package com.pd.base.model;

public class Typeset {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.TYPE_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String typeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.PAPER_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String paperId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.ROLE_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private Long roleId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.SETDESC
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String setdesc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.F1
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String f1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.F2
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String f2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.F3
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String f3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.F4
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String f4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TYPESET.F5
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private String f5;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.ID
	 * @return  the value of TYPESET.ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.ID
	 * @param id  the value for TYPESET.ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.TYPE_ID
	 * @return  the value of TYPESET.TYPE_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.TYPE_ID
	 * @param typeId  the value for TYPESET.TYPE_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.PAPER_ID
	 * @return  the value of TYPESET.PAPER_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getPaperId() {
		return paperId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.PAPER_ID
	 * @param paperId  the value for TYPESET.PAPER_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setPaperId(String paperId) {
		this.paperId = paperId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.ROLE_ID
	 * @return  the value of TYPESET.ROLE_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.ROLE_ID
	 * @param roleId  the value for TYPESET.ROLE_ID
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.SETDESC
	 * @return  the value of TYPESET.SETDESC
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getSetdesc() {
		return setdesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.SETDESC
	 * @param setdesc  the value for TYPESET.SETDESC
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setSetdesc(String setdesc) {
		this.setdesc = setdesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.F1
	 * @return  the value of TYPESET.F1
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getF1() {
		return f1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.F1
	 * @param f1  the value for TYPESET.F1
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setF1(String f1) {
		this.f1 = f1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.F2
	 * @return  the value of TYPESET.F2
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getF2() {
		return f2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.F2
	 * @param f2  the value for TYPESET.F2
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setF2(String f2) {
		this.f2 = f2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.F3
	 * @return  the value of TYPESET.F3
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getF3() {
		return f3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.F3
	 * @param f3  the value for TYPESET.F3
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setF3(String f3) {
		this.f3 = f3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.F4
	 * @return  the value of TYPESET.F4
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getF4() {
		return f4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.F4
	 * @param f4  the value for TYPESET.F4
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setF4(String f4) {
		this.f4 = f4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TYPESET.F5
	 * @return  the value of TYPESET.F5
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getF5() {
		return f5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TYPESET.F5
	 * @param f5  the value for TYPESET.F5
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setF5(String f5) {
		this.f5 = f5;
	}
}