package com.pd.wjyw.dao.impl;

import com.pd.system.framework.PageToExample;
import com.pd.wjyw.model.YcInfoPic;
import com.pd.wjyw.model.YcInfoPicExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class YcInfoPicDAOImpl extends SqlMapClientDaoSupport implements YcInfoPicDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public YcInfoPicDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public void insert(YcInfoPic record) {
		getSqlMapClientTemplate().insert("YC_INFO_PIC.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public int updateByPrimaryKey(YcInfoPic record) {
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO_PIC.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public int updateByPrimaryKeySelective(YcInfoPic record) {
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO_PIC.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public List selectByExample(YcInfoPicExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"YC_INFO_PIC.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public YcInfoPic selectByPrimaryKey(String id) {
		YcInfoPic key = new YcInfoPic();
		key.setId(id);
		YcInfoPic record = (YcInfoPic) getSqlMapClientTemplate()
				.queryForObject(
						"YC_INFO_PIC.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public int deleteByExample(YcInfoPicExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"YC_INFO_PIC.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		YcInfoPic key = new YcInfoPic();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"YC_INFO_PIC.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public int countByExample(YcInfoPicExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"YC_INFO_PIC.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public int updateByExampleSelective(YcInfoPic record,
			YcInfoPicExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO_PIC.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	public int updateByExample(YcInfoPic record, YcInfoPicExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO_PIC.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table YC_INFO_PIC
	 * @abatorgenerated  Fri Aug 08 11:57:38 CST 2014
	 */
	private static class UpdateByExampleParms extends YcInfoPicExample {
		private Object record;

		public UpdateByExampleParms(Object record, YcInfoPicExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	/**
	 * ??????
	 */
	@Override
	public List selectByExampleToPage(PageToExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"YC_INFO_PIC.abatorgenerated_selectByExampleToPage", example);
		return list;
	}
}