package com.pd.arc.model;

import java.util.Date;

public class ArcPicInfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.ID
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.XTDABH
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String xtdabh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.PIC_FILENAME
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String picFilename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.YWLX
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String ywlx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.SNTMC
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String sntmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.PAPER_ID
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String paperId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.SMRMC
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String smrmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.SMR
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String smr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.SMSJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private Date smsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.SMCS
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String smcs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.TPLJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String tplj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.SNTLJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String sntlj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.BZ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String bz;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.YTP
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String ytp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.TPLX
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String tplx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_PIC_INFO2.SFCS
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private String sfcs;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.ID
     *
     * @return the value of ARC_PIC_INFO2.ID
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.ID
     *
     * @param id the value for ARC_PIC_INFO2.ID
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.XTDABH
     *
     * @return the value of ARC_PIC_INFO2.XTDABH
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getXtdabh() {
        return xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.XTDABH
     *
     * @param xtdabh the value for ARC_PIC_INFO2.XTDABH
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setXtdabh(String xtdabh) {
        this.xtdabh = xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.PIC_FILENAME
     *
     * @return the value of ARC_PIC_INFO2.PIC_FILENAME
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getPicFilename() {
        return picFilename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.PIC_FILENAME
     *
     * @param picFilename the value for ARC_PIC_INFO2.PIC_FILENAME
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setPicFilename(String picFilename) {
        this.picFilename = picFilename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.YWLX
     *
     * @return the value of ARC_PIC_INFO2.YWLX
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getYwlx() {
        return ywlx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.YWLX
     *
     * @param ywlx the value for ARC_PIC_INFO2.YWLX
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setYwlx(String ywlx) {
        this.ywlx = ywlx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.SNTMC
     *
     * @return the value of ARC_PIC_INFO2.SNTMC
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getSntmc() {
        return sntmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.SNTMC
     *
     * @param sntmc the value for ARC_PIC_INFO2.SNTMC
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setSntmc(String sntmc) {
        this.sntmc = sntmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.PAPER_ID
     *
     * @return the value of ARC_PIC_INFO2.PAPER_ID
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.PAPER_ID
     *
     * @param paperId the value for ARC_PIC_INFO2.PAPER_ID
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.SMRMC
     *
     * @return the value of ARC_PIC_INFO2.SMRMC
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getSmrmc() {
        return smrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.SMRMC
     *
     * @param smrmc the value for ARC_PIC_INFO2.SMRMC
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setSmrmc(String smrmc) {
        this.smrmc = smrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.SMR
     *
     * @return the value of ARC_PIC_INFO2.SMR
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getSmr() {
        return smr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.SMR
     *
     * @param smr the value for ARC_PIC_INFO2.SMR
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setSmr(String smr) {
        this.smr = smr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.SMSJ
     *
     * @return the value of ARC_PIC_INFO2.SMSJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public Date getSmsj() {
        return smsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.SMSJ
     *
     * @param smsj the value for ARC_PIC_INFO2.SMSJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setSmsj(Date smsj) {
        this.smsj = smsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.SMCS
     *
     * @return the value of ARC_PIC_INFO2.SMCS
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getSmcs() {
        return smcs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.SMCS
     *
     * @param smcs the value for ARC_PIC_INFO2.SMCS
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setSmcs(String smcs) {
        this.smcs = smcs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.TPLJ
     *
     * @return the value of ARC_PIC_INFO2.TPLJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getTplj() {
        return tplj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.TPLJ
     *
     * @param tplj the value for ARC_PIC_INFO2.TPLJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setTplj(String tplj) {
        this.tplj = tplj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.SNTLJ
     *
     * @return the value of ARC_PIC_INFO2.SNTLJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getSntlj() {
        return sntlj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.SNTLJ
     *
     * @param sntlj the value for ARC_PIC_INFO2.SNTLJ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setSntlj(String sntlj) {
        this.sntlj = sntlj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.BZ
     *
     * @return the value of ARC_PIC_INFO2.BZ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.BZ
     *
     * @param bz the value for ARC_PIC_INFO2.BZ
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.YTP
     *
     * @return the value of ARC_PIC_INFO2.YTP
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getYtp() {
        return ytp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.YTP
     *
     * @param ytp the value for ARC_PIC_INFO2.YTP
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setYtp(String ytp) {
        this.ytp = ytp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.TPLX
     *
     * @return the value of ARC_PIC_INFO2.TPLX
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getTplx() {
        return tplx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.TPLX
     *
     * @param tplx the value for ARC_PIC_INFO2.TPLX
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setTplx(String tplx) {
        this.tplx = tplx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_PIC_INFO2.SFCS
     *
     * @return the value of ARC_PIC_INFO2.SFCS
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getSfcs() {
        return sfcs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_PIC_INFO2.SFCS
     *
     * @param sfcs the value for ARC_PIC_INFO2.SFCS
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setSfcs(String sfcs) {
        this.sfcs = sfcs;
    }
}