package com.pd.arc.dao.impl;

import java.util.List;
import java.util.Map;

import com.pd.arc.model.ArcBaseInfo;
import com.pd.arc.model.ArcBaseInfoExample;
import com.pd.arc.model.ArcBaseInfoSuper;
import com.pd.system.framework.BaseDAO;

public interface ArcBaseInfoDAO extends BaseDAO{
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    void insert(ArcBaseInfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    int updateByPrimaryKey(ArcBaseInfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    int updateByPrimaryKeySelective(ArcBaseInfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    List selectByExample(ArcBaseInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    ArcBaseInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    int deleteByExample(ArcBaseInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    int countByExample(ArcBaseInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    int updateByExampleSelective(ArcBaseInfo record, ArcBaseInfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_BASE_INFO
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    int updateByExample(ArcBaseInfo record, ArcBaseInfoExample example);
    
    /**
     * 审核归档工作量统计
    * @Title: getArcCheckNum 
    * @Description: TODO
    * @param @param map
    * @param @return    设定文件 
    * @return List<ArcBaseInfoSuper>    返回类型 
    * @throws 
    * @author zl
    * 2014-8-13
     */
	List<ArcBaseInfoSuper> getArcCheckNum(Map map);

	/**
	 * 统计扫描，审核归档入库的档案数量
	* @Title: getArcNum 
	* @Description: TODO
	* @param @param map
	* @param @return    设定文件 
	* @return List<ArcBaseInfoSuper>    返回类型 
	* @throws 
	* @author zl
	* 2014-8-14
	 */

	List<ArcBaseInfoSuper> getGdArcNum(Map map);

	List<ArcBaseInfoSuper> getShArcNum(Map map);

	List<ArcBaseInfoSuper> getSmArcNum(Map map);

	List<ArcBaseInfoSuper> getRkArcNum(Map map);
	
	/**
	 * 统计扫描一周的档案数量
	* @Title: getArcNum 
	* @Description: TODO
	* @param @param map
	* @param @return    设定文件 
	* @return List<ArcBaseInfoSuper>    返回类型 
	* @throws 
	* @author zl
	* 2014-8-14
	 */
	int getWeekArcNum(Map map);
	
	
	/**
	 * 获取某一格中最大储位编号的档案
	 * */
	List<ArcBaseInfo> findMaxCwbhArcByGeid(String geid);
	/**
	 * 获取某一格可用的储位序号，对于不连续的储位编号
	 * */
	Integer findUsableCwxh(String geid);

	List selectByExampleToPageOfQuerySh(ArcBaseInfoExample example);

	
}