package com.pd.arc.dao.impl;

import com.pd.arc.model.ArcCall;
import com.pd.arc.model.ArcCallExample;
import com.pd.system.framework.PageToExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArcCallDAOImpl extends SqlMapClientDaoSupport implements ArcCallDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public ArcCallDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public void insert(ArcCall record) {
        getSqlMapClientTemplate().insert("ARC_CALL.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public List selectByExample(ArcCallExample example) {
        List list = getSqlMapClientTemplate().queryForList("ARC_CALL.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public int deleteByExample(ArcCallExample example) {
        int rows = getSqlMapClientTemplate().delete("ARC_CALL.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public int countByExample(ArcCallExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ARC_CALL.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public int updateByExampleSelective(ArcCall record, ArcCallExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_CALL.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public int updateByExample(ArcCall record, ArcCallExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_CALL.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    private static class UpdateByExampleParms extends ArcCallExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArcCallExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List selectByExampleToPage(PageToExample example) {
		// TODO Auto-generated method stub
		return null;
	}

	
}