package com.pd.arc.dao.impl;

import com.pd.arc.model.ArcCall;
import com.pd.arc.model.ArcCallExample;
import com.pd.system.framework.BaseDAO;

import java.util.List;

public interface ArcCallDAO extends BaseDAO{
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    void insert(ArcCall record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    List selectByExample(ArcCallExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    int deleteByExample(ArcCallExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    int countByExample(ArcCallExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    int updateByExampleSelective(ArcCall record, ArcCallExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    int updateByExample(ArcCall record, ArcCallExample example);
}