package com.pd.arc.dao.impl;

import com.pd.arc.model.ArcCombInfo;
import com.pd.arc.model.ArcCombInfoExample;
import com.pd.system.framework.PageToExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArcCombInfoDAOImpl extends SqlMapClientDaoSupport implements ArcCombInfoDAO {

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public ArcCombInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public void insert(ArcCombInfo record) {
		getSqlMapClientTemplate().insert(
				"ARC_COMB_INFO.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public int updateByPrimaryKey(ArcCombInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"ARC_COMB_INFO.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public int updateByPrimaryKeySelective(ArcCombInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"ARC_COMB_INFO.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public List selectByExample(ArcCombInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"ARC_COMB_INFO.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public ArcCombInfo selectByPrimaryKey(String id) {
		ArcCombInfo key = new ArcCombInfo();
		key.setId(id);
		ArcCombInfo record = (ArcCombInfo) getSqlMapClientTemplate()
				.queryForObject(
						"ARC_COMB_INFO.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public int deleteByExample(ArcCombInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"ARC_COMB_INFO.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		ArcCombInfo key = new ArcCombInfo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"ARC_COMB_INFO.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public int countByExample(ArcCombInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"ARC_COMB_INFO.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public int updateByExampleSelective(ArcCombInfo record,
			ArcCombInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"ARC_COMB_INFO.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	public int updateByExample(ArcCombInfo record, ArcCombInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"ARC_COMB_INFO.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table ARC_COMB_INFO
	 * @abatorgenerated  Fri Aug 15 17:21:50 CST 2014
	 */
	private static class UpdateByExampleParms extends ArcCombInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, ArcCombInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List selectByExampleToPage(PageToExample example) {
		// TODO Auto-generated method stub
		return null;
	}
}