package com.pd.arc.dao.impl;

import com.pd.arc.model.ArcPicInfo;
import com.pd.arc.model.ArcPicInfoExample;
import com.pd.system.framework.PageToExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArcPicInfoDAOImpl extends SqlMapClientDaoSupport implements ArcPicInfoDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public ArcPicInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void insert(ArcPicInfo record) {
        getSqlMapClientTemplate().insert("ARC_PIC_INFO.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public int updateByPrimaryKey(ArcPicInfo record) {
        int rows = getSqlMapClientTemplate().update("ARC_PIC_INFO.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public int updateByPrimaryKeySelective(ArcPicInfo record) {
        int rows = getSqlMapClientTemplate().update("ARC_PIC_INFO.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public List selectByExample(ArcPicInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("ARC_PIC_INFO.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public ArcPicInfo selectByPrimaryKey(String id) {
        ArcPicInfo key = new ArcPicInfo();
        key.setId(id);
        ArcPicInfo record = (ArcPicInfo) getSqlMapClientTemplate().queryForObject("ARC_PIC_INFO.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public int deleteByExample(ArcPicInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("ARC_PIC_INFO.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public int deleteByPrimaryKey(String id) {
        ArcPicInfo key = new ArcPicInfo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("ARC_PIC_INFO.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public int countByExample(ArcPicInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ARC_PIC_INFO.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public int updateByExampleSelective(ArcPicInfo record, ArcPicInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_PIC_INFO.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public int updateByExample(ArcPicInfo record, ArcPicInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_PIC_INFO.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_PIC_INFO
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    private static class UpdateByExampleParms extends ArcPicInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArcPicInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List selectByExampleToPage(PageToExample example) {
		// TODO Auto-generated method stub
		return null;
	}
}