package com.pd.arc.dao.impl;

import com.pd.arc.model.ArcRescanInfo;
import com.pd.arc.model.ArcRescanInfoExample;
import com.pd.system.framework.PageToExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArcRescanInfoDAOImpl extends SqlMapClientDaoSupport implements ArcRescanInfoDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public ArcRescanInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public void insert(ArcRescanInfo record) {
        getSqlMapClientTemplate().insert("ARC_RESCAN_INFO.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public int updateByPrimaryKey(ArcRescanInfo record) {
        int rows = getSqlMapClientTemplate().update("ARC_RESCAN_INFO.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public int updateByPrimaryKeySelective(ArcRescanInfo record) {
        int rows = getSqlMapClientTemplate().update("ARC_RESCAN_INFO.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public List selectByExample(ArcRescanInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("ARC_RESCAN_INFO.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public ArcRescanInfo selectByPrimaryKey(String id) {
        ArcRescanInfo key = new ArcRescanInfo();
        key.setId(id);
        ArcRescanInfo record = (ArcRescanInfo) getSqlMapClientTemplate().queryForObject("ARC_RESCAN_INFO.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public int deleteByExample(ArcRescanInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("ARC_RESCAN_INFO.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public int deleteByPrimaryKey(String id) {
        ArcRescanInfo key = new ArcRescanInfo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("ARC_RESCAN_INFO.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public int countByExample(ArcRescanInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ARC_RESCAN_INFO.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public int updateByExampleSelective(ArcRescanInfo record, ArcRescanInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_RESCAN_INFO.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public int updateByExample(ArcRescanInfo record, ArcRescanInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_RESCAN_INFO.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    private static class UpdateByExampleParms extends ArcRescanInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArcRescanInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    @Override
	public List selectByExampleToPage(PageToExample example) {
		List list = getSqlMapClientTemplate().queryForList("ARC_RESCAN_INFO.abatorgenerated_selectByExampleToPage", example);
        return list;
	}
}