package com.pd.right.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.right.model.Dept;
import com.pd.right.model.DeptExample;

public class DeptDAOImpl extends SqlMapClientDaoSupport implements DeptDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public DeptDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void insert(Dept record) {
        getSqlMapClientTemplate().insert("DEPT.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByPrimaryKey(Dept record) {
        int rows = getSqlMapClientTemplate().update("DEPT.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByPrimaryKeySelective(Dept record) {
        int rows = getSqlMapClientTemplate().update("DEPT.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public List selectByExample(DeptExample example) {
        List list = getSqlMapClientTemplate().queryForList("DEPT.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public Dept selectByPrimaryKey(String deptcode) {
        Dept key = new Dept();
        key.setDeptcode(deptcode);
        Dept record = (Dept) getSqlMapClientTemplate().queryForObject("DEPT.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int deleteByExample(DeptExample example) {
        int rows = getSqlMapClientTemplate().delete("DEPT.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int deleteByPrimaryKey(String deptcode) {
        Dept key = new Dept();
        key.setDeptcode(deptcode);
        int rows = getSqlMapClientTemplate().delete("DEPT.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int countByExample(DeptExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("DEPT.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByExampleSelective(Dept record, DeptExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DEPT.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByExample(Dept record, DeptExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("DEPT.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table DEPT
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private static class UpdateByExampleParms extends DeptExample {
        private Object record;

        public UpdateByExampleParms(Object record, DeptExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public List<Dept> selectByExampleToPage(DeptExample example) {
		 List<Dept> list = getSqlMapClientTemplate().queryForList("DEPT.abatorgenerated_selectByExampleToPage", example);
	     return list;
	}
}