package com.pd.right.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import com.pd.system.framework.PageToExample;

public class LogExample extends PageToExample{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public LogExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    protected LogExample(LogExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andCzsjIsNull() {
            addCriterion("CZSJ is null");
            return this;
        }

        public Criteria andCzsjIsNotNull() {
            addCriterion("CZSJ is not null");
            return this;
        }

        public Criteria andCzsjEqualTo(Date value) {
            addCriterionForJDBCDate("CZSJ =", value, "czsj");
            return this;
        }

        public Criteria andCzsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("CZSJ <>", value, "czsj");
            return this;
        }

        public Criteria andCzsjGreaterThan(Date value) {
            addCriterionForJDBCDate("CZSJ >", value, "czsj");
            return this;
        }

        public Criteria andCzsjGreaterThanOrEqualTo(String value) {
        	addCriterion("to_char(CZSJ,'yyyy-mm-dd') >=", value, "czsj");
            return this;
        }

        public Criteria andCzsjLessThan(Date value) {
            addCriterionForJDBCDate("CZSJ <", value, "czsj");
            return this;
        }

        public Criteria andCzsjLessThanOrEqualTo(String value) {
        	addCriterion("to_char(CZSJ,'yyyy-mm-dd')<=", value, "czsj");
            return this;
        }

        public Criteria andCzsjIn(List values) {
            addCriterionForJDBCDate("CZSJ in", values, "czsj");
            return this;
        }

        public Criteria andCzsjNotIn(List values) {
            addCriterionForJDBCDate("CZSJ not in", values, "czsj");
            return this;
        }

        public Criteria andCzsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CZSJ between", value1, value2, "czsj");
            return this;
        }

        public Criteria andCzsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CZSJ not between", value1, value2, "czsj");
            return this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("USER_CODE is null");
            return this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("USER_CODE is not null");
            return this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("USER_CODE =", value, "userCode");
            return this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("USER_CODE <>", value, "userCode");
            return this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("USER_CODE >", value, "userCode");
            return this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_CODE >=", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("USER_CODE <", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("USER_CODE <=", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("USER_CODE like", value, "userCode");
            return this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("USER_CODE not like", value, "userCode");
            return this;
        }

        public Criteria andUserCodeIn(List values) {
            addCriterion("USER_CODE in", values, "userCode");
            return this;
        }

        public Criteria andUserCodeNotIn(List values) {
            addCriterion("USER_CODE not in", values, "userCode");
            return this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("USER_CODE between", value1, value2, "userCode");
            return this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("USER_CODE not between", value1, value2, "userCode");
            return this;
        }

        public Criteria andProgramIsNull() {
            addCriterion("PROGRAM is null");
            return this;
        }

        public Criteria andProgramIsNotNull() {
            addCriterion("PROGRAM is not null");
            return this;
        }

        public Criteria andProgramEqualTo(Long value) {
            addCriterion("PROGRAM =", value, "program");
            return this;
        }

        public Criteria andProgramNotEqualTo(Long value) {
            addCriterion("PROGRAM <>", value, "program");
            return this;
        }

        public Criteria andProgramGreaterThan(Long value) {
            addCriterion("PROGRAM >", value, "program");
            return this;
        }

        public Criteria andProgramGreaterThanOrEqualTo(Long value) {
            addCriterion("PROGRAM >=", value, "program");
            return this;
        }

        public Criteria andProgramLessThan(Long value) {
            addCriterion("PROGRAM <", value, "program");
            return this;
        }

        public Criteria andProgramLessThanOrEqualTo(Long value) {
            addCriterion("PROGRAM <=", value, "program");
            return this;
        }

        public Criteria andProgramIn(List values) {
            addCriterion("PROGRAM in", values, "program");
            return this;
        }

        public Criteria andProgramNotIn(List values) {
            addCriterion("PROGRAM not in", values, "program");
            return this;
        }

        public Criteria andProgramBetween(Long value1, Long value2) {
            addCriterion("PROGRAM between", value1, value2, "program");
            return this;
        }

        public Criteria andProgramNotBetween(Long value1, Long value2) {
            addCriterion("PROGRAM not between", value1, value2, "program");
            return this;
        }

        public Criteria andCzIsNull() {
            addCriterion("CZ is null");
            return this;
        }

        public Criteria andCzIsNotNull() {
            addCriterion("CZ is not null");
            return this;
        }

        public Criteria andCzEqualTo(String value) {
            addCriterion("CZ =", value, "cz");
            return this;
        }

        public Criteria andCzNotEqualTo(String value) {
            addCriterion("CZ <>", value, "cz");
            return this;
        }

        public Criteria andCzGreaterThan(String value) {
            addCriterion("CZ >", value, "cz");
            return this;
        }

        public Criteria andCzGreaterThanOrEqualTo(String value) {
            addCriterion("CZ >=", value, "cz");
            return this;
        }

        public Criteria andCzLessThan(String value) {
            addCriterion("CZ <", value, "cz");
            return this;
        }

        public Criteria andCzLessThanOrEqualTo(String value) {
            addCriterion("CZ <=", value, "cz");
            return this;
        }

        public Criteria andCzLike(String value) {
            addCriterion("CZ like", value, "cz");
            return this;
        }

        public Criteria andCzNotLike(String value) {
            addCriterion("CZ not like", value, "cz");
            return this;
        }

        public Criteria andCzIn(List values) {
            addCriterion("CZ in", values, "cz");
            return this;
        }

        public Criteria andCzNotIn(List values) {
            addCriterion("CZ not in", values, "cz");
            return this;
        }

        public Criteria andCzBetween(String value1, String value2) {
            addCriterion("CZ between", value1, value2, "cz");
            return this;
        }

        public Criteria andCzNotBetween(String value1, String value2) {
            addCriterion("CZ not between", value1, value2, "cz");
            return this;
        }

        public Criteria andXxsmIsNull() {
            addCriterion("XXSM is null");
            return this;
        }

        public Criteria andXxsmIsNotNull() {
            addCriterion("XXSM is not null");
            return this;
        }

        public Criteria andXxsmEqualTo(String value) {
            addCriterion("XXSM =", value, "xxsm");
            return this;
        }

        public Criteria andXxsmNotEqualTo(String value) {
            addCriterion("XXSM <>", value, "xxsm");
            return this;
        }

        public Criteria andXxsmGreaterThan(String value) {
            addCriterion("XXSM >", value, "xxsm");
            return this;
        }

        public Criteria andXxsmGreaterThanOrEqualTo(String value) {
            addCriterion("XXSM >=", value, "xxsm");
            return this;
        }

        public Criteria andXxsmLessThan(String value) {
            addCriterion("XXSM <", value, "xxsm");
            return this;
        }

        public Criteria andXxsmLessThanOrEqualTo(String value) {
            addCriterion("XXSM <=", value, "xxsm");
            return this;
        }

        public Criteria andXxsmLike(String value) {
            addCriterion("XXSM like", value, "xxsm");
            return this;
        }

        public Criteria andXxsmNotLike(String value) {
            addCriterion("XXSM not like", value, "xxsm");
            return this;
        }

        public Criteria andXxsmIn(List values) {
            addCriterion("XXSM in", values, "xxsm");
            return this;
        }

        public Criteria andXxsmNotIn(List values) {
            addCriterion("XXSM not in", values, "xxsm");
            return this;
        }

        public Criteria andXxsmBetween(String value1, String value2) {
            addCriterion("XXSM between", value1, value2, "xxsm");
            return this;
        }

        public Criteria andXxsmNotBetween(String value1, String value2) {
            addCriterion("XXSM not between", value1, value2, "xxsm");
            return this;
        }

        public Criteria andCzipIsNull() {
            addCriterion("CZIP is null");
            return this;
        }

        public Criteria andCzipIsNotNull() {
            addCriterion("CZIP is not null");
            return this;
        }

        public Criteria andCzipEqualTo(String value) {
            addCriterion("CZIP =", value, "czip");
            return this;
        }

        public Criteria andCzipNotEqualTo(String value) {
            addCriterion("CZIP <>", value, "czip");
            return this;
        }

        public Criteria andCzipGreaterThan(String value) {
            addCriterion("CZIP >", value, "czip");
            return this;
        }

        public Criteria andCzipGreaterThanOrEqualTo(String value) {
            addCriterion("CZIP >=", value, "czip");
            return this;
        }

        public Criteria andCzipLessThan(String value) {
            addCriterion("CZIP <", value, "czip");
            return this;
        }

        public Criteria andCzipLessThanOrEqualTo(String value) {
            addCriterion("CZIP <=", value, "czip");
            return this;
        }

        public Criteria andCzipLike(String value) {
            addCriterion("CZIP like", value, "czip");
            return this;
        }

        public Criteria andCzipNotLike(String value) {
            addCriterion("CZIP not like", value, "czip");
            return this;
        }

        public Criteria andCzipIn(List values) {
            addCriterion("CZIP in", values, "czip");
            return this;
        }

        public Criteria andCzipNotIn(List values) {
            addCriterion("CZIP not in", values, "czip");
            return this;
        }

        public Criteria andCzipBetween(String value1, String value2) {
            addCriterion("CZIP between", value1, value2, "czip");
            return this;
        }

        public Criteria andCzipNotBetween(String value1, String value2) {
            addCriterion("CZIP not between", value1, value2, "czip");
            return this;
        }

        public Criteria andJmwIsNull() {
            addCriterion("JMW is null");
            return this;
        }

        public Criteria andJmwIsNotNull() {
            addCriterion("JMW is not null");
            return this;
        }

        public Criteria andJmwEqualTo(String value) {
            addCriterion("JMW =", value, "jmw");
            return this;
        }

        public Criteria andJmwNotEqualTo(String value) {
            addCriterion("JMW <>", value, "jmw");
            return this;
        }

        public Criteria andJmwGreaterThan(String value) {
            addCriterion("JMW >", value, "jmw");
            return this;
        }

        public Criteria andJmwGreaterThanOrEqualTo(String value) {
            addCriterion("JMW >=", value, "jmw");
            return this;
        }

        public Criteria andJmwLessThan(String value) {
            addCriterion("JMW <", value, "jmw");
            return this;
        }

        public Criteria andJmwLessThanOrEqualTo(String value) {
            addCriterion("JMW <=", value, "jmw");
            return this;
        }

        public Criteria andJmwLike(String value) {
            addCriterion("JMW like", value, "jmw");
            return this;
        }

        public Criteria andJmwNotLike(String value) {
            addCriterion("JMW not like", value, "jmw");
            return this;
        }

        public Criteria andJmwIn(List values) {
            addCriterion("JMW in", values, "jmw");
            return this;
        }

        public Criteria andJmwNotIn(List values) {
            addCriterion("JMW not in", values, "jmw");
            return this;
        }

        public Criteria andJmwBetween(String value1, String value2) {
            addCriterion("JMW between", value1, value2, "jmw");
            return this;
        }

        public Criteria andJmwNotBetween(String value1, String value2) {
            addCriterion("JMW not between", value1, value2, "jmw");
            return this;
        }

        public Criteria andF1IsNull() {
            addCriterion("F1 is null");
            return this;
        }

        public Criteria andF1IsNotNull() {
            addCriterion("F1 is not null");
            return this;
        }

        public Criteria andF1EqualTo(String value) {
            addCriterion("F1 =", value, "f1");
            return this;
        }

        public Criteria andF1NotEqualTo(String value) {
            addCriterion("F1 <>", value, "f1");
            return this;
        }

        public Criteria andF1GreaterThan(String value) {
            addCriterion("F1 >", value, "f1");
            return this;
        }

        public Criteria andF1GreaterThanOrEqualTo(String value) {
            addCriterion("F1 >=", value, "f1");
            return this;
        }

        public Criteria andF1LessThan(String value) {
            addCriterion("F1 <", value, "f1");
            return this;
        }

        public Criteria andF1LessThanOrEqualTo(String value) {
            addCriterion("F1 <=", value, "f1");
            return this;
        }

        public Criteria andF1Like(String value) {
            addCriterion("F1 like", value, "f1");
            return this;
        }

        public Criteria andF1NotLike(String value) {
            addCriterion("F1 not like", value, "f1");
            return this;
        }

        public Criteria andF1In(List values) {
            addCriterion("F1 in", values, "f1");
            return this;
        }

        public Criteria andF1NotIn(List values) {
            addCriterion("F1 not in", values, "f1");
            return this;
        }

        public Criteria andF1Between(String value1, String value2) {
            addCriterion("F1 between", value1, value2, "f1");
            return this;
        }

        public Criteria andF1NotBetween(String value1, String value2) {
            addCriterion("F1 not between", value1, value2, "f1");
            return this;
        }

        public Criteria andF2IsNull() {
            addCriterion("F2 is null");
            return this;
        }

        public Criteria andF2IsNotNull() {
            addCriterion("F2 is not null");
            return this;
        }

        public Criteria andF2EqualTo(String value) {
            addCriterion("F2 =", value, "f2");
            return this;
        }

        public Criteria andF2NotEqualTo(String value) {
            addCriterion("F2 <>", value, "f2");
            return this;
        }

        public Criteria andF2GreaterThan(String value) {
            addCriterion("F2 >", value, "f2");
            return this;
        }

        public Criteria andF2GreaterThanOrEqualTo(String value) {
            addCriterion("F2 >=", value, "f2");
            return this;
        }

        public Criteria andF2LessThan(String value) {
            addCriterion("F2 <", value, "f2");
            return this;
        }

        public Criteria andF2LessThanOrEqualTo(String value) {
            addCriterion("F2 <=", value, "f2");
            return this;
        }

        public Criteria andF2Like(String value) {
            addCriterion("F2 like", value, "f2");
            return this;
        }

        public Criteria andF2NotLike(String value) {
            addCriterion("F2 not like", value, "f2");
            return this;
        }

        public Criteria andF2In(List values) {
            addCriterion("F2 in", values, "f2");
            return this;
        }

        public Criteria andF2NotIn(List values) {
            addCriterion("F2 not in", values, "f2");
            return this;
        }

        public Criteria andF2Between(String value1, String value2) {
            addCriterion("F2 between", value1, value2, "f2");
            return this;
        }

        public Criteria andF2NotBetween(String value1, String value2) {
            addCriterion("F2 not between", value1, value2, "f2");
            return this;
        }

        public Criteria andF3IsNull() {
            addCriterion("F3 is null");
            return this;
        }

        public Criteria andF3IsNotNull() {
            addCriterion("F3 is not null");
            return this;
        }

        public Criteria andF3EqualTo(String value) {
            addCriterion("F3 =", value, "f3");
            return this;
        }

        public Criteria andF3NotEqualTo(String value) {
            addCriterion("F3 <>", value, "f3");
            return this;
        }

        public Criteria andF3GreaterThan(String value) {
            addCriterion("F3 >", value, "f3");
            return this;
        }

        public Criteria andF3GreaterThanOrEqualTo(String value) {
            addCriterion("F3 >=", value, "f3");
            return this;
        }

        public Criteria andF3LessThan(String value) {
            addCriterion("F3 <", value, "f3");
            return this;
        }

        public Criteria andF3LessThanOrEqualTo(String value) {
            addCriterion("F3 <=", value, "f3");
            return this;
        }

        public Criteria andF3Like(String value) {
            addCriterion("F3 like", value, "f3");
            return this;
        }

        public Criteria andF3NotLike(String value) {
            addCriterion("F3 not like", value, "f3");
            return this;
        }

        public Criteria andF3In(List values) {
            addCriterion("F3 in", values, "f3");
            return this;
        }

        public Criteria andF3NotIn(List values) {
            addCriterion("F3 not in", values, "f3");
            return this;
        }

        public Criteria andF3Between(String value1, String value2) {
            addCriterion("F3 between", value1, value2, "f3");
            return this;
        }

        public Criteria andF3NotBetween(String value1, String value2) {
            addCriterion("F3 not between", value1, value2, "f3");
            return this;
        }

        public Criteria andLogtypeIsNull() {
            addCriterion("LOGTYPE is null");
            return this;
        }

        public Criteria andLogtypeIsNotNull() {
            addCriterion("LOGTYPE is not null");
            return this;
        }

        public Criteria andLogtypeEqualTo(String value) {
            addCriterion("LOGTYPE =", value, "logtype");
            return this;
        }

        public Criteria andLogtypeNotEqualTo(String value) {
            addCriterion("LOGTYPE <>", value, "logtype");
            return this;
        }

        public Criteria andLogtypeGreaterThan(String value) {
            addCriterion("LOGTYPE >", value, "logtype");
            return this;
        }

        public Criteria andLogtypeGreaterThanOrEqualTo(String value) {
            addCriterion("LOGTYPE >=", value, "logtype");
            return this;
        }

        public Criteria andLogtypeLessThan(String value) {
            addCriterion("LOGTYPE <", value, "logtype");
            return this;
        }

        public Criteria andLogtypeLessThanOrEqualTo(String value) {
            addCriterion("LOGTYPE <=", value, "logtype");
            return this;
        }

        public Criteria andLogtypeLike(String value) {
            addCriterion("LOGTYPE like", value, "logtype");
            return this;
        }

        public Criteria andLogtypeNotLike(String value) {
            addCriterion("LOGTYPE not like", value, "logtype");
            return this;
        }

        public Criteria andLogtypeIn(List values) {
            addCriterion("LOGTYPE in", values, "logtype");
            return this;
        }

        public Criteria andLogtypeNotIn(List values) {
            addCriterion("LOGTYPE not in", values, "logtype");
            return this;
        }

        public Criteria andLogtypeBetween(String value1, String value2) {
            addCriterion("LOGTYPE between", value1, value2, "logtype");
            return this;
        }

        public Criteria andLogtypeNotBetween(String value1, String value2) {
            addCriterion("LOGTYPE not between", value1, value2, "logtype");
            return this;
        }
    }
}