package com.pd.right.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import com.pd.system.framework.PageToExample;

public class UsersExample extends PageToExample{

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public UsersExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	protected UsersExample(UsersExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andUserCodeIsNull() {
			addCriterion("USER_CODE is null");
			return this;
		}

		public Criteria andUserCodeIsNotNull() {
			addCriterion("USER_CODE is not null");
			return this;
		}

		public Criteria andUserCodeEqualTo(String value) {
			addCriterion("USER_CODE =", value, "userCode");
			return this;
		}

		public Criteria andUserCodeNotEqualTo(String value) {
			addCriterion("USER_CODE <>", value, "userCode");
			return this;
		}

		public Criteria andUserCodeGreaterThan(String value) {
			addCriterion("USER_CODE >", value, "userCode");
			return this;
		}

		public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
			addCriterion("USER_CODE >=", value, "userCode");
			return this;
		}

		public Criteria andUserCodeLessThan(String value) {
			addCriterion("USER_CODE <", value, "userCode");
			return this;
		}

		public Criteria andUserCodeLessThanOrEqualTo(String value) {
			addCriterion("USER_CODE <=", value, "userCode");
			return this;
		}

		public Criteria andUserCodeLike(String value) {
			addCriterion("USER_CODE like", value, "userCode");
			return this;
		}

		public Criteria andUserCodeNotLike(String value) {
			addCriterion("USER_CODE not like", value, "userCode");
			return this;
		}

		public Criteria andUserCodeIn(List values) {
			addCriterion("USER_CODE in", values, "userCode");
			return this;
		}

		public Criteria andUserCodeNotIn(List values) {
			addCriterion("USER_CODE not in", values, "userCode");
			return this;
		}

		public Criteria andUserCodeBetween(String value1, String value2) {
			addCriterion("USER_CODE between", value1, value2, "userCode");
			return this;
		}

		public Criteria andUserCodeNotBetween(String value1, String value2) {
			addCriterion("USER_CODE not between", value1, value2, "userCode");
			return this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("USER_NAME is null");
			return this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("USER_NAME is not null");
			return this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("USER_NAME =", value, "userName");
			return this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("USER_NAME <>", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("USER_NAME >", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("USER_NAME >=", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("USER_NAME <", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("USER_NAME <=", value, "userName");
			return this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("USER_NAME like", value, "userName");
			return this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("USER_NAME not like", value, "userName");
			return this;
		}

		public Criteria andUserNameIn(List values) {
			addCriterion("USER_NAME in", values, "userName");
			return this;
		}

		public Criteria andUserNameNotIn(List values) {
			addCriterion("USER_NAME not in", values, "userName");
			return this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("USER_NAME between", value1, value2, "userName");
			return this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("USER_NAME not between", value1, value2, "userName");
			return this;
		}

		public Criteria andNickNameIsNull() {
			addCriterion("NICK_NAME is null");
			return this;
		}

		public Criteria andNickNameIsNotNull() {
			addCriterion("NICK_NAME is not null");
			return this;
		}

		public Criteria andNickNameEqualTo(String value) {
			addCriterion("NICK_NAME =", value, "nickName");
			return this;
		}

		public Criteria andNickNameNotEqualTo(String value) {
			addCriterion("NICK_NAME <>", value, "nickName");
			return this;
		}

		public Criteria andNickNameGreaterThan(String value) {
			addCriterion("NICK_NAME >", value, "nickName");
			return this;
		}

		public Criteria andNickNameGreaterThanOrEqualTo(String value) {
			addCriterion("NICK_NAME >=", value, "nickName");
			return this;
		}

		public Criteria andNickNameLessThan(String value) {
			addCriterion("NICK_NAME <", value, "nickName");
			return this;
		}

		public Criteria andNickNameLessThanOrEqualTo(String value) {
			addCriterion("NICK_NAME <=", value, "nickName");
			return this;
		}

		public Criteria andNickNameLike(String value) {
			addCriterion("NICK_NAME like", value, "nickName");
			return this;
		}

		public Criteria andNickNameNotLike(String value) {
			addCriterion("NICK_NAME not like", value, "nickName");
			return this;
		}

		public Criteria andNickNameIn(List values) {
			addCriterion("NICK_NAME in", values, "nickName");
			return this;
		}

		public Criteria andNickNameNotIn(List values) {
			addCriterion("NICK_NAME not in", values, "nickName");
			return this;
		}

		public Criteria andNickNameBetween(String value1, String value2) {
			addCriterion("NICK_NAME between", value1, value2, "nickName");
			return this;
		}

		public Criteria andNickNameNotBetween(String value1, String value2) {
			addCriterion("NICK_NAME not between", value1, value2, "nickName");
			return this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return this;
		}

		public Criteria andPasswordIn(List values) {
			addCriterion("PASSWORD in", values, "password");
			return this;
		}

		public Criteria andPasswordNotIn(List values) {
			addCriterion("PASSWORD not in", values, "password");
			return this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return this;
		}

		public Criteria andUserGenderIsNull() {
			addCriterion("USER_GENDER is null");
			return this;
		}

		public Criteria andUserGenderIsNotNull() {
			addCriterion("USER_GENDER is not null");
			return this;
		}

		public Criteria andUserGenderEqualTo(Short value) {
			addCriterion("USER_GENDER =", value, "userGender");
			return this;
		}

		public Criteria andUserGenderNotEqualTo(Short value) {
			addCriterion("USER_GENDER <>", value, "userGender");
			return this;
		}

		public Criteria andUserGenderGreaterThan(Short value) {
			addCriterion("USER_GENDER >", value, "userGender");
			return this;
		}

		public Criteria andUserGenderGreaterThanOrEqualTo(Short value) {
			addCriterion("USER_GENDER >=", value, "userGender");
			return this;
		}

		public Criteria andUserGenderLessThan(Short value) {
			addCriterion("USER_GENDER <", value, "userGender");
			return this;
		}

		public Criteria andUserGenderLessThanOrEqualTo(Short value) {
			addCriterion("USER_GENDER <=", value, "userGender");
			return this;
		}

		public Criteria andUserGenderIn(List values) {
			addCriterion("USER_GENDER in", values, "userGender");
			return this;
		}

		public Criteria andUserGenderNotIn(List values) {
			addCriterion("USER_GENDER not in", values, "userGender");
			return this;
		}

		public Criteria andUserGenderBetween(Short value1, Short value2) {
			addCriterion("USER_GENDER between", value1, value2, "userGender");
			return this;
		}

		public Criteria andUserGenderNotBetween(Short value1, Short value2) {
			addCriterion("USER_GENDER not between", value1, value2,
					"userGender");
			return this;
		}

		public Criteria andBornDateIsNull() {
			addCriterion("BORN_DATE is null");
			return this;
		}

		public Criteria andBornDateIsNotNull() {
			addCriterion("BORN_DATE is not null");
			return this;
		}

		public Criteria andBornDateEqualTo(Date value) {
			addCriterionForJDBCDate("BORN_DATE =", value, "bornDate");
			return this;
		}

		public Criteria andBornDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("BORN_DATE <>", value, "bornDate");
			return this;
		}

		public Criteria andBornDateGreaterThan(Date value) {
			addCriterionForJDBCDate("BORN_DATE >", value, "bornDate");
			return this;
		}

		public Criteria andBornDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("BORN_DATE >=", value, "bornDate");
			return this;
		}

		public Criteria andBornDateLessThan(Date value) {
			addCriterionForJDBCDate("BORN_DATE <", value, "bornDate");
			return this;
		}

		public Criteria andBornDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("BORN_DATE <=", value, "bornDate");
			return this;
		}

		public Criteria andBornDateIn(List values) {
			addCriterionForJDBCDate("BORN_DATE in", values, "bornDate");
			return this;
		}

		public Criteria andBornDateNotIn(List values) {
			addCriterionForJDBCDate("BORN_DATE not in", values, "bornDate");
			return this;
		}

		public Criteria andBornDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("BORN_DATE between", value1, value2,
					"bornDate");
			return this;
		}

		public Criteria andBornDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("BORN_DATE not between", value1, value2,
					"bornDate");
			return this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
			return this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateIn(List values) {
			addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateNotIn(List values) {
			addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE between", value1, value2,
					"createDate");
			return this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE not between", value1, value2,
					"createDate");
			return this;
		}

		public Criteria andUserstatIsNull() {
			addCriterion("USERSTAT is null");
			return this;
		}

		public Criteria andUserstatIsNotNull() {
			addCriterion("USERSTAT is not null");
			return this;
		}

		public Criteria andUserstatEqualTo(Short value) {
			addCriterion("USERSTAT =", value, "userstat");
			return this;
		}

		public Criteria andUserstatNotEqualTo(Short value) {
			addCriterion("USERSTAT <>", value, "userstat");
			return this;
		}

		public Criteria andUserstatGreaterThan(Short value) {
			addCriterion("USERSTAT >", value, "userstat");
			return this;
		}

		public Criteria andUserstatGreaterThanOrEqualTo(Short value) {
			addCriterion("USERSTAT >=", value, "userstat");
			return this;
		}

		public Criteria andUserstatLessThan(Short value) {
			addCriterion("USERSTAT <", value, "userstat");
			return this;
		}

		public Criteria andUserstatLessThanOrEqualTo(Short value) {
			addCriterion("USERSTAT <=", value, "userstat");
			return this;
		}

		public Criteria andUserstatIn(List values) {
			addCriterion("USERSTAT in", values, "userstat");
			return this;
		}

		public Criteria andUserstatNotIn(List values) {
			addCriterion("USERSTAT not in", values, "userstat");
			return this;
		}

		public Criteria andUserstatBetween(Short value1, Short value2) {
			addCriterion("USERSTAT between", value1, value2, "userstat");
			return this;
		}

		public Criteria andUserstatNotBetween(Short value1, Short value2) {
			addCriterion("USERSTAT not between", value1, value2, "userstat");
			return this;
		}

		public Criteria andCaridIsNull() {
			addCriterion("CARID is null");
			return this;
		}

		public Criteria andCaridIsNotNull() {
			addCriterion("CARID is not null");
			return this;
		}

		public Criteria andCaridEqualTo(String value) {
			addCriterion("CARID =", value, "carid");
			return this;
		}

		public Criteria andCaridNotEqualTo(String value) {
			addCriterion("CARID <>", value, "carid");
			return this;
		}

		public Criteria andCaridGreaterThan(String value) {
			addCriterion("CARID >", value, "carid");
			return this;
		}

		public Criteria andCaridGreaterThanOrEqualTo(String value) {
			addCriterion("CARID >=", value, "carid");
			return this;
		}

		public Criteria andCaridLessThan(String value) {
			addCriterion("CARID <", value, "carid");
			return this;
		}

		public Criteria andCaridLessThanOrEqualTo(String value) {
			addCriterion("CARID <=", value, "carid");
			return this;
		}

		public Criteria andCaridLike(String value) {
			addCriterion("CARID like", value, "carid");
			return this;
		}

		public Criteria andCaridNotLike(String value) {
			addCriterion("CARID not like", value, "carid");
			return this;
		}

		public Criteria andCaridIn(List values) {
			addCriterion("CARID in", values, "carid");
			return this;
		}

		public Criteria andCaridNotIn(List values) {
			addCriterion("CARID not in", values, "carid");
			return this;
		}

		public Criteria andCaridBetween(String value1, String value2) {
			addCriterion("CARID between", value1, value2, "carid");
			return this;
		}

		public Criteria andCaridNotBetween(String value1, String value2) {
			addCriterion("CARID not between", value1, value2, "carid");
			return this;
		}

		public Criteria andSignTypeIsNull() {
			addCriterion("SIGN_TYPE is null");
			return this;
		}

		public Criteria andSignTypeIsNotNull() {
			addCriterion("SIGN_TYPE is not null");
			return this;
		}

		public Criteria andSignTypeEqualTo(BigDecimal value) {
			addCriterion("SIGN_TYPE =", value, "signType");
			return this;
		}

		public Criteria andSignTypeNotEqualTo(BigDecimal value) {
			addCriterion("SIGN_TYPE <>", value, "signType");
			return this;
		}

		public Criteria andSignTypeGreaterThan(BigDecimal value) {
			addCriterion("SIGN_TYPE >", value, "signType");
			return this;
		}

		public Criteria andSignTypeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SIGN_TYPE >=", value, "signType");
			return this;
		}

		public Criteria andSignTypeLessThan(BigDecimal value) {
			addCriterion("SIGN_TYPE <", value, "signType");
			return this;
		}

		public Criteria andSignTypeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SIGN_TYPE <=", value, "signType");
			return this;
		}

		public Criteria andSignTypeIn(List values) {
			addCriterion("SIGN_TYPE in", values, "signType");
			return this;
		}

		public Criteria andSignTypeNotIn(List values) {
			addCriterion("SIGN_TYPE not in", values, "signType");
			return this;
		}

		public Criteria andSignTypeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SIGN_TYPE between", value1, value2, "signType");
			return this;
		}

		public Criteria andSignTypeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SIGN_TYPE not between", value1, value2, "signType");
			return this;
		}

		public Criteria andDeptCodeIsNull() {
			addCriterion("DEPT_CODE is null");
			return this;
		}

		public Criteria andDeptCodeIsNotNull() {
			addCriterion("DEPT_CODE is not null");
			return this;
		}

		public Criteria andDeptCodeEqualTo(String value) {
			addCriterion("DEPT_CODE =", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeNotEqualTo(String value) {
			addCriterion("DEPT_CODE <>", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeGreaterThan(String value) {
			addCriterion("DEPT_CODE >", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeGreaterThanOrEqualTo(String value) {
			addCriterion("DEPT_CODE >=", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeLessThan(String value) {
			addCriterion("DEPT_CODE <", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeLessThanOrEqualTo(String value) {
			addCriterion("DEPT_CODE <=", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeLike(String value) {
			addCriterion("DEPT_CODE like", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeNotLike(String value) {
			addCriterion("DEPT_CODE not like", value, "deptCode");
			return this;
		}

		public Criteria andDeptCodeIn(List values) {
			addCriterion("DEPT_CODE in", values, "deptCode");
			return this;
		}

		public Criteria andDeptCodeNotIn(List values) {
			addCriterion("DEPT_CODE not in", values, "deptCode");
			return this;
		}

		public Criteria andDeptCodeBetween(String value1, String value2) {
			addCriterion("DEPT_CODE between", value1, value2, "deptCode");
			return this;
		}

		public Criteria andDeptCodeNotBetween(String value1, String value2) {
			addCriterion("DEPT_CODE not between", value1, value2, "deptCode");
			return this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return this;
		}

		public Criteria andAddressIn(List values) {
			addCriterion("ADDRESS in", values, "address");
			return this;
		}

		public Criteria andAddressNotIn(List values) {
			addCriterion("ADDRESS not in", values, "address");
			return this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return this;
		}

		public Criteria andTelephoneIsNull() {
			addCriterion("TELEPHONE is null");
			return this;
		}

		public Criteria andTelephoneIsNotNull() {
			addCriterion("TELEPHONE is not null");
			return this;
		}

		public Criteria andTelephoneEqualTo(String value) {
			addCriterion("TELEPHONE =", value, "telephone");
			return this;
		}

		public Criteria andTelephoneNotEqualTo(String value) {
			addCriterion("TELEPHONE <>", value, "telephone");
			return this;
		}

		public Criteria andTelephoneGreaterThan(String value) {
			addCriterion("TELEPHONE >", value, "telephone");
			return this;
		}

		public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("TELEPHONE >=", value, "telephone");
			return this;
		}

		public Criteria andTelephoneLessThan(String value) {
			addCriterion("TELEPHONE <", value, "telephone");
			return this;
		}

		public Criteria andTelephoneLessThanOrEqualTo(String value) {
			addCriterion("TELEPHONE <=", value, "telephone");
			return this;
		}

		public Criteria andTelephoneLike(String value) {
			addCriterion("TELEPHONE like", value, "telephone");
			return this;
		}

		public Criteria andTelephoneNotLike(String value) {
			addCriterion("TELEPHONE not like", value, "telephone");
			return this;
		}

		public Criteria andTelephoneIn(List values) {
			addCriterion("TELEPHONE in", values, "telephone");
			return this;
		}

		public Criteria andTelephoneNotIn(List values) {
			addCriterion("TELEPHONE not in", values, "telephone");
			return this;
		}

		public Criteria andTelephoneBetween(String value1, String value2) {
			addCriterion("TELEPHONE between", value1, value2, "telephone");
			return this;
		}

		public Criteria andTelephoneNotBetween(String value1, String value2) {
			addCriterion("TELEPHONE not between", value1, value2, "telephone");
			return this;
		}

		public Criteria andMobilIsNull() {
			addCriterion("MOBIL is null");
			return this;
		}

		public Criteria andMobilIsNotNull() {
			addCriterion("MOBIL is not null");
			return this;
		}

		public Criteria andMobilEqualTo(String value) {
			addCriterion("MOBIL =", value, "mobil");
			return this;
		}

		public Criteria andMobilNotEqualTo(String value) {
			addCriterion("MOBIL <>", value, "mobil");
			return this;
		}

		public Criteria andMobilGreaterThan(String value) {
			addCriterion("MOBIL >", value, "mobil");
			return this;
		}

		public Criteria andMobilGreaterThanOrEqualTo(String value) {
			addCriterion("MOBIL >=", value, "mobil");
			return this;
		}

		public Criteria andMobilLessThan(String value) {
			addCriterion("MOBIL <", value, "mobil");
			return this;
		}

		public Criteria andMobilLessThanOrEqualTo(String value) {
			addCriterion("MOBIL <=", value, "mobil");
			return this;
		}

		public Criteria andMobilLike(String value) {
			addCriterion("MOBIL like", value, "mobil");
			return this;
		}

		public Criteria andMobilNotLike(String value) {
			addCriterion("MOBIL not like", value, "mobil");
			return this;
		}

		public Criteria andMobilIn(List values) {
			addCriterion("MOBIL in", values, "mobil");
			return this;
		}

		public Criteria andMobilNotIn(List values) {
			addCriterion("MOBIL not in", values, "mobil");
			return this;
		}

		public Criteria andMobilBetween(String value1, String value2) {
			addCriterion("MOBIL between", value1, value2, "mobil");
			return this;
		}

		public Criteria andMobilNotBetween(String value1, String value2) {
			addCriterion("MOBIL not between", value1, value2, "mobil");
			return this;
		}

		public Criteria andLinkEmailIsNull() {
			addCriterion("LINK_EMAIL is null");
			return this;
		}

		public Criteria andLinkEmailIsNotNull() {
			addCriterion("LINK_EMAIL is not null");
			return this;
		}

		public Criteria andLinkEmailEqualTo(String value) {
			addCriterion("LINK_EMAIL =", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailNotEqualTo(String value) {
			addCriterion("LINK_EMAIL <>", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailGreaterThan(String value) {
			addCriterion("LINK_EMAIL >", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailGreaterThanOrEqualTo(String value) {
			addCriterion("LINK_EMAIL >=", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailLessThan(String value) {
			addCriterion("LINK_EMAIL <", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailLessThanOrEqualTo(String value) {
			addCriterion("LINK_EMAIL <=", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailLike(String value) {
			addCriterion("LINK_EMAIL like", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailNotLike(String value) {
			addCriterion("LINK_EMAIL not like", value, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailIn(List values) {
			addCriterion("LINK_EMAIL in", values, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailNotIn(List values) {
			addCriterion("LINK_EMAIL not in", values, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailBetween(String value1, String value2) {
			addCriterion("LINK_EMAIL between", value1, value2, "linkEmail");
			return this;
		}

		public Criteria andLinkEmailNotBetween(String value1, String value2) {
			addCriterion("LINK_EMAIL not between", value1, value2, "linkEmail");
			return this;
		}

		public Criteria andMacAddressIsNull() {
			addCriterion("MAC_ADDRESS is null");
			return this;
		}

		public Criteria andMacAddressIsNotNull() {
			addCriterion("MAC_ADDRESS is not null");
			return this;
		}

		public Criteria andMacAddressEqualTo(String value) {
			addCriterion("MAC_ADDRESS =", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressNotEqualTo(String value) {
			addCriterion("MAC_ADDRESS <>", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressGreaterThan(String value) {
			addCriterion("MAC_ADDRESS >", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressGreaterThanOrEqualTo(String value) {
			addCriterion("MAC_ADDRESS >=", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressLessThan(String value) {
			addCriterion("MAC_ADDRESS <", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressLessThanOrEqualTo(String value) {
			addCriterion("MAC_ADDRESS <=", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressLike(String value) {
			addCriterion("MAC_ADDRESS like", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressNotLike(String value) {
			addCriterion("MAC_ADDRESS not like", value, "macAddress");
			return this;
		}

		public Criteria andMacAddressIn(List values) {
			addCriterion("MAC_ADDRESS in", values, "macAddress");
			return this;
		}

		public Criteria andMacAddressNotIn(List values) {
			addCriterion("MAC_ADDRESS not in", values, "macAddress");
			return this;
		}

		public Criteria andMacAddressBetween(String value1, String value2) {
			addCriterion("MAC_ADDRESS between", value1, value2, "macAddress");
			return this;
		}

		public Criteria andMacAddressNotBetween(String value1, String value2) {
			addCriterion("MAC_ADDRESS not between", value1, value2,
					"macAddress");
			return this;
		}

		public Criteria andLastLoginTimeIsNull() {
			addCriterion("LAST_LOGIN_TIME is null");
			return this;
		}

		public Criteria andLastLoginTimeIsNotNull() {
			addCriterion("LAST_LOGIN_TIME is not null");
			return this;
		}

		public Criteria andLastLoginTimeEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME =", value, "lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME <>", value,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME >", value, "lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME >=", value,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeLessThan(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME <", value, "lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME <=", value,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeIn(List values) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME in", values,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeNotIn(List values) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME not in", values,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME between", value1, value2,
					"lastLoginTime");
			return this;
		}

		public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_LOGIN_TIME not between", value1,
					value2, "lastLoginTime");
			return this;
		}

		public Criteria andLastLoginIpIsNull() {
			addCriterion("LAST_LOGIN_IP is null");
			return this;
		}

		public Criteria andLastLoginIpIsNotNull() {
			addCriterion("LAST_LOGIN_IP is not null");
			return this;
		}

		public Criteria andLastLoginIpEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_IP =", value, "lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpNotEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_IP <>", value, "lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpGreaterThan(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_IP >", value, "lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_IP >=", value, "lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpLessThan(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_IP <", value, "lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("LAST_LOGIN_IP <=", value, "lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpIn(List values) {
			addCriterionForJDBCDate("LAST_LOGIN_IP in", values, "lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpNotIn(List values) {
			addCriterionForJDBCDate("LAST_LOGIN_IP not in", values,
					"lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_LOGIN_IP between", value1, value2,
					"lastLoginIp");
			return this;
		}

		public Criteria andLastLoginIpNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("LAST_LOGIN_IP not between", value1,
					value2, "lastLoginIp");
			return this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("ROLE_ID is null");
			return this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("ROLE_ID is not null");
			return this;
		}

		public Criteria andRoleIdEqualTo(Long value) {
			addCriterion("ROLE_ID =", value, "roleId");
			return this;
		}

		public Criteria andRoleIdNotEqualTo(Long value) {
			addCriterion("ROLE_ID <>", value, "roleId");
			return this;
		}

		public Criteria andRoleIdGreaterThan(Long value) {
			addCriterion("ROLE_ID >", value, "roleId");
			return this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ROLE_ID >=", value, "roleId");
			return this;
		}

		public Criteria andRoleIdLessThan(Long value) {
			addCriterion("ROLE_ID <", value, "roleId");
			return this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("ROLE_ID <=", value, "roleId");
			return this;
		}

		public Criteria andRoleIdIn(List values) {
			addCriterion("ROLE_ID in", values, "roleId");
			return this;
		}

		public Criteria andRoleIdNotIn(List values) {
			addCriterion("ROLE_ID not in", values, "roleId");
			return this;
		}

		public Criteria andRoleIdBetween(Long value1, Long value2) {
			addCriterion("ROLE_ID between", value1, value2, "roleId");
			return this;
		}

		public Criteria andRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("ROLE_ID not between", value1, value2, "roleId");
			return this;
		}

		public Criteria andIsOnlineIsNull() {
			addCriterion("IS_ONLINE is null");
			return this;
		}

		public Criteria andIsOnlineIsNotNull() {
			addCriterion("IS_ONLINE is not null");
			return this;
		}

		public Criteria andIsOnlineEqualTo(Short value) {
			addCriterion("IS_ONLINE =", value, "isOnline");
			return this;
		}

		public Criteria andIsOnlineNotEqualTo(Short value) {
			addCriterion("IS_ONLINE <>", value, "isOnline");
			return this;
		}

		public Criteria andIsOnlineGreaterThan(Short value) {
			addCriterion("IS_ONLINE >", value, "isOnline");
			return this;
		}

		public Criteria andIsOnlineGreaterThanOrEqualTo(Short value) {
			addCriterion("IS_ONLINE >=", value, "isOnline");
			return this;
		}

		public Criteria andIsOnlineLessThan(Short value) {
			addCriterion("IS_ONLINE <", value, "isOnline");
			return this;
		}

		public Criteria andIsOnlineLessThanOrEqualTo(Short value) {
			addCriterion("IS_ONLINE <=", value, "isOnline");
			return this;
		}

		public Criteria andIsOnlineIn(List values) {
			addCriterion("IS_ONLINE in", values, "isOnline");
			return this;
		}

		public Criteria andIsOnlineNotIn(List values) {
			addCriterion("IS_ONLINE not in", values, "isOnline");
			return this;
		}

		public Criteria andIsOnlineBetween(Short value1, Short value2) {
			addCriterion("IS_ONLINE between", value1, value2, "isOnline");
			return this;
		}

		public Criteria andIsOnlineNotBetween(Short value1, Short value2) {
			addCriterion("IS_ONLINE not between", value1, value2, "isOnline");
			return this;
		}

		public Criteria andLoginTypeIsNull() {
			addCriterion("LOGIN_TYPE is null");
			return this;
		}

		public Criteria andLoginTypeIsNotNull() {
			addCriterion("LOGIN_TYPE is not null");
			return this;
		}

		public Criteria andLoginTypeEqualTo(Short value) {
			addCriterion("LOGIN_TYPE =", value, "loginType");
			return this;
		}

		public Criteria andLoginTypeNotEqualTo(Short value) {
			addCriterion("LOGIN_TYPE <>", value, "loginType");
			return this;
		}

		public Criteria andLoginTypeGreaterThan(Short value) {
			addCriterion("LOGIN_TYPE >", value, "loginType");
			return this;
		}

		public Criteria andLoginTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("LOGIN_TYPE >=", value, "loginType");
			return this;
		}

		public Criteria andLoginTypeLessThan(Short value) {
			addCriterion("LOGIN_TYPE <", value, "loginType");
			return this;
		}

		public Criteria andLoginTypeLessThanOrEqualTo(Short value) {
			addCriterion("LOGIN_TYPE <=", value, "loginType");
			return this;
		}

		public Criteria andLoginTypeIn(List values) {
			addCriterion("LOGIN_TYPE in", values, "loginType");
			return this;
		}

		public Criteria andLoginTypeNotIn(List values) {
			addCriterion("LOGIN_TYPE not in", values, "loginType");
			return this;
		}

		public Criteria andLoginTypeBetween(Short value1, Short value2) {
			addCriterion("LOGIN_TYPE between", value1, value2, "loginType");
			return this;
		}

		public Criteria andLoginTypeNotBetween(Short value1, Short value2) {
			addCriterion("LOGIN_TYPE not between", value1, value2, "loginType");
			return this;
		}

		public Criteria andPymIsNull() {
			addCriterion("PYM is null");
			return this;
		}

		public Criteria andPymIsNotNull() {
			addCriterion("PYM is not null");
			return this;
		}

		public Criteria andPymEqualTo(String value) {
			addCriterion("PYM =", value, "pym");
			return this;
		}

		public Criteria andPymNotEqualTo(String value) {
			addCriterion("PYM <>", value, "pym");
			return this;
		}

		public Criteria andPymGreaterThan(String value) {
			addCriterion("PYM >", value, "pym");
			return this;
		}

		public Criteria andPymGreaterThanOrEqualTo(String value) {
			addCriterion("PYM >=", value, "pym");
			return this;
		}

		public Criteria andPymLessThan(String value) {
			addCriterion("PYM <", value, "pym");
			return this;
		}

		public Criteria andPymLessThanOrEqualTo(String value) {
			addCriterion("PYM <=", value, "pym");
			return this;
		}

		public Criteria andPymLike(String value) {
			addCriterion("PYM like", value, "pym");
			return this;
		}

		public Criteria andPymNotLike(String value) {
			addCriterion("PYM not like", value, "pym");
			return this;
		}

		public Criteria andPymIn(List values) {
			addCriterion("PYM in", values, "pym");
			return this;
		}

		public Criteria andPymNotIn(List values) {
			addCriterion("PYM not in", values, "pym");
			return this;
		}

		public Criteria andPymBetween(String value1, String value2) {
			addCriterion("PYM between", value1, value2, "pym");
			return this;
		}

		public Criteria andPymNotBetween(String value1, String value2) {
			addCriterion("PYM not between", value1, value2, "pym");
			return this;
		}

		public Criteria andPhotoIsNull() {
			addCriterion("PHOTO is null");
			return this;
		}

		public Criteria andPhotoIsNotNull() {
			addCriterion("PHOTO is not null");
			return this;
		}

		public Criteria andPhotoEqualTo(String value) {
			addCriterion("PHOTO =", value, "photo");
			return this;
		}

		public Criteria andPhotoNotEqualTo(String value) {
			addCriterion("PHOTO <>", value, "photo");
			return this;
		}

		public Criteria andPhotoGreaterThan(String value) {
			addCriterion("PHOTO >", value, "photo");
			return this;
		}

		public Criteria andPhotoGreaterThanOrEqualTo(String value) {
			addCriterion("PHOTO >=", value, "photo");
			return this;
		}

		public Criteria andPhotoLessThan(String value) {
			addCriterion("PHOTO <", value, "photo");
			return this;
		}

		public Criteria andPhotoLessThanOrEqualTo(String value) {
			addCriterion("PHOTO <=", value, "photo");
			return this;
		}

		public Criteria andPhotoLike(String value) {
			addCriterion("PHOTO like", value, "photo");
			return this;
		}

		public Criteria andPhotoNotLike(String value) {
			addCriterion("PHOTO not like", value, "photo");
			return this;
		}

		public Criteria andPhotoIn(List values) {
			addCriterion("PHOTO in", values, "photo");
			return this;
		}

		public Criteria andPhotoNotIn(List values) {
			addCriterion("PHOTO not in", values, "photo");
			return this;
		}

		public Criteria andPhotoBetween(String value1, String value2) {
			addCriterion("PHOTO between", value1, value2, "photo");
			return this;
		}

		public Criteria andPhotoNotBetween(String value1, String value2) {
			addCriterion("PHOTO not between", value1, value2, "photo");
			return this;
		}

		public Criteria andGwhIsNull() {
			addCriterion("GWH is null");
			return this;
		}

		public Criteria andGwhIsNotNull() {
			addCriterion("GWH is not null");
			return this;
		}

		public Criteria andGwhEqualTo(String value) {
			addCriterion("GWH =", value, "gwh");
			return this;
		}

		public Criteria andGwhNotEqualTo(String value) {
			addCriterion("GWH <>", value, "gwh");
			return this;
		}

		public Criteria andGwhGreaterThan(String value) {
			addCriterion("GWH >", value, "gwh");
			return this;
		}

		public Criteria andGwhGreaterThanOrEqualTo(String value) {
			addCriterion("GWH >=", value, "gwh");
			return this;
		}

		public Criteria andGwhLessThan(String value) {
			addCriterion("GWH <", value, "gwh");
			return this;
		}

		public Criteria andGwhLessThanOrEqualTo(String value) {
			addCriterion("GWH <=", value, "gwh");
			return this;
		}

		public Criteria andGwhLike(String value) {
			addCriterion("GWH like", value, "gwh");
			return this;
		}

		public Criteria andGwhNotLike(String value) {
			addCriterion("GWH not like", value, "gwh");
			return this;
		}

		public Criteria andGwhIn(List values) {
			addCriterion("GWH in", values, "gwh");
			return this;
		}

		public Criteria andGwhNotIn(List values) {
			addCriterion("GWH not in", values, "gwh");
			return this;
		}

		public Criteria andGwhBetween(String value1, String value2) {
			addCriterion("GWH between", value1, value2, "gwh");
			return this;
		}

		public Criteria andGwhNotBetween(String value1, String value2) {
			addCriterion("GWH not between", value1, value2, "gwh");
			return this;
		}

		public Criteria andF1IsNull() {
			addCriterion("F1 is null");
			return this;
		}

		public Criteria andF1IsNotNull() {
			addCriterion("F1 is not null");
			return this;
		}

		public Criteria andF1EqualTo(String value) {
			addCriterion("F1 =", value, "f1");
			return this;
		}

		public Criteria andF1NotEqualTo(String value) {
			addCriterion("F1 <>", value, "f1");
			return this;
		}

		public Criteria andF1GreaterThan(String value) {
			addCriterion("F1 >", value, "f1");
			return this;
		}

		public Criteria andF1GreaterThanOrEqualTo(String value) {
			addCriterion("F1 >=", value, "f1");
			return this;
		}

		public Criteria andF1LessThan(String value) {
			addCriterion("F1 <", value, "f1");
			return this;
		}

		public Criteria andF1LessThanOrEqualTo(String value) {
			addCriterion("F1 <=", value, "f1");
			return this;
		}

		public Criteria andF1Like(String value) {
			addCriterion("F1 like", value, "f1");
			return this;
		}

		public Criteria andF1NotLike(String value) {
			addCriterion("F1 not like", value, "f1");
			return this;
		}

		public Criteria andF1In(List values) {
			addCriterion("F1 in", values, "f1");
			return this;
		}

		public Criteria andF1NotIn(List values) {
			addCriterion("F1 not in", values, "f1");
			return this;
		}

		public Criteria andF1Between(String value1, String value2) {
			addCriterion("F1 between", value1, value2, "f1");
			return this;
		}

		public Criteria andF1NotBetween(String value1, String value2) {
			addCriterion("F1 not between", value1, value2, "f1");
			return this;
		}

		public Criteria andF2IsNull() {
			addCriterion("F2 is null");
			return this;
		}

		public Criteria andF2IsNotNull() {
			addCriterion("F2 is not null");
			return this;
		}

		public Criteria andF2EqualTo(String value) {
			addCriterion("F2 =", value, "f2");
			return this;
		}

		public Criteria andF2NotEqualTo(String value) {
			addCriterion("F2 <>", value, "f2");
			return this;
		}

		public Criteria andF2GreaterThan(String value) {
			addCriterion("F2 >", value, "f2");
			return this;
		}

		public Criteria andF2GreaterThanOrEqualTo(String value) {
			addCriterion("F2 >=", value, "f2");
			return this;
		}

		public Criteria andF2LessThan(String value) {
			addCriterion("F2 <", value, "f2");
			return this;
		}

		public Criteria andF2LessThanOrEqualTo(String value) {
			addCriterion("F2 <=", value, "f2");
			return this;
		}

		public Criteria andF2Like(String value) {
			addCriterion("F2 like", value, "f2");
			return this;
		}

		public Criteria andF2NotLike(String value) {
			addCriterion("F2 not like", value, "f2");
			return this;
		}

		public Criteria andF2In(List values) {
			addCriterion("F2 in", values, "f2");
			return this;
		}

		public Criteria andF2NotIn(List values) {
			addCriterion("F2 not in", values, "f2");
			return this;
		}

		public Criteria andF2Between(String value1, String value2) {
			addCriterion("F2 between", value1, value2, "f2");
			return this;
		}

		public Criteria andF2NotBetween(String value1, String value2) {
			addCriterion("F2 not between", value1, value2, "f2");
			return this;
		}

		public Criteria andF3IsNull() {
			addCriterion("F3 is null");
			return this;
		}

		public Criteria andF3IsNotNull() {
			addCriterion("F3 is not null");
			return this;
		}

		public Criteria andF3EqualTo(String value) {
			addCriterion("F3 =", value, "f3");
			return this;
		}

		public Criteria andF3NotEqualTo(String value) {
			addCriterion("F3 <>", value, "f3");
			return this;
		}

		public Criteria andF3GreaterThan(String value) {
			addCriterion("F3 >", value, "f3");
			return this;
		}

		public Criteria andF3GreaterThanOrEqualTo(String value) {
			addCriterion("F3 >=", value, "f3");
			return this;
		}

		public Criteria andF3LessThan(String value) {
			addCriterion("F3 <", value, "f3");
			return this;
		}

		public Criteria andF3LessThanOrEqualTo(String value) {
			addCriterion("F3 <=", value, "f3");
			return this;
		}

		public Criteria andF3Like(String value) {
			addCriterion("F3 like", value, "f3");
			return this;
		}

		public Criteria andF3NotLike(String value) {
			addCriterion("F3 not like", value, "f3");
			return this;
		}

		public Criteria andF3In(List values) {
			addCriterion("F3 in", values, "f3");
			return this;
		}

		public Criteria andF3NotIn(List values) {
			addCriterion("F3 not in", values, "f3");
			return this;
		}

		public Criteria andF3Between(String value1, String value2) {
			addCriterion("F3 between", value1, value2, "f3");
			return this;
		}

		public Criteria andF3NotBetween(String value1, String value2) {
			addCriterion("F3 not between", value1, value2, "f3");
			return this;
		}

		public Criteria andF4IsNull() {
			addCriterion("F4 is null");
			return this;
		}

		public Criteria andF4IsNotNull() {
			addCriterion("F4 is not null");
			return this;
		}

		public Criteria andF4EqualTo(String value) {
			addCriterion("F4 =", value, "f4");
			return this;
		}

		public Criteria andF4NotEqualTo(String value) {
			addCriterion("F4 <>", value, "f4");
			return this;
		}

		public Criteria andF4GreaterThan(String value) {
			addCriterion("F4 >", value, "f4");
			return this;
		}

		public Criteria andF4GreaterThanOrEqualTo(String value) {
			addCriterion("F4 >=", value, "f4");
			return this;
		}

		public Criteria andF4LessThan(String value) {
			addCriterion("F4 <", value, "f4");
			return this;
		}

		public Criteria andF4LessThanOrEqualTo(String value) {
			addCriterion("F4 <=", value, "f4");
			return this;
		}

		public Criteria andF4Like(String value) {
			addCriterion("F4 like", value, "f4");
			return this;
		}

		public Criteria andF4NotLike(String value) {
			addCriterion("F4 not like", value, "f4");
			return this;
		}

		public Criteria andF4In(List values) {
			addCriterion("F4 in", values, "f4");
			return this;
		}

		public Criteria andF4NotIn(List values) {
			addCriterion("F4 not in", values, "f4");
			return this;
		}

		public Criteria andF4Between(String value1, String value2) {
			addCriterion("F4 between", value1, value2, "f4");
			return this;
		}

		public Criteria andF4NotBetween(String value1, String value2) {
			addCriterion("F4 not between", value1, value2, "f4");
			return this;
		}

		public Criteria andF5IsNull() {
			addCriterion("F5 is null");
			return this;
		}

		public Criteria andF5IsNotNull() {
			addCriterion("F5 is not null");
			return this;
		}

		public Criteria andF5EqualTo(String value) {
			addCriterion("F5 =", value, "f5");
			return this;
		}

		public Criteria andF5NotEqualTo(String value) {
			addCriterion("F5 <>", value, "f5");
			return this;
		}

		public Criteria andF5GreaterThan(String value) {
			addCriterion("F5 >", value, "f5");
			return this;
		}

		public Criteria andF5GreaterThanOrEqualTo(String value) {
			addCriterion("F5 >=", value, "f5");
			return this;
		}

		public Criteria andF5LessThan(String value) {
			addCriterion("F5 <", value, "f5");
			return this;
		}

		public Criteria andF5LessThanOrEqualTo(String value) {
			addCriterion("F5 <=", value, "f5");
			return this;
		}

		public Criteria andF5Like(String value) {
			addCriterion("F5 like", value, "f5");
			return this;
		}

		public Criteria andF5NotLike(String value) {
			addCriterion("F5 not like", value, "f5");
			return this;
		}

		public Criteria andF5In(List values) {
			addCriterion("F5 in", values, "f5");
			return this;
		}

		public Criteria andF5NotIn(List values) {
			addCriterion("F5 not in", values, "f5");
			return this;
		}

		public Criteria andF5Between(String value1, String value2) {
			addCriterion("F5 between", value1, value2, "f5");
			return this;
		}

		public Criteria andF5NotBetween(String value1, String value2) {
			addCriterion("F5 not between", value1, value2, "f5");
			return this;
		}

		public Criteria andJybhIsNull() {
			addCriterion("JYBH is null");
			return this;
		}

		public Criteria andJybhIsNotNull() {
			addCriterion("JYBH is not null");
			return this;
		}

		public Criteria andJybhEqualTo(String value) {
			addCriterion("JYBH =", value, "jybh");
			return this;
		}

		public Criteria andJybhNotEqualTo(String value) {
			addCriterion("JYBH <>", value, "jybh");
			return this;
		}

		public Criteria andJybhGreaterThan(String value) {
			addCriterion("JYBH >", value, "jybh");
			return this;
		}

		public Criteria andJybhGreaterThanOrEqualTo(String value) {
			addCriterion("JYBH >=", value, "jybh");
			return this;
		}

		public Criteria andJybhLessThan(String value) {
			addCriterion("JYBH <", value, "jybh");
			return this;
		}

		public Criteria andJybhLessThanOrEqualTo(String value) {
			addCriterion("JYBH <=", value, "jybh");
			return this;
		}

		public Criteria andJybhLike(String value) {
			addCriterion("JYBH like", value, "jybh");
			return this;
		}

		public Criteria andJybhNotLike(String value) {
			addCriterion("JYBH not like", value, "jybh");
			return this;
		}

		public Criteria andJybhIn(List values) {
			addCriterion("JYBH in", values, "jybh");
			return this;
		}

		public Criteria andJybhNotIn(List values) {
			addCriterion("JYBH not in", values, "jybh");
			return this;
		}

		public Criteria andJybhBetween(String value1, String value2) {
			addCriterion("JYBH between", value1, value2, "jybh");
			return this;
		}

		public Criteria andJybhNotBetween(String value1, String value2) {
			addCriterion("JYBH not between", value1, value2, "jybh");
			return this;
		}
	}
}