package com.pd.right.model;

import java.math.BigDecimal;
import java.util.Date;

public class Users {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.USER_CODE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String userCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.USER_NAME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String userName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.NICK_NAME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String nickName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.PASSWORD
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String password;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.USER_GENDER
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Short userGender;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.BORN_DATE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Date bornDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.CREATE_DATE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Date createDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.USERSTAT
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Short userstat;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.CARID
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String carid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.SIGN_TYPE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private BigDecimal signType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.DEPT_CODE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String deptCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.ADDRESS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String address;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.TELEPHONE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String telephone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.MOBIL
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String mobil;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.LINK_EMAIL
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String linkEmail;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.MAC_ADDRESS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String macAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.LAST_LOGIN_TIME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.LAST_LOGIN_IP
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Date lastLoginIp;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.ROLE_ID
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Long roleId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.IS_ONLINE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Short isOnline;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.LOGIN_TYPE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private Short loginType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.PYM
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String pym;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.PHOTO
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String photo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.GWH
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String gwh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.F1
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String f1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.F2
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String f2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.F3
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String f3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.F4
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String f4;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.F5
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String f5;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column USERS.JYBH
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private String jybh;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.USER_CODE
	 * @return  the value of USERS.USER_CODE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.USER_CODE
	 * @param userCode  the value for USERS.USER_CODE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.USER_NAME
	 * @return  the value of USERS.USER_NAME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.USER_NAME
	 * @param userName  the value for USERS.USER_NAME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.NICK_NAME
	 * @return  the value of USERS.NICK_NAME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.NICK_NAME
	 * @param nickName  the value for USERS.NICK_NAME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.PASSWORD
	 * @return  the value of USERS.PASSWORD
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.PASSWORD
	 * @param password  the value for USERS.PASSWORD
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.USER_GENDER
	 * @return  the value of USERS.USER_GENDER
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Short getUserGender() {
		return userGender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.USER_GENDER
	 * @param userGender  the value for USERS.USER_GENDER
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setUserGender(Short userGender) {
		this.userGender = userGender;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.BORN_DATE
	 * @return  the value of USERS.BORN_DATE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Date getBornDate() {
		return bornDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.BORN_DATE
	 * @param bornDate  the value for USERS.BORN_DATE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setBornDate(Date bornDate) {
		this.bornDate = bornDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.CREATE_DATE
	 * @return  the value of USERS.CREATE_DATE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.CREATE_DATE
	 * @param createDate  the value for USERS.CREATE_DATE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.USERSTAT
	 * @return  the value of USERS.USERSTAT
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Short getUserstat() {
		return userstat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.USERSTAT
	 * @param userstat  the value for USERS.USERSTAT
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setUserstat(Short userstat) {
		this.userstat = userstat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.CARID
	 * @return  the value of USERS.CARID
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getCarid() {
		return carid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.CARID
	 * @param carid  the value for USERS.CARID
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setCarid(String carid) {
		this.carid = carid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.SIGN_TYPE
	 * @return  the value of USERS.SIGN_TYPE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public BigDecimal getSignType() {
		return signType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.SIGN_TYPE
	 * @param signType  the value for USERS.SIGN_TYPE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setSignType(BigDecimal signType) {
		this.signType = signType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.DEPT_CODE
	 * @return  the value of USERS.DEPT_CODE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getDeptCode() {
		return deptCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.DEPT_CODE
	 * @param deptCode  the value for USERS.DEPT_CODE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.ADDRESS
	 * @return  the value of USERS.ADDRESS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.ADDRESS
	 * @param address  the value for USERS.ADDRESS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.TELEPHONE
	 * @return  the value of USERS.TELEPHONE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.TELEPHONE
	 * @param telephone  the value for USERS.TELEPHONE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.MOBIL
	 * @return  the value of USERS.MOBIL
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getMobil() {
		return mobil;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.MOBIL
	 * @param mobil  the value for USERS.MOBIL
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setMobil(String mobil) {
		this.mobil = mobil;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.LINK_EMAIL
	 * @return  the value of USERS.LINK_EMAIL
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getLinkEmail() {
		return linkEmail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.LINK_EMAIL
	 * @param linkEmail  the value for USERS.LINK_EMAIL
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setLinkEmail(String linkEmail) {
		this.linkEmail = linkEmail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.MAC_ADDRESS
	 * @return  the value of USERS.MAC_ADDRESS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getMacAddress() {
		return macAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.MAC_ADDRESS
	 * @param macAddress  the value for USERS.MAC_ADDRESS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.LAST_LOGIN_TIME
	 * @return  the value of USERS.LAST_LOGIN_TIME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.LAST_LOGIN_TIME
	 * @param lastLoginTime  the value for USERS.LAST_LOGIN_TIME
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.LAST_LOGIN_IP
	 * @return  the value of USERS.LAST_LOGIN_IP
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Date getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.LAST_LOGIN_IP
	 * @param lastLoginIp  the value for USERS.LAST_LOGIN_IP
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setLastLoginIp(Date lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.ROLE_ID
	 * @return  the value of USERS.ROLE_ID
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.ROLE_ID
	 * @param roleId  the value for USERS.ROLE_ID
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.IS_ONLINE
	 * @return  the value of USERS.IS_ONLINE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Short getIsOnline() {
		return isOnline;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.IS_ONLINE
	 * @param isOnline  the value for USERS.IS_ONLINE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setIsOnline(Short isOnline) {
		this.isOnline = isOnline;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.LOGIN_TYPE
	 * @return  the value of USERS.LOGIN_TYPE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Short getLoginType() {
		return loginType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.LOGIN_TYPE
	 * @param loginType  the value for USERS.LOGIN_TYPE
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setLoginType(Short loginType) {
		this.loginType = loginType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.PYM
	 * @return  the value of USERS.PYM
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getPym() {
		return pym;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.PYM
	 * @param pym  the value for USERS.PYM
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setPym(String pym) {
		this.pym = pym;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.PHOTO
	 * @return  the value of USERS.PHOTO
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.PHOTO
	 * @param photo  the value for USERS.PHOTO
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.GWH
	 * @return  the value of USERS.GWH
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getGwh() {
		return gwh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.GWH
	 * @param gwh  the value for USERS.GWH
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setGwh(String gwh) {
		this.gwh = gwh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.F1
	 * @return  the value of USERS.F1
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getF1() {
		return f1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.F1
	 * @param f1  the value for USERS.F1
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setF1(String f1) {
		this.f1 = f1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.F2
	 * @return  the value of USERS.F2
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getF2() {
		return f2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.F2
	 * @param f2  the value for USERS.F2
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setF2(String f2) {
		this.f2 = f2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.F3
	 * @return  the value of USERS.F3
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getF3() {
		return f3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.F3
	 * @param f3  the value for USERS.F3
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setF3(String f3) {
		this.f3 = f3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.F4
	 * @return  the value of USERS.F4
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getF4() {
		return f4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.F4
	 * @param f4  the value for USERS.F4
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setF4(String f4) {
		this.f4 = f4;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.F5
	 * @return  the value of USERS.F5
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getF5() {
		return f5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.F5
	 * @param f5  the value for USERS.F5
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setF5(String f5) {
		this.f5 = f5;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column USERS.JYBH
	 * @return  the value of USERS.JYBH
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public String getJybh() {
		return jybh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column USERS.JYBH
	 * @param jybh  the value for USERS.JYBH
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void setJybh(String jybh) {
		this.jybh = jybh;
	}
}