package com.pd.right.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.pd.system.framework.PageToExample;

public class RoleExample extends PageToExample{

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public RoleExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	protected RoleExample(RoleExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table ROLE
	 * @abatorgenerated  Mon Jun 24 13:28:44 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andRoleidIsNull() {
			addCriterion("ROLEID is null");
			return this;
		}

		public Criteria andRoleidIsNotNull() {
			addCriterion("ROLEID is not null");
			return this;
		}

		public Criteria andRoleidEqualTo(Long value) {
			addCriterion("ROLEID =", value, "roleid");
			return this;
		}

		public Criteria andRoleidNotEqualTo(Long value) {
			addCriterion("ROLEID <>", value, "roleid");
			return this;
		}

		public Criteria andRoleidGreaterThan(Long value) {
			addCriterion("ROLEID >", value, "roleid");
			return this;
		}

		public Criteria andRoleidGreaterThanOrEqualTo(Long value) {
			addCriterion("ROLEID >=", value, "roleid");
			return this;
		}

		public Criteria andRoleidLessThan(Long value) {
			addCriterion("ROLEID <", value, "roleid");
			return this;
		}

		public Criteria andRoleidLessThanOrEqualTo(Long value) {
			addCriterion("ROLEID <=", value, "roleid");
			return this;
		}

		public Criteria andRoleidIn(List values) {
			addCriterion("ROLEID in", values, "roleid");
			return this;
		}

		public Criteria andRoleidNotIn(List values) {
			addCriterion("ROLEID not in", values, "roleid");
			return this;
		}

		public Criteria andRoleidBetween(Long value1, Long value2) {
			addCriterion("ROLEID between", value1, value2, "roleid");
			return this;
		}

		public Criteria andRoleidNotBetween(Long value1, Long value2) {
			addCriterion("ROLEID not between", value1, value2, "roleid");
			return this;
		}

		public Criteria andRolenameIsNull() {
			addCriterion("ROLENAME is null");
			return this;
		}

		public Criteria andRolenameIsNotNull() {
			addCriterion("ROLENAME is not null");
			return this;
		}

		public Criteria andRolenameEqualTo(String value) {
			addCriterion("ROLENAME =", value, "rolename");
			return this;
		}

		public Criteria andRolenameNotEqualTo(String value) {
			addCriterion("ROLENAME <>", value, "rolename");
			return this;
		}

		public Criteria andRolenameGreaterThan(String value) {
			addCriterion("ROLENAME >", value, "rolename");
			return this;
		}

		public Criteria andRolenameGreaterThanOrEqualTo(String value) {
			addCriterion("ROLENAME >=", value, "rolename");
			return this;
		}

		public Criteria andRolenameLessThan(String value) {
			addCriterion("ROLENAME <", value, "rolename");
			return this;
		}

		public Criteria andRolenameLessThanOrEqualTo(String value) {
			addCriterion("ROLENAME <=", value, "rolename");
			return this;
		}

		public Criteria andRolenameLike(String value) {
			addCriterion("ROLENAME like", value, "rolename");
			return this;
		}

		public Criteria andRolenameNotLike(String value) {
			addCriterion("ROLENAME not like", value, "rolename");
			return this;
		}

		public Criteria andRolenameIn(List values) {
			addCriterion("ROLENAME in", values, "rolename");
			return this;
		}

		public Criteria andRolenameNotIn(List values) {
			addCriterion("ROLENAME not in", values, "rolename");
			return this;
		}

		public Criteria andRolenameBetween(String value1, String value2) {
			addCriterion("ROLENAME between", value1, value2, "rolename");
			return this;
		}

		public Criteria andRolenameNotBetween(String value1, String value2) {
			addCriterion("ROLENAME not between", value1, value2, "rolename");
			return this;
		}

		public Criteria andRoletypeIsNull() {
			addCriterion("ROLETYPE is null");
			return this;
		}

		public Criteria andRoletypeIsNotNull() {
			addCriterion("ROLETYPE is not null");
			return this;
		}

		public Criteria andRoletypeEqualTo(Short value) {
			addCriterion("ROLETYPE =", value, "roletype");
			return this;
		}

		public Criteria andRoletypeNotEqualTo(Short value) {
			addCriterion("ROLETYPE <>", value, "roletype");
			return this;
		}

		public Criteria andRoletypeGreaterThan(Short value) {
			addCriterion("ROLETYPE >", value, "roletype");
			return this;
		}

		public Criteria andRoletypeGreaterThanOrEqualTo(Short value) {
			addCriterion("ROLETYPE >=", value, "roletype");
			return this;
		}

		public Criteria andRoletypeLessThan(Short value) {
			addCriterion("ROLETYPE <", value, "roletype");
			return this;
		}

		public Criteria andRoletypeLessThanOrEqualTo(Short value) {
			addCriterion("ROLETYPE <=", value, "roletype");
			return this;
		}

		public Criteria andRoletypeIn(List values) {
			addCriterion("ROLETYPE in", values, "roletype");
			return this;
		}

		public Criteria andRoletypeNotIn(List values) {
			addCriterion("ROLETYPE not in", values, "roletype");
			return this;
		}

		public Criteria andRoletypeBetween(Short value1, Short value2) {
			addCriterion("ROLETYPE between", value1, value2, "roletype");
			return this;
		}

		public Criteria andRoletypeNotBetween(Short value1, Short value2) {
			addCriterion("ROLETYPE not between", value1, value2, "roletype");
			return this;
		}

		public Criteria andRoledescIsNull() {
			addCriterion("ROLEDESC is null");
			return this;
		}

		public Criteria andRoledescIsNotNull() {
			addCriterion("ROLEDESC is not null");
			return this;
		}

		public Criteria andRoledescEqualTo(String value) {
			addCriterion("ROLEDESC =", value, "roledesc");
			return this;
		}

		public Criteria andRoledescNotEqualTo(String value) {
			addCriterion("ROLEDESC <>", value, "roledesc");
			return this;
		}

		public Criteria andRoledescGreaterThan(String value) {
			addCriterion("ROLEDESC >", value, "roledesc");
			return this;
		}

		public Criteria andRoledescGreaterThanOrEqualTo(String value) {
			addCriterion("ROLEDESC >=", value, "roledesc");
			return this;
		}

		public Criteria andRoledescLessThan(String value) {
			addCriterion("ROLEDESC <", value, "roledesc");
			return this;
		}

		public Criteria andRoledescLessThanOrEqualTo(String value) {
			addCriterion("ROLEDESC <=", value, "roledesc");
			return this;
		}

		public Criteria andRoledescLike(String value) {
			addCriterion("ROLEDESC like", value, "roledesc");
			return this;
		}

		public Criteria andRoledescNotLike(String value) {
			addCriterion("ROLEDESC not like", value, "roledesc");
			return this;
		}

		public Criteria andRoledescIn(List values) {
			addCriterion("ROLEDESC in", values, "roledesc");
			return this;
		}

		public Criteria andRoledescNotIn(List values) {
			addCriterion("ROLEDESC not in", values, "roledesc");
			return this;
		}

		public Criteria andRoledescBetween(String value1, String value2) {
			addCriterion("ROLEDESC between", value1, value2, "roledesc");
			return this;
		}

		public Criteria andRoledescNotBetween(String value1, String value2) {
			addCriterion("ROLEDESC not between", value1, value2, "roledesc");
			return this;
		}

		public Criteria andF1IsNull() {
			addCriterion("F1 is null");
			return this;
		}

		public Criteria andF1IsNotNull() {
			addCriterion("F1 is not null");
			return this;
		}

		public Criteria andF1EqualTo(String value) {
			addCriterion("F1 =", value, "f1");
			return this;
		}

		public Criteria andF1NotEqualTo(String value) {
			addCriterion("F1 <>", value, "f1");
			return this;
		}

		public Criteria andF1GreaterThan(String value) {
			addCriterion("F1 >", value, "f1");
			return this;
		}

		public Criteria andF1GreaterThanOrEqualTo(String value) {
			addCriterion("F1 >=", value, "f1");
			return this;
		}

		public Criteria andF1LessThan(String value) {
			addCriterion("F1 <", value, "f1");
			return this;
		}

		public Criteria andF1LessThanOrEqualTo(String value) {
			addCriterion("F1 <=", value, "f1");
			return this;
		}

		public Criteria andF1Like(String value) {
			addCriterion("F1 like", value, "f1");
			return this;
		}

		public Criteria andF1NotLike(String value) {
			addCriterion("F1 not like", value, "f1");
			return this;
		}

		public Criteria andF1In(List values) {
			addCriterion("F1 in", values, "f1");
			return this;
		}

		public Criteria andF1NotIn(List values) {
			addCriterion("F1 not in", values, "f1");
			return this;
		}

		public Criteria andF1Between(String value1, String value2) {
			addCriterion("F1 between", value1, value2, "f1");
			return this;
		}

		public Criteria andF1NotBetween(String value1, String value2) {
			addCriterion("F1 not between", value1, value2, "f1");
			return this;
		}

		public Criteria andF2IsNull() {
			addCriterion("F2 is null");
			return this;
		}

		public Criteria andF2IsNotNull() {
			addCriterion("F2 is not null");
			return this;
		}

		public Criteria andF2EqualTo(String value) {
			addCriterion("F2 =", value, "f2");
			return this;
		}

		public Criteria andF2NotEqualTo(String value) {
			addCriterion("F2 <>", value, "f2");
			return this;
		}

		public Criteria andF2GreaterThan(String value) {
			addCriterion("F2 >", value, "f2");
			return this;
		}

		public Criteria andF2GreaterThanOrEqualTo(String value) {
			addCriterion("F2 >=", value, "f2");
			return this;
		}

		public Criteria andF2LessThan(String value) {
			addCriterion("F2 <", value, "f2");
			return this;
		}

		public Criteria andF2LessThanOrEqualTo(String value) {
			addCriterion("F2 <=", value, "f2");
			return this;
		}

		public Criteria andF2Like(String value) {
			addCriterion("F2 like", value, "f2");
			return this;
		}

		public Criteria andF2NotLike(String value) {
			addCriterion("F2 not like", value, "f2");
			return this;
		}

		public Criteria andF2In(List values) {
			addCriterion("F2 in", values, "f2");
			return this;
		}

		public Criteria andF2NotIn(List values) {
			addCriterion("F2 not in", values, "f2");
			return this;
		}

		public Criteria andF2Between(String value1, String value2) {
			addCriterion("F2 between", value1, value2, "f2");
			return this;
		}

		public Criteria andF2NotBetween(String value1, String value2) {
			addCriterion("F2 not between", value1, value2, "f2");
			return this;
		}

		public Criteria andLevelIdIsNull() {
			addCriterion("LEVEL_ID is null");
			return this;
		}

		public Criteria andLevelIdIsNotNull() {
			addCriterion("LEVEL_ID is not null");
			return this;
		}

		public Criteria andLevelIdEqualTo(String value) {
			addCriterion("LEVEL_ID =", value, "levelId");
			return this;
		}

		public Criteria andLevelIdNotEqualTo(String value) {
			addCriterion("LEVEL_ID <>", value, "levelId");
			return this;
		}

		public Criteria andLevelIdGreaterThan(String value) {
			addCriterion("LEVEL_ID >", value, "levelId");
			return this;
		}

		public Criteria andLevelIdGreaterThanOrEqualTo(String value) {
			addCriterion("LEVEL_ID >=", value, "levelId");
			return this;
		}

		public Criteria andLevelIdLessThan(String value) {
			addCriterion("LEVEL_ID <", value, "levelId");
			return this;
		}

		public Criteria andLevelIdLessThanOrEqualTo(String value) {
			addCriterion("LEVEL_ID <=", value, "levelId");
			return this;
		}

		public Criteria andLevelIdLike(String value) {
			addCriterion("LEVEL_ID like", value, "levelId");
			return this;
		}

		public Criteria andLevelIdNotLike(String value) {
			addCriterion("LEVEL_ID not like", value, "levelId");
			return this;
		}

		public Criteria andLevelIdIn(List values) {
			addCriterion("LEVEL_ID in", values, "levelId");
			return this;
		}

		public Criteria andLevelIdNotIn(List values) {
			addCriterion("LEVEL_ID not in", values, "levelId");
			return this;
		}

		public Criteria andLevelIdBetween(String value1, String value2) {
			addCriterion("LEVEL_ID between", value1, value2, "levelId");
			return this;
		}

		public Criteria andLevelIdNotBetween(String value1, String value2) {
			addCriterion("LEVEL_ID not between", value1, value2, "levelId");
			return this;
		}
	}
}