package com.pd.base.model;

public class Paper {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAPER.ID
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAPER.PAPER_NAME
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private String paperName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAPER.PAPER_DESC
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private String paperDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAPER.PAPER_TYPE
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private String paperType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAPER.F1
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private String f1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAPER.F2
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private String f2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAPER.LEVEL_ID
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private String levelId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAPER.ID
     *
     * @return the value of PAPER.ID
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAPER.ID
     *
     * @param id the value for PAPER.ID
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAPER.PAPER_NAME
     *
     * @return the value of PAPER.PAPER_NAME
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAPER.PAPER_NAME
     *
     * @param paperName the value for PAPER.PAPER_NAME
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAPER.PAPER_DESC
     *
     * @return the value of PAPER.PAPER_DESC
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public String getPaperDesc() {
        return paperDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAPER.PAPER_DESC
     *
     * @param paperDesc the value for PAPER.PAPER_DESC
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void setPaperDesc(String paperDesc) {
        this.paperDesc = paperDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAPER.PAPER_TYPE
     *
     * @return the value of PAPER.PAPER_TYPE
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public String getPaperType() {
        return paperType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAPER.PAPER_TYPE
     *
     * @param paperType the value for PAPER.PAPER_TYPE
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void setPaperType(String paperType) {
        this.paperType = paperType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAPER.F1
     *
     * @return the value of PAPER.F1
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAPER.F1
     *
     * @param f1 the value for PAPER.F1
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void setF1(String f1) {
        this.f1 = f1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAPER.F2
     *
     * @return the value of PAPER.F2
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public String getF2() {
        return f2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAPER.F2
     *
     * @param f2 the value for PAPER.F2
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void setF2(String f2) {
        this.f2 = f2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAPER.LEVEL_ID
     *
     * @return the value of PAPER.LEVEL_ID
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public String getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAPER.LEVEL_ID
     *
     * @param levelId the value for PAPER.LEVEL_ID
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void setLevelId(String levelId) {
        this.levelId = levelId;
    }
}