package com.pd.swgl.dao;

import com.pd.swgl.model.ArcStorageIn;
import com.pd.swgl.model.ArcStorageInExample;
import com.pd.system.framework.PageToExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArcStorageInDAOImpl extends SqlMapClientDaoSupport implements ArcStorageInDAO {

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public ArcStorageInDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public void insert(ArcStorageIn record) {
		getSqlMapClientTemplate().insert(
				"ARC_STORAGE_IN.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public int updateByPrimaryKey(ArcStorageIn record) {
		int rows = getSqlMapClientTemplate().update(
				"ARC_STORAGE_IN.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public int updateByPrimaryKeySelective(ArcStorageIn record) {
		int rows = getSqlMapClientTemplate().update(
				"ARC_STORAGE_IN.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public List selectByExample(ArcStorageInExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"ARC_STORAGE_IN.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public ArcStorageIn selectByPrimaryKey(String rkid) {
		ArcStorageIn key = new ArcStorageIn();
		key.setRkid(rkid);
		ArcStorageIn record = (ArcStorageIn) getSqlMapClientTemplate()
				.queryForObject(
						"ARC_STORAGE_IN.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public int deleteByExample(ArcStorageInExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"ARC_STORAGE_IN.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public int deleteByPrimaryKey(String rkid) {
		ArcStorageIn key = new ArcStorageIn();
		key.setRkid(rkid);
		int rows = getSqlMapClientTemplate().delete(
				"ARC_STORAGE_IN.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public int countByExample(ArcStorageInExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"ARC_STORAGE_IN.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public int updateByExampleSelective(ArcStorageIn record,
			ArcStorageInExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"ARC_STORAGE_IN.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	public int updateByExample(ArcStorageIn record, ArcStorageInExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"ARC_STORAGE_IN.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table ARC_STORAGE_IN
	 * @abatorgenerated  Tue Aug 12 10:20:56 CST 2014
	 */
	private static class UpdateByExampleParms extends ArcStorageInExample {
		private Object record;

		public UpdateByExampleParms(Object record, ArcStorageInExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public String getRKSeq() {
		return getSqlMapClientTemplate().queryForObject("ARC_STORAGE_IN.getCRKSeq").toString();
	}

	@Override
	public String getRKPCSeq() {
		return getSqlMapClientTemplate().queryForObject("ARC_STORAGE_IN.getCRKPCSeq").toString();
	}

	@Override
	public List selectByExampleToPage(PageToExample example) {
		return getSqlMapClientTemplate().queryForList("ARC_STORAGE_IN."+SELECT_EXAMPLE_TO_PAGE,example);
	}
}