package com.pd.swgl.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.pd.system.framework.PageToExample;

public class ArcStorageOutExample extends PageToExample{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public ArcStorageOutExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    protected ArcStorageOutExample(ArcStorageOutExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCkidIsNull() {
            addCriterion("CKID is null");
            return this;
        }

        public Criteria andCkidIsNotNull() {
            addCriterion("CKID is not null");
            return this;
        }

        public Criteria andCkidEqualTo(String value) {
            addCriterion("CKID =", value, "ckid");
            return this;
        }

        public Criteria andCkidNotEqualTo(String value) {
            addCriterion("CKID <>", value, "ckid");
            return this;
        }

        public Criteria andCkidGreaterThan(String value) {
            addCriterion("CKID >", value, "ckid");
            return this;
        }

        public Criteria andCkidGreaterThanOrEqualTo(String value) {
            addCriterion("CKID >=", value, "ckid");
            return this;
        }

        public Criteria andCkidLessThan(String value) {
            addCriterion("CKID <", value, "ckid");
            return this;
        }

        public Criteria andCkidLessThanOrEqualTo(String value) {
            addCriterion("CKID <=", value, "ckid");
            return this;
        }

        public Criteria andCkidLike(String value) {
            addCriterion("CKID like", value, "ckid");
            return this;
        }

        public Criteria andCkidNotLike(String value) {
            addCriterion("CKID not like", value, "ckid");
            return this;
        }

        public Criteria andCkidIn(List values) {
            addCriterion("CKID in", values, "ckid");
            return this;
        }

        public Criteria andCkidNotIn(List values) {
            addCriterion("CKID not in", values, "ckid");
            return this;
        }

        public Criteria andCkidBetween(String value1, String value2) {
            addCriterion("CKID between", value1, value2, "ckid");
            return this;
        }

        public Criteria andCkidNotBetween(String value1, String value2) {
            addCriterion("CKID not between", value1, value2, "ckid");
            return this;
        }

        public Criteria andXtdabhIsNull() {
            addCriterion("XTDABH is null");
            return this;
        }

        public Criteria andXtdabhIsNotNull() {
            addCriterion("XTDABH is not null");
            return this;
        }

        public Criteria andXtdabhEqualTo(String value) {
            addCriterion("XTDABH =", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotEqualTo(String value) {
            addCriterion("XTDABH <>", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhGreaterThan(String value) {
            addCriterion("XTDABH >", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhGreaterThanOrEqualTo(String value) {
            addCriterion("XTDABH >=", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLessThan(String value) {
            addCriterion("XTDABH <", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLessThanOrEqualTo(String value) {
            addCriterion("XTDABH <=", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLike(String value) {
            addCriterion("XTDABH like", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotLike(String value) {
            addCriterion("XTDABH not like", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhIn(List values) {
            addCriterion("XTDABH in", values, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotIn(List values) {
            addCriterion("XTDABH not in", values, "xtdabh");
            return this;
        }

        public Criteria andXtdabhBetween(String value1, String value2) {
            addCriterion("XTDABH between", value1, value2, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotBetween(String value1, String value2) {
            addCriterion("XTDABH not between", value1, value2, "xtdabh");
            return this;
        }

        public Criteria andCkpchIsNull() {
            addCriterion("CKPCH is null");
            return this;
        }

        public Criteria andCkpchIsNotNull() {
            addCriterion("CKPCH is not null");
            return this;
        }

        public Criteria andCkpchEqualTo(String value) {
            addCriterion("CKPCH =", value, "ckpch");
            return this;
        }

        public Criteria andCkpchNotEqualTo(String value) {
            addCriterion("CKPCH <>", value, "ckpch");
            return this;
        }

        public Criteria andCkpchGreaterThan(String value) {
            addCriterion("CKPCH >", value, "ckpch");
            return this;
        }

        public Criteria andCkpchGreaterThanOrEqualTo(String value) {
            addCriterion("CKPCH >=", value, "ckpch");
            return this;
        }

        public Criteria andCkpchLessThan(String value) {
            addCriterion("CKPCH <", value, "ckpch");
            return this;
        }

        public Criteria andCkpchLessThanOrEqualTo(String value) {
            addCriterion("CKPCH <=", value, "ckpch");
            return this;
        }

        public Criteria andCkpchLike(String value) {
            addCriterion("CKPCH like", value, "ckpch");
            return this;
        }

        public Criteria andCkpchNotLike(String value) {
            addCriterion("CKPCH not like", value, "ckpch");
            return this;
        }

        public Criteria andCkpchIn(List values) {
            addCriterion("CKPCH in", values, "ckpch");
            return this;
        }

        public Criteria andCkpchNotIn(List values) {
            addCriterion("CKPCH not in", values, "ckpch");
            return this;
        }

        public Criteria andCkpchBetween(String value1, String value2) {
            addCriterion("CKPCH between", value1, value2, "ckpch");
            return this;
        }

        public Criteria andCkpchNotBetween(String value1, String value2) {
            addCriterion("CKPCH not between", value1, value2, "ckpch");
            return this;
        }

        public Criteria andZdaidIsNull() {
            addCriterion("ZDAID is null");
            return this;
        }

        public Criteria andZdaidIsNotNull() {
            addCriterion("ZDAID is not null");
            return this;
        }

        public Criteria andZdaidEqualTo(String value) {
            addCriterion("ZDAID =", value, "zdaid");
            return this;
        }

        public Criteria andZdaidNotEqualTo(String value) {
            addCriterion("ZDAID <>", value, "zdaid");
            return this;
        }

        public Criteria andZdaidGreaterThan(String value) {
            addCriterion("ZDAID >", value, "zdaid");
            return this;
        }

        public Criteria andZdaidGreaterThanOrEqualTo(String value) {
            addCriterion("ZDAID >=", value, "zdaid");
            return this;
        }

        public Criteria andZdaidLessThan(String value) {
            addCriterion("ZDAID <", value, "zdaid");
            return this;
        }

        public Criteria andZdaidLessThanOrEqualTo(String value) {
            addCriterion("ZDAID <=", value, "zdaid");
            return this;
        }

        public Criteria andZdaidLike(String value) {
            addCriterion("ZDAID like", value, "zdaid");
            return this;
        }

        public Criteria andZdaidNotLike(String value) {
            addCriterion("ZDAID not like", value, "zdaid");
            return this;
        }

        public Criteria andZdaidIn(List values) {
            addCriterion("ZDAID in", values, "zdaid");
            return this;
        }

        public Criteria andZdaidNotIn(List values) {
            addCriterion("ZDAID not in", values, "zdaid");
            return this;
        }

        public Criteria andZdaidBetween(String value1, String value2) {
            addCriterion("ZDAID between", value1, value2, "zdaid");
            return this;
        }

        public Criteria andZdaidNotBetween(String value1, String value2) {
            addCriterion("ZDAID not between", value1, value2, "zdaid");
            return this;
        }

        public Criteria andDaztIsNull() {
            addCriterion("DAZT is null");
            return this;
        }

        public Criteria andDaztIsNotNull() {
            addCriterion("DAZT is not null");
            return this;
        }

        public Criteria andDaztEqualTo(String value) {
            addCriterion("DAZT =", value, "dazt");
            return this;
        }

        public Criteria andDaztNotEqualTo(String value) {
            addCriterion("DAZT <>", value, "dazt");
            return this;
        }

        public Criteria andDaztGreaterThan(String value) {
            addCriterion("DAZT >", value, "dazt");
            return this;
        }

        public Criteria andDaztGreaterThanOrEqualTo(String value) {
            addCriterion("DAZT >=", value, "dazt");
            return this;
        }

        public Criteria andDaztLessThan(String value) {
            addCriterion("DAZT <", value, "dazt");
            return this;
        }

        public Criteria andDaztLessThanOrEqualTo(String value) {
            addCriterion("DAZT <=", value, "dazt");
            return this;
        }

        public Criteria andDaztLike(String value) {
            addCriterion("DAZT like", value, "dazt");
            return this;
        }

        public Criteria andDaztNotLike(String value) {
            addCriterion("DAZT not like", value, "dazt");
            return this;
        }

        public Criteria andDaztIn(List values) {
            addCriterion("DAZT in", values, "dazt");
            return this;
        }

        public Criteria andDaztNotIn(List values) {
            addCriterion("DAZT not in", values, "dazt");
            return this;
        }

        public Criteria andDaztBetween(String value1, String value2) {
            addCriterion("DAZT between", value1, value2, "dazt");
            return this;
        }

        public Criteria andDaztNotBetween(String value1, String value2) {
            addCriterion("DAZT not between", value1, value2, "dazt");
            return this;
        }

        public Criteria andCwbhIsNull() {
            addCriterion("CWBH is null");
            return this;
        }

        public Criteria andCwbhIsNotNull() {
            addCriterion("CWBH is not null");
            return this;
        }

        public Criteria andCwbhEqualTo(String value) {
            addCriterion("CWBH =", value, "cwbh");
            return this;
        }

        public Criteria andCwbhNotEqualTo(String value) {
            addCriterion("CWBH <>", value, "cwbh");
            return this;
        }

        public Criteria andCwbhGreaterThan(String value) {
            addCriterion("CWBH >", value, "cwbh");
            return this;
        }

        public Criteria andCwbhGreaterThanOrEqualTo(String value) {
            addCriterion("CWBH >=", value, "cwbh");
            return this;
        }

        public Criteria andCwbhLessThan(String value) {
            addCriterion("CWBH <", value, "cwbh");
            return this;
        }

        public Criteria andCwbhLessThanOrEqualTo(String value) {
            addCriterion("CWBH <=", value, "cwbh");
            return this;
        }

        public Criteria andCwbhLike(String value) {
            addCriterion("CWBH like", value, "cwbh");
            return this;
        }

        public Criteria andCwbhNotLike(String value) {
            addCriterion("CWBH not like", value, "cwbh");
            return this;
        }

        public Criteria andCwbhIn(List values) {
            addCriterion("CWBH in", values, "cwbh");
            return this;
        }

        public Criteria andCwbhNotIn(List values) {
            addCriterion("CWBH not in", values, "cwbh");
            return this;
        }

        public Criteria andCwbhBetween(String value1, String value2) {
            addCriterion("CWBH between", value1, value2, "cwbh");
            return this;
        }

        public Criteria andCwbhNotBetween(String value1, String value2) {
            addCriterion("CWBH not between", value1, value2, "cwbh");
            return this;
        }

        public Criteria andDabhIsNull() {
            addCriterion("DABH is null");
            return this;
        }

        public Criteria andDabhIsNotNull() {
            addCriterion("DABH is not null");
            return this;
        }

        public Criteria andDabhEqualTo(String value) {
            addCriterion("DABH =", value, "dabh");
            return this;
        }

        public Criteria andDabhNotEqualTo(String value) {
            addCriterion("DABH <>", value, "dabh");
            return this;
        }

        public Criteria andDabhGreaterThan(String value) {
            addCriterion("DABH >", value, "dabh");
            return this;
        }

        public Criteria andDabhGreaterThanOrEqualTo(String value) {
            addCriterion("DABH >=", value, "dabh");
            return this;
        }

        public Criteria andDabhLessThan(String value) {
            addCriterion("DABH <", value, "dabh");
            return this;
        }

        public Criteria andDabhLessThanOrEqualTo(String value) {
            addCriterion("DABH <=", value, "dabh");
            return this;
        }

        public Criteria andDabhLike(String value) {
            addCriterion("DABH like", value, "dabh");
            return this;
        }

        public Criteria andDabhNotLike(String value) {
            addCriterion("DABH not like", value, "dabh");
            return this;
        }

        public Criteria andDabhIn(List values) {
            addCriterion("DABH in", values, "dabh");
            return this;
        }

        public Criteria andDabhNotIn(List values) {
            addCriterion("DABH not in", values, "dabh");
            return this;
        }

        public Criteria andDabhBetween(String value1, String value2) {
            addCriterion("DABH between", value1, value2, "dabh");
            return this;
        }

        public Criteria andDabhNotBetween(String value1, String value2) {
            addCriterion("DABH not between", value1, value2, "dabh");
            return this;
        }

        public Criteria andYwlxIsNull() {
            addCriterion("YWLX is null");
            return this;
        }

        public Criteria andYwlxIsNotNull() {
            addCriterion("YWLX is not null");
            return this;
        }

        public Criteria andYwlxEqualTo(String value) {
            addCriterion("YWLX =", value, "ywlx");
            return this;
        }

        public Criteria andYwlxNotEqualTo(String value) {
            addCriterion("YWLX <>", value, "ywlx");
            return this;
        }

        public Criteria andYwlxGreaterThan(String value) {
            addCriterion("YWLX >", value, "ywlx");
            return this;
        }

        public Criteria andYwlxGreaterThanOrEqualTo(String value) {
            addCriterion("YWLX >=", value, "ywlx");
            return this;
        }

        public Criteria andYwlxLessThan(String value) {
            addCriterion("YWLX <", value, "ywlx");
            return this;
        }

        public Criteria andYwlxLessThanOrEqualTo(String value) {
            addCriterion("YWLX <=", value, "ywlx");
            return this;
        }

        public Criteria andYwlxLike(String value) {
            addCriterion("YWLX like", value, "ywlx");
            return this;
        }

        public Criteria andYwlxNotLike(String value) {
            addCriterion("YWLX not like", value, "ywlx");
            return this;
        }

        public Criteria andYwlxIn(List values) {
            addCriterion("YWLX in", values, "ywlx");
            return this;
        }

        public Criteria andYwlxNotIn(List values) {
            addCriterion("YWLX not in", values, "ywlx");
            return this;
        }

        public Criteria andYwlxBetween(String value1, String value2) {
            addCriterion("YWLX between", value1, value2, "ywlx");
            return this;
        }

        public Criteria andYwlxNotBetween(String value1, String value2) {
            addCriterion("YWLX not between", value1, value2, "ywlx");
            return this;
        }

        public Criteria andLshIsNull() {
            addCriterion("LSH is null");
            return this;
        }

        public Criteria andLshIsNotNull() {
            addCriterion("LSH is not null");
            return this;
        }

        public Criteria andLshEqualTo(String value) {
            addCriterion("LSH =", value, "lsh");
            return this;
        }

        public Criteria andLshNotEqualTo(String value) {
            addCriterion("LSH <>", value, "lsh");
            return this;
        }

        public Criteria andLshGreaterThan(String value) {
            addCriterion("LSH >", value, "lsh");
            return this;
        }

        public Criteria andLshGreaterThanOrEqualTo(String value) {
            addCriterion("LSH >=", value, "lsh");
            return this;
        }

        public Criteria andLshLessThan(String value) {
            addCriterion("LSH <", value, "lsh");
            return this;
        }

        public Criteria andLshLessThanOrEqualTo(String value) {
            addCriterion("LSH <=", value, "lsh");
            return this;
        }

        public Criteria andLshLike(String value) {
            addCriterion("LSH like", value, "lsh");
            return this;
        }

        public Criteria andLshNotLike(String value) {
            addCriterion("LSH not like", value, "lsh");
            return this;
        }

        public Criteria andLshIn(List values) {
            addCriterion("LSH in", values, "lsh");
            return this;
        }

        public Criteria andLshNotIn(List values) {
            addCriterion("LSH not in", values, "lsh");
            return this;
        }

        public Criteria andLshBetween(String value1, String value2) {
            addCriterion("LSH between", value1, value2, "lsh");
            return this;
        }

        public Criteria andLshNotBetween(String value1, String value2) {
            addCriterion("LSH not between", value1, value2, "lsh");
            return this;
        }

        public Criteria andHpzlIsNull() {
            addCriterion("HPZL is null");
            return this;
        }

        public Criteria andHpzlIsNotNull() {
            addCriterion("HPZL is not null");
            return this;
        }

        public Criteria andHpzlEqualTo(String value) {
            addCriterion("HPZL =", value, "hpzl");
            return this;
        }

        public Criteria andHpzlNotEqualTo(String value) {
            addCriterion("HPZL <>", value, "hpzl");
            return this;
        }

        public Criteria andHpzlGreaterThan(String value) {
            addCriterion("HPZL >", value, "hpzl");
            return this;
        }

        public Criteria andHpzlGreaterThanOrEqualTo(String value) {
            addCriterion("HPZL >=", value, "hpzl");
            return this;
        }

        public Criteria andHpzlLessThan(String value) {
            addCriterion("HPZL <", value, "hpzl");
            return this;
        }

        public Criteria andHpzlLessThanOrEqualTo(String value) {
            addCriterion("HPZL <=", value, "hpzl");
            return this;
        }

        public Criteria andHpzlLike(String value) {
            addCriterion("HPZL like", value, "hpzl");
            return this;
        }

        public Criteria andHpzlNotLike(String value) {
            addCriterion("HPZL not like", value, "hpzl");
            return this;
        }

        public Criteria andHpzlIn(List values) {
            addCriterion("HPZL in", values, "hpzl");
            return this;
        }

        public Criteria andHpzlNotIn(List values) {
            addCriterion("HPZL not in", values, "hpzl");
            return this;
        }

        public Criteria andHpzlBetween(String value1, String value2) {
            addCriterion("HPZL between", value1, value2, "hpzl");
            return this;
        }

        public Criteria andHpzlNotBetween(String value1, String value2) {
            addCriterion("HPZL not between", value1, value2, "hpzl");
            return this;
        }

        public Criteria andHphmIsNull() {
            addCriterion("HPHM is null");
            return this;
        }

        public Criteria andHphmIsNotNull() {
            addCriterion("HPHM is not null");
            return this;
        }

        public Criteria andHphmEqualTo(String value) {
            addCriterion("HPHM =", value, "hphm");
            return this;
        }

        public Criteria andHphmNotEqualTo(String value) {
            addCriterion("HPHM <>", value, "hphm");
            return this;
        }

        public Criteria andHphmGreaterThan(String value) {
            addCriterion("HPHM >", value, "hphm");
            return this;
        }

        public Criteria andHphmGreaterThanOrEqualTo(String value) {
            addCriterion("HPHM >=", value, "hphm");
            return this;
        }

        public Criteria andHphmLessThan(String value) {
            addCriterion("HPHM <", value, "hphm");
            return this;
        }

        public Criteria andHphmLessThanOrEqualTo(String value) {
            addCriterion("HPHM <=", value, "hphm");
            return this;
        }

        public Criteria andHphmLike(String value) {
            addCriterion("HPHM like", value, "hphm");
            return this;
        }

        public Criteria andHphmNotLike(String value) {
            addCriterion("HPHM not like", value, "hphm");
            return this;
        }

        public Criteria andHphmIn(List values) {
            addCriterion("HPHM in", values, "hphm");
            return this;
        }

        public Criteria andHphmNotIn(List values) {
            addCriterion("HPHM not in", values, "hphm");
            return this;
        }

        public Criteria andHphmBetween(String value1, String value2) {
            addCriterion("HPHM between", value1, value2, "hphm");
            return this;
        }

        public Criteria andHphmNotBetween(String value1, String value2) {
            addCriterion("HPHM not between", value1, value2, "hphm");
            return this;
        }

        public Criteria andClsbdhIsNull() {
            addCriterion("CLSBDH is null");
            return this;
        }

        public Criteria andClsbdhIsNotNull() {
            addCriterion("CLSBDH is not null");
            return this;
        }

        public Criteria andClsbdhEqualTo(String value) {
            addCriterion("CLSBDH =", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhNotEqualTo(String value) {
            addCriterion("CLSBDH <>", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhGreaterThan(String value) {
            addCriterion("CLSBDH >", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhGreaterThanOrEqualTo(String value) {
            addCriterion("CLSBDH >=", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhLessThan(String value) {
            addCriterion("CLSBDH <", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhLessThanOrEqualTo(String value) {
            addCriterion("CLSBDH <=", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhLike(String value) {
            addCriterion("CLSBDH like", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhNotLike(String value) {
            addCriterion("CLSBDH not like", value, "clsbdh");
            return this;
        }

        public Criteria andClsbdhIn(List values) {
            addCriterion("CLSBDH in", values, "clsbdh");
            return this;
        }

        public Criteria andClsbdhNotIn(List values) {
            addCriterion("CLSBDH not in", values, "clsbdh");
            return this;
        }

        public Criteria andClsbdhBetween(String value1, String value2) {
            addCriterion("CLSBDH between", value1, value2, "clsbdh");
            return this;
        }

        public Criteria andClsbdhNotBetween(String value1, String value2) {
            addCriterion("CLSBDH not between", value1, value2, "clsbdh");
            return this;
        }

        public Criteria andXhIsNull() {
            addCriterion("XH is null");
            return this;
        }

        public Criteria andXhIsNotNull() {
            addCriterion("XH is not null");
            return this;
        }

        public Criteria andXhEqualTo(String value) {
            addCriterion("XH =", value, "xh");
            return this;
        }

        public Criteria andXhNotEqualTo(String value) {
            addCriterion("XH <>", value, "xh");
            return this;
        }

        public Criteria andXhGreaterThan(String value) {
            addCriterion("XH >", value, "xh");
            return this;
        }

        public Criteria andXhGreaterThanOrEqualTo(String value) {
            addCriterion("XH >=", value, "xh");
            return this;
        }

        public Criteria andXhLessThan(String value) {
            addCriterion("XH <", value, "xh");
            return this;
        }

        public Criteria andXhLessThanOrEqualTo(String value) {
            addCriterion("XH <=", value, "xh");
            return this;
        }

        public Criteria andXhLike(String value) {
            addCriterion("XH like", value, "xh");
            return this;
        }

        public Criteria andXhNotLike(String value) {
            addCriterion("XH not like", value, "xh");
            return this;
        }

        public Criteria andXhIn(List values) {
            addCriterion("XH in", values, "xh");
            return this;
        }

        public Criteria andXhNotIn(List values) {
            addCriterion("XH not in", values, "xh");
            return this;
        }

        public Criteria andXhBetween(String value1, String value2) {
            addCriterion("XH between", value1, value2, "xh");
            return this;
        }

        public Criteria andXhNotBetween(String value1, String value2) {
            addCriterion("XH not between", value1, value2, "xh");
            return this;
        }

        public Criteria andXzqhIsNull() {
            addCriterion("XZQH is null");
            return this;
        }

        public Criteria andXzqhIsNotNull() {
            addCriterion("XZQH is not null");
            return this;
        }

        public Criteria andXzqhEqualTo(String value) {
            addCriterion("XZQH =", value, "xzqh");
            return this;
        }

        public Criteria andXzqhNotEqualTo(String value) {
            addCriterion("XZQH <>", value, "xzqh");
            return this;
        }

        public Criteria andXzqhGreaterThan(String value) {
            addCriterion("XZQH >", value, "xzqh");
            return this;
        }

        public Criteria andXzqhGreaterThanOrEqualTo(String value) {
            addCriterion("XZQH >=", value, "xzqh");
            return this;
        }

        public Criteria andXzqhLessThan(String value) {
            addCriterion("XZQH <", value, "xzqh");
            return this;
        }

        public Criteria andXzqhLessThanOrEqualTo(String value) {
            addCriterion("XZQH <=", value, "xzqh");
            return this;
        }

        public Criteria andXzqhLike(String value) {
            addCriterion("XZQH like", value, "xzqh");
            return this;
        }

        public Criteria andXzqhNotLike(String value) {
            addCriterion("XZQH not like", value, "xzqh");
            return this;
        }

        public Criteria andXzqhIn(List values) {
            addCriterion("XZQH in", values, "xzqh");
            return this;
        }

        public Criteria andXzqhNotIn(List values) {
            addCriterion("XZQH not in", values, "xzqh");
            return this;
        }

        public Criteria andXzqhBetween(String value1, String value2) {
            addCriterion("XZQH between", value1, value2, "xzqh");
            return this;
        }

        public Criteria andXzqhNotBetween(String value1, String value2) {
            addCriterion("XZQH not between", value1, value2, "xzqh");
            return this;
        }

        public Criteria andSqridIsNull() {
            addCriterion("SQRID is null");
            return this;
        }

        public Criteria andSqridIsNotNull() {
            addCriterion("SQRID is not null");
            return this;
        }

        public Criteria andSqridEqualTo(String value) {
            addCriterion("SQRID =", value, "sqrid");
            return this;
        }

        public Criteria andSqridNotEqualTo(String value) {
            addCriterion("SQRID <>", value, "sqrid");
            return this;
        }

        public Criteria andSqridGreaterThan(String value) {
            addCriterion("SQRID >", value, "sqrid");
            return this;
        }

        public Criteria andSqridGreaterThanOrEqualTo(String value) {
            addCriterion("SQRID >=", value, "sqrid");
            return this;
        }

        public Criteria andSqridLessThan(String value) {
            addCriterion("SQRID <", value, "sqrid");
            return this;
        }

        public Criteria andSqridLessThanOrEqualTo(String value) {
            addCriterion("SQRID <=", value, "sqrid");
            return this;
        }

        public Criteria andSqridLike(String value) {
            addCriterion("SQRID like", value, "sqrid");
            return this;
        }

        public Criteria andSqridNotLike(String value) {
            addCriterion("SQRID not like", value, "sqrid");
            return this;
        }

        public Criteria andSqridIn(List values) {
            addCriterion("SQRID in", values, "sqrid");
            return this;
        }

        public Criteria andSqridNotIn(List values) {
            addCriterion("SQRID not in", values, "sqrid");
            return this;
        }

        public Criteria andSqridBetween(String value1, String value2) {
            addCriterion("SQRID between", value1, value2, "sqrid");
            return this;
        }

        public Criteria andSqridNotBetween(String value1, String value2) {
            addCriterion("SQRID not between", value1, value2, "sqrid");
            return this;
        }

        public Criteria andSqrxmIsNull() {
            addCriterion("SQRXM is null");
            return this;
        }

        public Criteria andSqrxmIsNotNull() {
            addCriterion("SQRXM is not null");
            return this;
        }

        public Criteria andSqrxmEqualTo(String value) {
            addCriterion("SQRXM =", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmNotEqualTo(String value) {
            addCriterion("SQRXM <>", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmGreaterThan(String value) {
            addCriterion("SQRXM >", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmGreaterThanOrEqualTo(String value) {
            addCriterion("SQRXM >=", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmLessThan(String value) {
            addCriterion("SQRXM <", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmLessThanOrEqualTo(String value) {
            addCriterion("SQRXM <=", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmLike(String value) {
            addCriterion("SQRXM like", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmNotLike(String value) {
            addCriterion("SQRXM not like", value, "sqrxm");
            return this;
        }

        public Criteria andSqrxmIn(List values) {
            addCriterion("SQRXM in", values, "sqrxm");
            return this;
        }

        public Criteria andSqrxmNotIn(List values) {
            addCriterion("SQRXM not in", values, "sqrxm");
            return this;
        }

        public Criteria andSqrxmBetween(String value1, String value2) {
            addCriterion("SQRXM between", value1, value2, "sqrxm");
            return this;
        }

        public Criteria andSqrxmNotBetween(String value1, String value2) {
            addCriterion("SQRXM not between", value1, value2, "sqrxm");
            return this;
        }

        public Criteria andSqsjIsNull() {
            addCriterion("SQSJ is null");
            return this;
        }

        public Criteria andSqsjIsNotNull() {
            addCriterion("SQSJ is not null");
            return this;
        }

        public Criteria andSqsjEqualTo(Date value) {
            addCriterion("SQSJ =", value, "sqsj");
            return this;
        }

        public Criteria andSqsjNotEqualTo(Date value) {
            addCriterion("SQSJ <>", value, "sqsj");
            return this;
        }

        public Criteria andSqsjGreaterThan(Date value) {
            addCriterion("SQSJ >", value, "sqsj");
            return this;
        }

        public Criteria andSqsjGreaterThanOrEqualTo(Date value) {
            addCriterion("SQSJ >=", value, "sqsj");
            return this;
        }

        public Criteria andSqsjLessThan(Date value) {
            addCriterion("SQSJ <", value, "sqsj");
            return this;
        }

        public Criteria andSqsjLessThanOrEqualTo(Date value) {
            addCriterion("SQSJ <=", value, "sqsj");
            return this;
        }

        public Criteria andSqsjIn(List values) {
            addCriterion("SQSJ in", values, "sqsj");
            return this;
        }

        public Criteria andSqsjNotIn(List values) {
            addCriterion("SQSJ not in", values, "sqsj");
            return this;
        }

        public Criteria andSqsjBetween(Date value1, Date value2) {
            addCriterion("SQSJ between", value1, value2, "sqsj");
            return this;
        }

        public Criteria andSqsjNotBetween(Date value1, Date value2) {
            addCriterion("SQSJ not between", value1, value2, "sqsj");
            return this;
        }

        public Criteria andSqsmIsNull() {
            addCriterion("SQSM is null");
            return this;
        }

        public Criteria andSqsmIsNotNull() {
            addCriterion("SQSM is not null");
            return this;
        }

        public Criteria andSqsmEqualTo(String value) {
            addCriterion("SQSM =", value, "sqsm");
            return this;
        }

        public Criteria andSqsmNotEqualTo(String value) {
            addCriterion("SQSM <>", value, "sqsm");
            return this;
        }

        public Criteria andSqsmGreaterThan(String value) {
            addCriterion("SQSM >", value, "sqsm");
            return this;
        }

        public Criteria andSqsmGreaterThanOrEqualTo(String value) {
            addCriterion("SQSM >=", value, "sqsm");
            return this;
        }

        public Criteria andSqsmLessThan(String value) {
            addCriterion("SQSM <", value, "sqsm");
            return this;
        }

        public Criteria andSqsmLessThanOrEqualTo(String value) {
            addCriterion("SQSM <=", value, "sqsm");
            return this;
        }

        public Criteria andSqsmLike(String value) {
            addCriterion("SQSM like", value, "sqsm");
            return this;
        }

        public Criteria andSqsmNotLike(String value) {
            addCriterion("SQSM not like", value, "sqsm");
            return this;
        }

        public Criteria andSqsmIn(List values) {
            addCriterion("SQSM in", values, "sqsm");
            return this;
        }

        public Criteria andSqsmNotIn(List values) {
            addCriterion("SQSM not in", values, "sqsm");
            return this;
        }

        public Criteria andSqsmBetween(String value1, String value2) {
            addCriterion("SQSM between", value1, value2, "sqsm");
            return this;
        }

        public Criteria andSqsmNotBetween(String value1, String value2) {
            addCriterion("SQSM not between", value1, value2, "sqsm");
            return this;
        }

        public Criteria andCzridIsNull() {
            addCriterion("CZRID is null");
            return this;
        }

        public Criteria andCzridIsNotNull() {
            addCriterion("CZRID is not null");
            return this;
        }

        public Criteria andCzridEqualTo(String value) {
            addCriterion("CZRID =", value, "czrid");
            return this;
        }

        public Criteria andCzridNotEqualTo(String value) {
            addCriterion("CZRID <>", value, "czrid");
            return this;
        }

        public Criteria andCzridGreaterThan(String value) {
            addCriterion("CZRID >", value, "czrid");
            return this;
        }

        public Criteria andCzridGreaterThanOrEqualTo(String value) {
            addCriterion("CZRID >=", value, "czrid");
            return this;
        }

        public Criteria andCzridLessThan(String value) {
            addCriterion("CZRID <", value, "czrid");
            return this;
        }

        public Criteria andCzridLessThanOrEqualTo(String value) {
            addCriterion("CZRID <=", value, "czrid");
            return this;
        }

        public Criteria andCzridLike(String value) {
            addCriterion("CZRID like", value, "czrid");
            return this;
        }

        public Criteria andCzridNotLike(String value) {
            addCriterion("CZRID not like", value, "czrid");
            return this;
        }

        public Criteria andCzridIn(List values) {
            addCriterion("CZRID in", values, "czrid");
            return this;
        }

        public Criteria andCzridNotIn(List values) {
            addCriterion("CZRID not in", values, "czrid");
            return this;
        }

        public Criteria andCzridBetween(String value1, String value2) {
            addCriterion("CZRID between", value1, value2, "czrid");
            return this;
        }

        public Criteria andCzridNotBetween(String value1, String value2) {
            addCriterion("CZRID not between", value1, value2, "czrid");
            return this;
        }

        public Criteria andCzrxmIsNull() {
            addCriterion("CZRXM is null");
            return this;
        }

        public Criteria andCzrxmIsNotNull() {
            addCriterion("CZRXM is not null");
            return this;
        }

        public Criteria andCzrxmEqualTo(String value) {
            addCriterion("CZRXM =", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmNotEqualTo(String value) {
            addCriterion("CZRXM <>", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmGreaterThan(String value) {
            addCriterion("CZRXM >", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmGreaterThanOrEqualTo(String value) {
            addCriterion("CZRXM >=", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmLessThan(String value) {
            addCriterion("CZRXM <", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmLessThanOrEqualTo(String value) {
            addCriterion("CZRXM <=", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmLike(String value) {
            addCriterion("CZRXM like", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmNotLike(String value) {
            addCriterion("CZRXM not like", value, "czrxm");
            return this;
        }

        public Criteria andCzrxmIn(List values) {
            addCriterion("CZRXM in", values, "czrxm");
            return this;
        }

        public Criteria andCzrxmNotIn(List values) {
            addCriterion("CZRXM not in", values, "czrxm");
            return this;
        }

        public Criteria andCzrxmBetween(String value1, String value2) {
            addCriterion("CZRXM between", value1, value2, "czrxm");
            return this;
        }

        public Criteria andCzrxmNotBetween(String value1, String value2) {
            addCriterion("CZRXM not between", value1, value2, "czrxm");
            return this;
        }

        public Criteria andShridIsNull() {
            addCriterion("SHRID is null");
            return this;
        }

        public Criteria andShridIsNotNull() {
            addCriterion("SHRID is not null");
            return this;
        }

        public Criteria andShridEqualTo(String value) {
            addCriterion("SHRID =", value, "shrid");
            return this;
        }

        public Criteria andShridNotEqualTo(String value) {
            addCriterion("SHRID <>", value, "shrid");
            return this;
        }

        public Criteria andShridGreaterThan(String value) {
            addCriterion("SHRID >", value, "shrid");
            return this;
        }

        public Criteria andShridGreaterThanOrEqualTo(String value) {
            addCriterion("SHRID >=", value, "shrid");
            return this;
        }

        public Criteria andShridLessThan(String value) {
            addCriterion("SHRID <", value, "shrid");
            return this;
        }

        public Criteria andShridLessThanOrEqualTo(String value) {
            addCriterion("SHRID <=", value, "shrid");
            return this;
        }

        public Criteria andShridLike(String value) {
            addCriterion("SHRID like", value, "shrid");
            return this;
        }

        public Criteria andShridNotLike(String value) {
            addCriterion("SHRID not like", value, "shrid");
            return this;
        }

        public Criteria andShridIn(List values) {
            addCriterion("SHRID in", values, "shrid");
            return this;
        }

        public Criteria andShridNotIn(List values) {
            addCriterion("SHRID not in", values, "shrid");
            return this;
        }

        public Criteria andShridBetween(String value1, String value2) {
            addCriterion("SHRID between", value1, value2, "shrid");
            return this;
        }

        public Criteria andShridNotBetween(String value1, String value2) {
            addCriterion("SHRID not between", value1, value2, "shrid");
            return this;
        }

        public Criteria andShrxmIsNull() {
            addCriterion("SHRXM is null");
            return this;
        }

        public Criteria andShrxmIsNotNull() {
            addCriterion("SHRXM is not null");
            return this;
        }

        public Criteria andShrxmEqualTo(String value) {
            addCriterion("SHRXM =", value, "shrxm");
            return this;
        }

        public Criteria andShrxmNotEqualTo(String value) {
            addCriterion("SHRXM <>", value, "shrxm");
            return this;
        }

        public Criteria andShrxmGreaterThan(String value) {
            addCriterion("SHRXM >", value, "shrxm");
            return this;
        }

        public Criteria andShrxmGreaterThanOrEqualTo(String value) {
            addCriterion("SHRXM >=", value, "shrxm");
            return this;
        }

        public Criteria andShrxmLessThan(String value) {
            addCriterion("SHRXM <", value, "shrxm");
            return this;
        }

        public Criteria andShrxmLessThanOrEqualTo(String value) {
            addCriterion("SHRXM <=", value, "shrxm");
            return this;
        }

        public Criteria andShrxmLike(String value) {
            addCriterion("SHRXM like", value, "shrxm");
            return this;
        }

        public Criteria andShrxmNotLike(String value) {
            addCriterion("SHRXM not like", value, "shrxm");
            return this;
        }

        public Criteria andShrxmIn(List values) {
            addCriterion("SHRXM in", values, "shrxm");
            return this;
        }

        public Criteria andShrxmNotIn(List values) {
            addCriterion("SHRXM not in", values, "shrxm");
            return this;
        }

        public Criteria andShrxmBetween(String value1, String value2) {
            addCriterion("SHRXM between", value1, value2, "shrxm");
            return this;
        }

        public Criteria andShrxmNotBetween(String value1, String value2) {
            addCriterion("SHRXM not between", value1, value2, "shrxm");
            return this;
        }

        public Criteria andShsjIsNull() {
            addCriterion("SHSJ is null");
            return this;
        }

        public Criteria andShsjIsNotNull() {
            addCriterion("SHSJ is not null");
            return this;
        }

        public Criteria andShsjEqualTo(Date value) {
            addCriterion("SHSJ =", value, "shsj");
            return this;
        }

        public Criteria andShsjNotEqualTo(Date value) {
            addCriterion("SHSJ <>", value, "shsj");
            return this;
        }

        public Criteria andShsjGreaterThan(Date value) {
            addCriterion("SHSJ >", value, "shsj");
            return this;
        }

        public Criteria andShsjGreaterThanOrEqualTo(Date value) {
            addCriterion("SHSJ >=", value, "shsj");
            return this;
        }

        public Criteria andShsjLessThan(Date value) {
            addCriterion("SHSJ <", value, "shsj");
            return this;
        }

        public Criteria andShsjLessThanOrEqualTo(Date value) {
            addCriterion("SHSJ <=", value, "shsj");
            return this;
        }

        public Criteria andShsjIn(List values) {
            addCriterion("SHSJ in", values, "shsj");
            return this;
        }

        public Criteria andShsjNotIn(List values) {
            addCriterion("SHSJ not in", values, "shsj");
            return this;
        }

        public Criteria andShsjBetween(Date value1, Date value2) {
            addCriterion("SHSJ between", value1, value2, "shsj");
            return this;
        }

        public Criteria andShsjNotBetween(Date value1, Date value2) {
            addCriterion("SHSJ not between", value1, value2, "shsj");
            return this;
        }

        public Criteria andShsmIsNull() {
            addCriterion("SHSM is null");
            return this;
        }

        public Criteria andShsmIsNotNull() {
            addCriterion("SHSM is not null");
            return this;
        }

        public Criteria andShsmEqualTo(String value) {
            addCriterion("SHSM =", value, "shsm");
            return this;
        }

        public Criteria andShsmNotEqualTo(String value) {
            addCriterion("SHSM <>", value, "shsm");
            return this;
        }

        public Criteria andShsmGreaterThan(String value) {
            addCriterion("SHSM >", value, "shsm");
            return this;
        }

        public Criteria andShsmGreaterThanOrEqualTo(String value) {
            addCriterion("SHSM >=", value, "shsm");
            return this;
        }

        public Criteria andShsmLessThan(String value) {
            addCriterion("SHSM <", value, "shsm");
            return this;
        }

        public Criteria andShsmLessThanOrEqualTo(String value) {
            addCriterion("SHSM <=", value, "shsm");
            return this;
        }

        public Criteria andShsmLike(String value) {
            addCriterion("SHSM like", value, "shsm");
            return this;
        }

        public Criteria andShsmNotLike(String value) {
            addCriterion("SHSM not like", value, "shsm");
            return this;
        }

        public Criteria andShsmIn(List values) {
            addCriterion("SHSM in", values, "shsm");
            return this;
        }

        public Criteria andShsmNotIn(List values) {
            addCriterion("SHSM not in", values, "shsm");
            return this;
        }

        public Criteria andShsmBetween(String value1, String value2) {
            addCriterion("SHSM between", value1, value2, "shsm");
            return this;
        }

        public Criteria andShsmNotBetween(String value1, String value2) {
            addCriterion("SHSM not between", value1, value2, "shsm");
            return this;
        }

        public Criteria andCkridIsNull() {
            addCriterion("CKRID is null");
            return this;
        }

        public Criteria andCkridIsNotNull() {
            addCriterion("CKRID is not null");
            return this;
        }

        public Criteria andCkridEqualTo(String value) {
            addCriterion("CKRID =", value, "ckrid");
            return this;
        }

        public Criteria andCkridNotEqualTo(String value) {
            addCriterion("CKRID <>", value, "ckrid");
            return this;
        }

        public Criteria andCkridGreaterThan(String value) {
            addCriterion("CKRID >", value, "ckrid");
            return this;
        }

        public Criteria andCkridGreaterThanOrEqualTo(String value) {
            addCriterion("CKRID >=", value, "ckrid");
            return this;
        }

        public Criteria andCkridLessThan(String value) {
            addCriterion("CKRID <", value, "ckrid");
            return this;
        }

        public Criteria andCkridLessThanOrEqualTo(String value) {
            addCriterion("CKRID <=", value, "ckrid");
            return this;
        }

        public Criteria andCkridLike(String value) {
            addCriterion("CKRID like", value, "ckrid");
            return this;
        }

        public Criteria andCkridNotLike(String value) {
            addCriterion("CKRID not like", value, "ckrid");
            return this;
        }

        public Criteria andCkridIn(List values) {
            addCriterion("CKRID in", values, "ckrid");
            return this;
        }

        public Criteria andCkridNotIn(List values) {
            addCriterion("CKRID not in", values, "ckrid");
            return this;
        }

        public Criteria andCkridBetween(String value1, String value2) {
            addCriterion("CKRID between", value1, value2, "ckrid");
            return this;
        }

        public Criteria andCkridNotBetween(String value1, String value2) {
            addCriterion("CKRID not between", value1, value2, "ckrid");
            return this;
        }

        public Criteria andCkrxmIsNull() {
            addCriterion("CKRXM is null");
            return this;
        }

        public Criteria andCkrxmIsNotNull() {
            addCriterion("CKRXM is not null");
            return this;
        }

        public Criteria andCkrxmEqualTo(String value) {
            addCriterion("CKRXM =", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmNotEqualTo(String value) {
            addCriterion("CKRXM <>", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmGreaterThan(String value) {
            addCriterion("CKRXM >", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmGreaterThanOrEqualTo(String value) {
            addCriterion("CKRXM >=", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmLessThan(String value) {
            addCriterion("CKRXM <", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmLessThanOrEqualTo(String value) {
            addCriterion("CKRXM <=", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmLike(String value) {
            addCriterion("CKRXM like", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmNotLike(String value) {
            addCriterion("CKRXM not like", value, "ckrxm");
            return this;
        }

        public Criteria andCkrxmIn(List values) {
            addCriterion("CKRXM in", values, "ckrxm");
            return this;
        }

        public Criteria andCkrxmNotIn(List values) {
            addCriterion("CKRXM not in", values, "ckrxm");
            return this;
        }

        public Criteria andCkrxmBetween(String value1, String value2) {
            addCriterion("CKRXM between", value1, value2, "ckrxm");
            return this;
        }

        public Criteria andCkrxmNotBetween(String value1, String value2) {
            addCriterion("CKRXM not between", value1, value2, "ckrxm");
            return this;
        }

        public Criteria andCksjIsNull() {
            addCriterion("CKSJ is null");
            return this;
        }

        public Criteria andCksjIsNotNull() {
            addCriterion("CKSJ is not null");
            return this;
        }

        public Criteria andCksjEqualTo(Date value) {
            addCriterion("CKSJ =", value, "cksj");
            return this;
        }

        public Criteria andCksjNotEqualTo(Date value) {
            addCriterion("CKSJ <>", value, "cksj");
            return this;
        }

        public Criteria andCksjGreaterThan(Date value) {
            addCriterion("CKSJ >", value, "cksj");
            return this;
        }

        public Criteria andCksjGreaterThanOrEqualTo(Date value) {
            addCriterion("CKSJ >=", value, "cksj");
            return this;
        }

        public Criteria andCksjLessThan(Date value) {
            addCriterion("CKSJ <", value, "cksj");
            return this;
        }

        public Criteria andCksjLessThanOrEqualTo(Date value) {
            addCriterion("CKSJ <=", value, "cksj");
            return this;
        }

        public Criteria andCksjIn(List values) {
            addCriterion("CKSJ in", values, "cksj");
            return this;
        }

        public Criteria andCksjNotIn(List values) {
            addCriterion("CKSJ not in", values, "cksj");
            return this;
        }

        public Criteria andCksjBetween(Date value1, Date value2) {
            addCriterion("CKSJ between", value1, value2, "cksj");
            return this;
        }

        public Criteria andCksjNotBetween(Date value1, Date value2) {
            addCriterion("CKSJ not between", value1, value2, "cksj");
            return this;
        }

        public Criteria andSfhdIsNull() {
            addCriterion("SFHD is null");
            return this;
        }

        public Criteria andSfhdIsNotNull() {
            addCriterion("SFHD is not null");
            return this;
        }

        public Criteria andSfhdEqualTo(String value) {
            addCriterion("SFHD =", value, "sfhd");
            return this;
        }

        public Criteria andSfhdNotEqualTo(String value) {
            addCriterion("SFHD <>", value, "sfhd");
            return this;
        }

        public Criteria andSfhdGreaterThan(String value) {
            addCriterion("SFHD >", value, "sfhd");
            return this;
        }

        public Criteria andSfhdGreaterThanOrEqualTo(String value) {
            addCriterion("SFHD >=", value, "sfhd");
            return this;
        }

        public Criteria andSfhdLessThan(String value) {
            addCriterion("SFHD <", value, "sfhd");
            return this;
        }

        public Criteria andSfhdLessThanOrEqualTo(String value) {
            addCriterion("SFHD <=", value, "sfhd");
            return this;
        }

        public Criteria andSfhdLike(String value) {
            addCriterion("SFHD like", value, "sfhd");
            return this;
        }

        public Criteria andSfhdNotLike(String value) {
            addCriterion("SFHD not like", value, "sfhd");
            return this;
        }

        public Criteria andSfhdIn(List values) {
            addCriterion("SFHD in", values, "sfhd");
            return this;
        }

        public Criteria andSfhdNotIn(List values) {
            addCriterion("SFHD not in", values, "sfhd");
            return this;
        }

        public Criteria andSfhdBetween(String value1, String value2) {
            addCriterion("SFHD between", value1, value2, "sfhd");
            return this;
        }

        public Criteria andSfhdNotBetween(String value1, String value2) {
            addCriterion("SFHD not between", value1, value2, "sfhd");
            return this;
        }
    }
}