package com.pd.arc.model;

import java.util.Date;

public class ArcBaseInfoAndYcInfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.ID
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.DAZT
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String dazt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.XH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String xh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.YWLX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String ywlx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.LSH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String lsh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.HPZL
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String hpzl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.HPHM
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String hphm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CLSBDH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String clsbdh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.FPRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private Date fprq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SYR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String syr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SFZMHM
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String sfzmhm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.ZSXXDZ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String zsxxdz;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CLPP1
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String clpp1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CLXH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String clxh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CLLX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String cllx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CSYS
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String csys;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.ZZG
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String zzg;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.FDJH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String fdjh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.BZ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String bz;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.DALX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String dalx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.GDR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String gdr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.GDSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private Date gdsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.DABH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String dabh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CWBH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String cwbh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.XZQH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String xzqh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.DEPTCODE
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String deptcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.HDBJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String hdbj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.XTDABH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String xtdabh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CLPP2
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String clpp2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.GDRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String gdrmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.ZZCMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String zzcmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SFZMMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String sfzmmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.FZJG
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String fzjg;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.DJRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private Date djrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SQRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private Date sqrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CJR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String cjr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CJRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String cjrmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.CJSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private Date cjsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SHR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String shr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SHRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String shrmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SHSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private Date shsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.KFBJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String kfbj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.BJRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private Date bjrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.PC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String pc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_BASE_INFO.SFBH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    private String sfbh;
    
    private String yc_id;
    
    private String yc_xtdabh;
    
    private String yc_ywlx;
    
    private String yc_hphm;
    
    private String yc_hpzl;
    
    private String yc_cjr;
    
	private String yc_cjrmc;
	
	private Date yc_cjsj;
	
	private String yc_xzqh;
	
	private String yc_bz;
	
	private String yc_status;
	
	private String yc_shr;
	
	private String yc_shrmc;
	
	private Date yc_shsj;
	
	private String yc_shjg;
	
	private String yc_lsh;
	
	private String yc_sfwj;


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.ID
     *
     * @return the value of ARC_BASE_INFO.ID
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.ID
     *
     * @param id the value for ARC_BASE_INFO.ID
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.DAZT
     *
     * @return the value of ARC_BASE_INFO.DAZT
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getDazt() {
        return dazt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.DAZT
     *
     * @param dazt the value for ARC_BASE_INFO.DAZT
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setDazt(String dazt) {
        this.dazt = dazt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.XH
     *
     * @return the value of ARC_BASE_INFO.XH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.XH
     *
     * @param xh the value for ARC_BASE_INFO.XH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setXh(String xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.YWLX
     *
     * @return the value of ARC_BASE_INFO.YWLX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getYwlx() {
        return ywlx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.YWLX
     *
     * @param ywlx the value for ARC_BASE_INFO.YWLX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setYwlx(String ywlx) {
        this.ywlx = ywlx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.LSH
     *
     * @return the value of ARC_BASE_INFO.LSH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getLsh() {
        return lsh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.LSH
     *
     * @param lsh the value for ARC_BASE_INFO.LSH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setLsh(String lsh) {
        this.lsh = lsh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.HPZL
     *
     * @return the value of ARC_BASE_INFO.HPZL
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.HPZL
     *
     * @param hpzl the value for ARC_BASE_INFO.HPZL
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.HPHM
     *
     * @return the value of ARC_BASE_INFO.HPHM
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.HPHM
     *
     * @param hphm the value for ARC_BASE_INFO.HPHM
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setHphm(String hphm) {
        this.hphm = hphm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CLSBDH
     *
     * @return the value of ARC_BASE_INFO.CLSBDH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getClsbdh() {
        return clsbdh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CLSBDH
     *
     * @param clsbdh the value for ARC_BASE_INFO.CLSBDH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setClsbdh(String clsbdh) {
        this.clsbdh = clsbdh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.FPRQ
     *
     * @return the value of ARC_BASE_INFO.FPRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public Date getFprq() {
        return fprq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.FPRQ
     *
     * @param fprq the value for ARC_BASE_INFO.FPRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setFprq(Date fprq) {
        this.fprq = fprq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SYR
     *
     * @return the value of ARC_BASE_INFO.SYR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getSyr() {
        return syr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SYR
     *
     * @param syr the value for ARC_BASE_INFO.SYR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setSyr(String syr) {
        this.syr = syr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SFZMHM
     *
     * @return the value of ARC_BASE_INFO.SFZMHM
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getSfzmhm() {
        return sfzmhm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SFZMHM
     *
     * @param sfzmhm the value for ARC_BASE_INFO.SFZMHM
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setSfzmhm(String sfzmhm) {
        this.sfzmhm = sfzmhm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.ZSXXDZ
     *
     * @return the value of ARC_BASE_INFO.ZSXXDZ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getZsxxdz() {
        return zsxxdz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.ZSXXDZ
     *
     * @param zsxxdz the value for ARC_BASE_INFO.ZSXXDZ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setZsxxdz(String zsxxdz) {
        this.zsxxdz = zsxxdz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CLPP1
     *
     * @return the value of ARC_BASE_INFO.CLPP1
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getClpp1() {
        return clpp1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CLPP1
     *
     * @param clpp1 the value for ARC_BASE_INFO.CLPP1
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setClpp1(String clpp1) {
        this.clpp1 = clpp1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CLXH
     *
     * @return the value of ARC_BASE_INFO.CLXH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getClxh() {
        return clxh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CLXH
     *
     * @param clxh the value for ARC_BASE_INFO.CLXH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setClxh(String clxh) {
        this.clxh = clxh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CLLX
     *
     * @return the value of ARC_BASE_INFO.CLLX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getCllx() {
        return cllx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CLLX
     *
     * @param cllx the value for ARC_BASE_INFO.CLLX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setCllx(String cllx) {
        this.cllx = cllx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CSYS
     *
     * @return the value of ARC_BASE_INFO.CSYS
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getCsys() {
        return csys;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CSYS
     *
     * @param csys the value for ARC_BASE_INFO.CSYS
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setCsys(String csys) {
        this.csys = csys;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.ZZG
     *
     * @return the value of ARC_BASE_INFO.ZZG
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getZzg() {
        return zzg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.ZZG
     *
     * @param zzg the value for ARC_BASE_INFO.ZZG
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setZzg(String zzg) {
        this.zzg = zzg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.FDJH
     *
     * @return the value of ARC_BASE_INFO.FDJH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getFdjh() {
        return fdjh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.FDJH
     *
     * @param fdjh the value for ARC_BASE_INFO.FDJH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setFdjh(String fdjh) {
        this.fdjh = fdjh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.BZ
     *
     * @return the value of ARC_BASE_INFO.BZ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.BZ
     *
     * @param bz the value for ARC_BASE_INFO.BZ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.DALX
     *
     * @return the value of ARC_BASE_INFO.DALX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getDalx() {
        return dalx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.DALX
     *
     * @param dalx the value for ARC_BASE_INFO.DALX
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setDalx(String dalx) {
        this.dalx = dalx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.GDR
     *
     * @return the value of ARC_BASE_INFO.GDR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getGdr() {
        return gdr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.GDR
     *
     * @param gdr the value for ARC_BASE_INFO.GDR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setGdr(String gdr) {
        this.gdr = gdr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.GDSJ
     *
     * @return the value of ARC_BASE_INFO.GDSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public Date getGdsj() {
        return gdsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.GDSJ
     *
     * @param gdsj the value for ARC_BASE_INFO.GDSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setGdsj(Date gdsj) {
        this.gdsj = gdsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.DABH
     *
     * @return the value of ARC_BASE_INFO.DABH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.DABH
     *
     * @param dabh the value for ARC_BASE_INFO.DABH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setDabh(String dabh) {
        this.dabh = dabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CWBH
     *
     * @return the value of ARC_BASE_INFO.CWBH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getCwbh() {
        return cwbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CWBH
     *
     * @param cwbh the value for ARC_BASE_INFO.CWBH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setCwbh(String cwbh) {
        this.cwbh = cwbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.XZQH
     *
     * @return the value of ARC_BASE_INFO.XZQH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.XZQH
     *
     * @param xzqh the value for ARC_BASE_INFO.XZQH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.DEPTCODE
     *
     * @return the value of ARC_BASE_INFO.DEPTCODE
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.DEPTCODE
     *
     * @param deptcode the value for ARC_BASE_INFO.DEPTCODE
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.HDBJ
     *
     * @return the value of ARC_BASE_INFO.HDBJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getHdbj() {
        return hdbj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.HDBJ
     *
     * @param hdbj the value for ARC_BASE_INFO.HDBJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setHdbj(String hdbj) {
        this.hdbj = hdbj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.XTDABH
     *
     * @return the value of ARC_BASE_INFO.XTDABH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getXtdabh() {
        return xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.XTDABH
     *
     * @param xtdabh the value for ARC_BASE_INFO.XTDABH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setXtdabh(String xtdabh) {
        this.xtdabh = xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CLPP2
     *
     * @return the value of ARC_BASE_INFO.CLPP2
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getClpp2() {
        return clpp2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CLPP2
     *
     * @param clpp2 the value for ARC_BASE_INFO.CLPP2
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setClpp2(String clpp2) {
        this.clpp2 = clpp2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.GDRMC
     *
     * @return the value of ARC_BASE_INFO.GDRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getGdrmc() {
        return gdrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.GDRMC
     *
     * @param gdrmc the value for ARC_BASE_INFO.GDRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setGdrmc(String gdrmc) {
        this.gdrmc = gdrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.ZZCMC
     *
     * @return the value of ARC_BASE_INFO.ZZCMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getZzcmc() {
        return zzcmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.ZZCMC
     *
     * @param zzcmc the value for ARC_BASE_INFO.ZZCMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setZzcmc(String zzcmc) {
        this.zzcmc = zzcmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SFZMMC
     *
     * @return the value of ARC_BASE_INFO.SFZMMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getSfzmmc() {
        return sfzmmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SFZMMC
     *
     * @param sfzmmc the value for ARC_BASE_INFO.SFZMMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setSfzmmc(String sfzmmc) {
        this.sfzmmc = sfzmmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.FZJG
     *
     * @return the value of ARC_BASE_INFO.FZJG
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getFzjg() {
        return fzjg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.FZJG
     *
     * @param fzjg the value for ARC_BASE_INFO.FZJG
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.DJRQ
     *
     * @return the value of ARC_BASE_INFO.DJRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public Date getDjrq() {
        return djrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.DJRQ
     *
     * @param djrq the value for ARC_BASE_INFO.DJRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setDjrq(Date djrq) {
        this.djrq = djrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SQRQ
     *
     * @return the value of ARC_BASE_INFO.SQRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public Date getSqrq() {
        return sqrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SQRQ
     *
     * @param sqrq the value for ARC_BASE_INFO.SQRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setSqrq(Date sqrq) {
        this.sqrq = sqrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CJR
     *
     * @return the value of ARC_BASE_INFO.CJR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CJR
     *
     * @param cjr the value for ARC_BASE_INFO.CJR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setCjr(String cjr) {
        this.cjr = cjr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CJRMC
     *
     * @return the value of ARC_BASE_INFO.CJRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getCjrmc() {
        return cjrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CJRMC
     *
     * @param cjrmc the value for ARC_BASE_INFO.CJRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setCjrmc(String cjrmc) {
        this.cjrmc = cjrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.CJSJ
     *
     * @return the value of ARC_BASE_INFO.CJSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.CJSJ
     *
     * @param cjsj the value for ARC_BASE_INFO.CJSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SHR
     *
     * @return the value of ARC_BASE_INFO.SHR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getShr() {
        return shr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SHR
     *
     * @param shr the value for ARC_BASE_INFO.SHR
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setShr(String shr) {
        this.shr = shr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SHRMC
     *
     * @return the value of ARC_BASE_INFO.SHRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getShrmc() {
        return shrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SHRMC
     *
     * @param shrmc the value for ARC_BASE_INFO.SHRMC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setShrmc(String shrmc) {
        this.shrmc = shrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SHSJ
     *
     * @return the value of ARC_BASE_INFO.SHSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public Date getShsj() {
        return shsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SHSJ
     *
     * @param shsj the value for ARC_BASE_INFO.SHSJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setShsj(Date shsj) {
        this.shsj = shsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.KFBJ
     *
     * @return the value of ARC_BASE_INFO.KFBJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getKfbj() {
        return kfbj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.KFBJ
     *
     * @param kfbj the value for ARC_BASE_INFO.KFBJ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setKfbj(String kfbj) {
        this.kfbj = kfbj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.BJRQ
     *
     * @return the value of ARC_BASE_INFO.BJRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public Date getBjrq() {
        return bjrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.BJRQ
     *
     * @param bjrq the value for ARC_BASE_INFO.BJRQ
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setBjrq(Date bjrq) {
        this.bjrq = bjrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.PC
     *
     * @return the value of ARC_BASE_INFO.PC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getPc() {
        return pc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.PC
     *
     * @param pc the value for ARC_BASE_INFO.PC
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setPc(String pc) {
        this.pc = pc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_BASE_INFO.SFBH
     *
     * @return the value of ARC_BASE_INFO.SFBH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public String getSfbh() {
        return sfbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_BASE_INFO.SFBH
     *
     * @param sfbh the value for ARC_BASE_INFO.SFBH
     *
     * @abatorgenerated Fri Aug 01 13:50:26 CST 2014
     */
    public void setSfbh(String sfbh) {
        this.sfbh = sfbh;
    }

	public String getYc_id() {
		return yc_id;
	}

	public void setYc_id(String ycId) {
		yc_id = ycId;
	}

	public String getYc_xtdabh() {
		return yc_xtdabh;
	}

	public void setYc_xtdabh(String ycXtdabh) {
		yc_xtdabh = ycXtdabh;
	}

	public String getYc_ywlx() {
		return yc_ywlx;
	}

	public void setYc_ywlx(String ycYwlx) {
		yc_ywlx = ycYwlx;
	}

	public String getYc_hphm() {
		return yc_hphm;
	}

	public void setYc_hphm(String ycHphm) {
		yc_hphm = ycHphm;
	}

	public String getYc_hpzl() {
		return yc_hpzl;
	}

	public void setYc_hpzl(String ycHpzl) {
		yc_hpzl = ycHpzl;
	}

	public String getYc_cjr() {
		return yc_cjr;
	}

	public void setYc_cjr(String ycCjr) {
		yc_cjr = ycCjr;
	}

	public String getYc_cjrmc() {
		return yc_cjrmc;
	}

	public void setYc_cjrmc(String ycCjrmc) {
		yc_cjrmc = ycCjrmc;
	}

	public Date getYc_cjsj() {
		return yc_cjsj;
	}

	public void setYc_cjsj(Date ycCjsj) {
		yc_cjsj = ycCjsj;
	}

	public String getYc_xzqh() {
		return yc_xzqh;
	}

	public void setYc_xzqh(String ycXzqh) {
		yc_xzqh = ycXzqh;
	}

	public String getYc_bz() {
		return yc_bz;
	}

	public void setYc_bz(String ycBz) {
		yc_bz = ycBz;
	}

	public String getYc_status() {
		return yc_status;
	}

	public void setYc_status(String ycStatus) {
		yc_status = ycStatus;
	}

	public String getYc_shr() {
		return yc_shr;
	}

	public void setYc_shr(String ycShr) {
		yc_shr = ycShr;
	}

	public String getYc_shrmc() {
		return yc_shrmc;
	}

	public void setYc_shrmc(String ycShrmc) {
		yc_shrmc = ycShrmc;
	}

	public Date getYc_shsj() {
		return yc_shsj;
	}

	public void setYc_shsj(Date ycShsj) {
		yc_shsj = ycShsj;
	}

	public String getYc_shjg() {
		return yc_shjg;
	}

	public void setYc_shjg(String ycShjg) {
		yc_shjg = ycShjg;
	}

	public String getYc_lsh() {
		return yc_lsh;
	}

	public void setYc_lsh(String ycLsh) {
		yc_lsh = ycLsh;
	}

	public String getYc_sfwj() {
		return yc_sfwj;
	}

	public void setYc_sfwj(String ycSfwj) {
		yc_sfwj = ycSfwj;
	}
    
    
}