package com.pd.arc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import com.pd.system.framework.PageToExample;

public class ArcRescanInfoExample extends PageToExample{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public ArcRescanInfoExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    protected ArcRescanInfoExample(ArcRescanInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_RESCAN_INFO
     *
     * @abatorgenerated Tue Aug 12 16:21:31 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andXtdabhIsNull() {
            addCriterion("XTDABH is null");
            return this;
        }

        public Criteria andXtdabhIsNotNull() {
            addCriterion("XTDABH is not null");
            return this;
        }

        public Criteria andXtdabhEqualTo(String value) {
            addCriterion("XTDABH =", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotEqualTo(String value) {
            addCriterion("XTDABH <>", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhGreaterThan(String value) {
            addCriterion("XTDABH >", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhGreaterThanOrEqualTo(String value) {
            addCriterion("XTDABH >=", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLessThan(String value) {
            addCriterion("XTDABH <", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLessThanOrEqualTo(String value) {
            addCriterion("XTDABH <=", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLike(String value) {
            addCriterion("XTDABH like", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotLike(String value) {
            addCriterion("XTDABH not like", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhIn(List values) {
            addCriterion("XTDABH in", values, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotIn(List values) {
            addCriterion("XTDABH not in", values, "xtdabh");
            return this;
        }

        public Criteria andXtdabhBetween(String value1, String value2) {
            addCriterion("XTDABH between", value1, value2, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotBetween(String value1, String value2) {
            addCriterion("XTDABH not between", value1, value2, "xtdabh");
            return this;
        }

        public Criteria andArcStatusIsNull() {
            addCriterion("ARC_STATUS is null");
            return this;
        }

        public Criteria andArcStatusIsNotNull() {
            addCriterion("ARC_STATUS is not null");
            return this;
        }

        public Criteria andArcStatusEqualTo(String value) {
            addCriterion("ARC_STATUS =", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusNotEqualTo(String value) {
            addCriterion("ARC_STATUS <>", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusGreaterThan(String value) {
            addCriterion("ARC_STATUS >", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ARC_STATUS >=", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusLessThan(String value) {
            addCriterion("ARC_STATUS <", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusLessThanOrEqualTo(String value) {
            addCriterion("ARC_STATUS <=", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusLike(String value) {
            addCriterion("ARC_STATUS like", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusNotLike(String value) {
            addCriterion("ARC_STATUS not like", value, "arcStatus");
            return this;
        }

        public Criteria andArcStatusIn(List values) {
            addCriterion("ARC_STATUS in", values, "arcStatus");
            return this;
        }

        public Criteria andArcStatusNotIn(List values) {
            addCriterion("ARC_STATUS not in", values, "arcStatus");
            return this;
        }

        public Criteria andArcStatusBetween(String value1, String value2) {
            addCriterion("ARC_STATUS between", value1, value2, "arcStatus");
            return this;
        }

        public Criteria andArcStatusNotBetween(String value1, String value2) {
            addCriterion("ARC_STATUS not between", value1, value2, "arcStatus");
            return this;
        }

        public Criteria andApplyPeopleIsNull() {
            addCriterion("APPLY_PEOPLE is null");
            return this;
        }

        public Criteria andApplyPeopleIsNotNull() {
            addCriterion("APPLY_PEOPLE is not null");
            return this;
        }

        public Criteria andApplyPeopleEqualTo(String value) {
            addCriterion("APPLY_PEOPLE =", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleNotEqualTo(String value) {
            addCriterion("APPLY_PEOPLE <>", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleGreaterThan(String value) {
            addCriterion("APPLY_PEOPLE >", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_PEOPLE >=", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleLessThan(String value) {
            addCriterion("APPLY_PEOPLE <", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleLessThanOrEqualTo(String value) {
            addCriterion("APPLY_PEOPLE <=", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleLike(String value) {
            addCriterion("APPLY_PEOPLE like", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleNotLike(String value) {
            addCriterion("APPLY_PEOPLE not like", value, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleIn(List values) {
            addCriterion("APPLY_PEOPLE in", values, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleNotIn(List values) {
            addCriterion("APPLY_PEOPLE not in", values, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleBetween(String value1, String value2) {
            addCriterion("APPLY_PEOPLE between", value1, value2, "applyPeople");
            return this;
        }

        public Criteria andApplyPeopleNotBetween(String value1, String value2) {
            addCriterion("APPLY_PEOPLE not between", value1, value2, "applyPeople");
            return this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("APPLY_TIME is null");
            return this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("APPLY_TIME is not null");
            return this;
        }

        public Criteria andApplyTimeEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_TIME =", value, "applyTime");
            return this;
        }

        public Criteria andApplyTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_TIME <>", value, "applyTime");
            return this;
        }

        public Criteria andApplyTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("APPLY_TIME >", value, "applyTime");
            return this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_TIME >=", value, "applyTime");
            return this;
        }

        public Criteria andApplyTimeLessThan(Date value) {
            addCriterionForJDBCDate("APPLY_TIME <", value, "applyTime");
            return this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_TIME <=", value, "applyTime");
            return this;
        }

        public Criteria andApplyTimeIn(List values) {
            addCriterionForJDBCDate("APPLY_TIME in", values, "applyTime");
            return this;
        }

        public Criteria andApplyTimeNotIn(List values) {
            addCriterionForJDBCDate("APPLY_TIME not in", values, "applyTime");
            return this;
        }

        public Criteria andApplyTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APPLY_TIME between", value1, value2, "applyTime");
            return this;
        }

        public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APPLY_TIME not between", value1, value2, "applyTime");
            return this;
        }

        public Criteria andApplyReasonIsNull() {
            addCriterion("APPLY_REASON is null");
            return this;
        }

        public Criteria andApplyReasonIsNotNull() {
            addCriterion("APPLY_REASON is not null");
            return this;
        }

        public Criteria andApplyReasonEqualTo(String value) {
            addCriterion("APPLY_REASON =", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonNotEqualTo(String value) {
            addCriterion("APPLY_REASON <>", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonGreaterThan(String value) {
            addCriterion("APPLY_REASON >", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_REASON >=", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonLessThan(String value) {
            addCriterion("APPLY_REASON <", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonLessThanOrEqualTo(String value) {
            addCriterion("APPLY_REASON <=", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonLike(String value) {
            addCriterion("APPLY_REASON like", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonNotLike(String value) {
            addCriterion("APPLY_REASON not like", value, "applyReason");
            return this;
        }

        public Criteria andApplyReasonIn(List values) {
            addCriterion("APPLY_REASON in", values, "applyReason");
            return this;
        }

        public Criteria andApplyReasonNotIn(List values) {
            addCriterion("APPLY_REASON not in", values, "applyReason");
            return this;
        }

        public Criteria andApplyReasonBetween(String value1, String value2) {
            addCriterion("APPLY_REASON between", value1, value2, "applyReason");
            return this;
        }

        public Criteria andApplyReasonNotBetween(String value1, String value2) {
            addCriterion("APPLY_REASON not between", value1, value2, "applyReason");
            return this;
        }

        public Criteria andVerifyPeopleIsNull() {
            addCriterion("VERIFY_PEOPLE is null");
            return this;
        }

        public Criteria andVerifyPeopleIsNotNull() {
            addCriterion("VERIFY_PEOPLE is not null");
            return this;
        }

        public Criteria andVerifyPeopleEqualTo(String value) {
            addCriterion("VERIFY_PEOPLE =", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleNotEqualTo(String value) {
            addCriterion("VERIFY_PEOPLE <>", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleGreaterThan(String value) {
            addCriterion("VERIFY_PEOPLE >", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_PEOPLE >=", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleLessThan(String value) {
            addCriterion("VERIFY_PEOPLE <", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_PEOPLE <=", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleLike(String value) {
            addCriterion("VERIFY_PEOPLE like", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleNotLike(String value) {
            addCriterion("VERIFY_PEOPLE not like", value, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleIn(List values) {
            addCriterion("VERIFY_PEOPLE in", values, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleNotIn(List values) {
            addCriterion("VERIFY_PEOPLE not in", values, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleBetween(String value1, String value2) {
            addCriterion("VERIFY_PEOPLE between", value1, value2, "verifyPeople");
            return this;
        }

        public Criteria andVerifyPeopleNotBetween(String value1, String value2) {
            addCriterion("VERIFY_PEOPLE not between", value1, value2, "verifyPeople");
            return this;
        }

        public Criteria andVerifyTimeIsNull() {
            addCriterion("VERIFY_TIME is null");
            return this;
        }

        public Criteria andVerifyTimeIsNotNull() {
            addCriterion("VERIFY_TIME is not null");
            return this;
        }

        public Criteria andVerifyTimeEqualTo(Date value) {
            addCriterionForJDBCDate("VERIFY_TIME =", value, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("VERIFY_TIME <>", value, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("VERIFY_TIME >", value, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VERIFY_TIME >=", value, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeLessThan(Date value) {
            addCriterionForJDBCDate("VERIFY_TIME <", value, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VERIFY_TIME <=", value, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeIn(List values) {
            addCriterionForJDBCDate("VERIFY_TIME in", values, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeNotIn(List values) {
            addCriterionForJDBCDate("VERIFY_TIME not in", values, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VERIFY_TIME between", value1, value2, "verifyTime");
            return this;
        }

        public Criteria andVerifyTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VERIFY_TIME not between", value1, value2, "verifyTime");
            return this;
        }

        public Criteria andVerifyResultIsNull() {
            addCriterion("VERIFY_RESULT is null");
            return this;
        }

        public Criteria andVerifyResultIsNotNull() {
            addCriterion("VERIFY_RESULT is not null");
            return this;
        }

        public Criteria andVerifyResultEqualTo(String value) {
            addCriterion("VERIFY_RESULT =", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultNotEqualTo(String value) {
            addCriterion("VERIFY_RESULT <>", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultGreaterThan(String value) {
            addCriterion("VERIFY_RESULT >", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_RESULT >=", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultLessThan(String value) {
            addCriterion("VERIFY_RESULT <", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_RESULT <=", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultLike(String value) {
            addCriterion("VERIFY_RESULT like", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultNotLike(String value) {
            addCriterion("VERIFY_RESULT not like", value, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultIn(List values) {
            addCriterion("VERIFY_RESULT in", values, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultNotIn(List values) {
            addCriterion("VERIFY_RESULT not in", values, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultBetween(String value1, String value2) {
            addCriterion("VERIFY_RESULT between", value1, value2, "verifyResult");
            return this;
        }

        public Criteria andVerifyResultNotBetween(String value1, String value2) {
            addCriterion("VERIFY_RESULT not between", value1, value2, "verifyResult");
            return this;
        }

        public Criteria andVerifyExplainIsNull() {
            addCriterion("VERIFY_EXPLAIN is null");
            return this;
        }

        public Criteria andVerifyExplainIsNotNull() {
            addCriterion("VERIFY_EXPLAIN is not null");
            return this;
        }

        public Criteria andVerifyExplainEqualTo(String value) {
            addCriterion("VERIFY_EXPLAIN =", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainNotEqualTo(String value) {
            addCriterion("VERIFY_EXPLAIN <>", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainGreaterThan(String value) {
            addCriterion("VERIFY_EXPLAIN >", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_EXPLAIN >=", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainLessThan(String value) {
            addCriterion("VERIFY_EXPLAIN <", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_EXPLAIN <=", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainLike(String value) {
            addCriterion("VERIFY_EXPLAIN like", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainNotLike(String value) {
            addCriterion("VERIFY_EXPLAIN not like", value, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainIn(List values) {
            addCriterion("VERIFY_EXPLAIN in", values, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainNotIn(List values) {
            addCriterion("VERIFY_EXPLAIN not in", values, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainBetween(String value1, String value2) {
            addCriterion("VERIFY_EXPLAIN between", value1, value2, "verifyExplain");
            return this;
        }

        public Criteria andVerifyExplainNotBetween(String value1, String value2) {
            addCriterion("VERIFY_EXPLAIN not between", value1, value2, "verifyExplain");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterionForJDBCDate("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterionForJDBCDate("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andSfycsIsNull() {
            addCriterion("SFYCS is null");
            return this;
        }

        public Criteria andSfycsIsNotNull() {
            addCriterion("SFYCS is not null");
            return this;
        }

        public Criteria andSfycsEqualTo(String value) {
            addCriterion("SFYCS =", value, "sfycs");
            return this;
        }

        public Criteria andSfycsNotEqualTo(String value) {
            addCriterion("SFYCS <>", value, "sfycs");
            return this;
        }

        public Criteria andSfycsGreaterThan(String value) {
            addCriterion("SFYCS >", value, "sfycs");
            return this;
        }

        public Criteria andSfycsGreaterThanOrEqualTo(String value) {
            addCriterion("SFYCS >=", value, "sfycs");
            return this;
        }

        public Criteria andSfycsLessThan(String value) {
            addCriterion("SFYCS <", value, "sfycs");
            return this;
        }

        public Criteria andSfycsLessThanOrEqualTo(String value) {
            addCriterion("SFYCS <=", value, "sfycs");
            return this;
        }

        public Criteria andSfycsLike(String value) {
            addCriterion("SFYCS like", value, "sfycs");
            return this;
        }

        public Criteria andSfycsNotLike(String value) {
            addCriterion("SFYCS not like", value, "sfycs");
            return this;
        }

        public Criteria andSfycsIn(List values) {
            addCriterion("SFYCS in", values, "sfycs");
            return this;
        }

        public Criteria andSfycsNotIn(List values) {
            addCriterion("SFYCS not in", values, "sfycs");
            return this;
        }

        public Criteria andSfycsBetween(String value1, String value2) {
            addCriterion("SFYCS between", value1, value2, "sfycs");
            return this;
        }

        public Criteria andSfycsNotBetween(String value1, String value2) {
            addCriterion("SFYCS not between", value1, value2, "sfycs");
            return this;
        }

        public Criteria andSfygdIsNull() {
            addCriterion("SFYGD is null");
            return this;
        }

        public Criteria andSfygdIsNotNull() {
            addCriterion("SFYGD is not null");
            return this;
        }

        public Criteria andSfygdEqualTo(String value) {
            addCriterion("SFYGD =", value, "sfygd");
            return this;
        }

        public Criteria andSfygdNotEqualTo(String value) {
            addCriterion("SFYGD <>", value, "sfygd");
            return this;
        }

        public Criteria andSfygdGreaterThan(String value) {
            addCriterion("SFYGD >", value, "sfygd");
            return this;
        }

        public Criteria andSfygdGreaterThanOrEqualTo(String value) {
            addCriterion("SFYGD >=", value, "sfygd");
            return this;
        }

        public Criteria andSfygdLessThan(String value) {
            addCriterion("SFYGD <", value, "sfygd");
            return this;
        }

        public Criteria andSfygdLessThanOrEqualTo(String value) {
            addCriterion("SFYGD <=", value, "sfygd");
            return this;
        }

        public Criteria andSfygdLike(String value) {
            addCriterion("SFYGD like", value, "sfygd");
            return this;
        }

        public Criteria andSfygdNotLike(String value) {
            addCriterion("SFYGD not like", value, "sfygd");
            return this;
        }

        public Criteria andSfygdIn(List values) {
            addCriterion("SFYGD in", values, "sfygd");
            return this;
        }

        public Criteria andSfygdNotIn(List values) {
            addCriterion("SFYGD not in", values, "sfygd");
            return this;
        }

        public Criteria andSfygdBetween(String value1, String value2) {
            addCriterion("SFYGD between", value1, value2, "sfygd");
            return this;
        }

        public Criteria andSfygdNotBetween(String value1, String value2) {
            addCriterion("SFYGD not between", value1, value2, "sfygd");
            return this;
        }
        
/*****************************      自定义查询条件         *****************************************************/
		
		public Criteria andLshEqualTo(String value) {
			addCriterion("LSH =", value, "lsh");
			return this;
		}
		
		public Criteria andYwlxEqualTo(String value) {
			addCriterion("YWLX =", value, "ywlx");
			return this;
		}
		
		public Criteria andXhEqualTo(String value) {
			addCriterion("XH =", value, "xh");
			return this;
		}
		
		public Criteria andHpzlEqualTo(String value) {
			addCriterion("HPZL =", value, "hpzl");
			return this;
		}
		
		public Criteria andHphmEqualTo(String value) {
			addCriterion("HPHM =", value, "hphm");
			return this;
		}
		
		public Criteria andLshLike(String value) {
	            addCriterion("LSH like", value, "lsh");
	            return this;
	    }
		public Criteria andXhLike(String value) {
            addCriterion("XH like", value, "xh");
            return this;
        }
		public Criteria andHphmLike(String value) {
            addCriterion("HPHM like", value, "hphm");
            return this;
        }
    }
}