package com.pd.arc.model;

import java.util.Date;

public class ArcStatusRecord {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STATUS_RECORD.ID
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STATUS_RECORD.XTDABH
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    private String xtdabh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STATUS_RECORD.CZR
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    private String czr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STATUS_RECORD.CZRMC
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    private String czrmc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STATUS_RECORD.CZSJ
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    private Date czsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STATUS_RECORD.STATUS_CODE
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    private String statusCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STATUS_RECORD.BZ
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    private String bz;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STATUS_RECORD.ID
     *
     * @return the value of ARC_STATUS_RECORD.ID
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STATUS_RECORD.ID
     *
     * @param id the value for ARC_STATUS_RECORD.ID
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STATUS_RECORD.XTDABH
     *
     * @return the value of ARC_STATUS_RECORD.XTDABH
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public String getXtdabh() {
        return xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STATUS_RECORD.XTDABH
     *
     * @param xtdabh the value for ARC_STATUS_RECORD.XTDABH
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public void setXtdabh(String xtdabh) {
        this.xtdabh = xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STATUS_RECORD.CZR
     *
     * @return the value of ARC_STATUS_RECORD.CZR
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public String getCzr() {
        return czr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STATUS_RECORD.CZR
     *
     * @param czr the value for ARC_STATUS_RECORD.CZR
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public void setCzr(String czr) {
        this.czr = czr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STATUS_RECORD.CZRMC
     *
     * @return the value of ARC_STATUS_RECORD.CZRMC
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public String getCzrmc() {
        return czrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STATUS_RECORD.CZRMC
     *
     * @param czrmc the value for ARC_STATUS_RECORD.CZRMC
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public void setCzrmc(String czrmc) {
        this.czrmc = czrmc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STATUS_RECORD.CZSJ
     *
     * @return the value of ARC_STATUS_RECORD.CZSJ
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STATUS_RECORD.CZSJ
     *
     * @param czsj the value for ARC_STATUS_RECORD.CZSJ
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STATUS_RECORD.STATUS_CODE
     *
     * @return the value of ARC_STATUS_RECORD.STATUS_CODE
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STATUS_RECORD.STATUS_CODE
     *
     * @param statusCode the value for ARC_STATUS_RECORD.STATUS_CODE
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STATUS_RECORD.BZ
     *
     * @return the value of ARC_STATUS_RECORD.BZ
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STATUS_RECORD.BZ
     *
     * @param bz the value for ARC_STATUS_RECORD.BZ
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    public void setBz(String bz) {
        this.bz = bz;
    }
}