package com.pd.arc.dao.impl;

import com.pd.arc.model.ArcStatusRecord;
import com.pd.arc.model.ArcStatusRecordExample;
import com.pd.system.framework.BaseDAO;

import java.util.List;

public interface ArcStatusRecordDAO extends BaseDAO{
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    void insert(ArcStatusRecord record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    int updateByPrimaryKey(ArcStatusRecord record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    int updateByPrimaryKeySelective(ArcStatusRecord record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    List selectByExample(ArcStatusRecordExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    ArcStatusRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    int deleteByExample(ArcStatusRecordExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    int countByExample(ArcStatusRecordExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    int updateByExampleSelective(ArcStatusRecord record, ArcStatusRecordExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STATUS_RECORD
     *
     * @abatorgenerated Thu Sep 25 10:51:47 CST 2014
     */
    int updateByExample(ArcStatusRecord record, ArcStatusRecordExample example);
}