package com.pd.right.model;

import java.util.Date;

public class Log {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.ID
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.CZSJ
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private Date czsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.USER_CODE
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String userCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.PROGRAM
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private Long program;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.CZ
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String cz;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.XXSM
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String xxsm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.CZIP
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String czip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.JMW
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String jmw;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.F1
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String f1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.F2
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String f2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.F3
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String f3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LOG.LOGTYPE
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private String logtype;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.ID
     *
     * @return the value of LOG.ID
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.ID
     *
     * @param id the value for LOG.ID
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.CZSJ
     *
     * @return the value of LOG.CZSJ
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.CZSJ
     *
     * @param czsj the value for LOG.CZSJ
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.USER_CODE
     *
     * @return the value of LOG.USER_CODE
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.USER_CODE
     *
     * @param userCode the value for LOG.USER_CODE
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.PROGRAM
     *
     * @return the value of LOG.PROGRAM
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public Long getProgram() {
        return program;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.PROGRAM
     *
     * @param program the value for LOG.PROGRAM
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setProgram(Long program) {
        this.program = program;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.CZ
     *
     * @return the value of LOG.CZ
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.CZ
     *
     * @param cz the value for LOG.CZ
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setCz(String cz) {
        this.cz = cz;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.XXSM
     *
     * @return the value of LOG.XXSM
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getXxsm() {
        return xxsm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.XXSM
     *
     * @param xxsm the value for LOG.XXSM
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setXxsm(String xxsm) {
        this.xxsm = xxsm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.CZIP
     *
     * @return the value of LOG.CZIP
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getCzip() {
        return czip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.CZIP
     *
     * @param czip the value for LOG.CZIP
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setCzip(String czip) {
        this.czip = czip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.JMW
     *
     * @return the value of LOG.JMW
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getJmw() {
        return jmw;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.JMW
     *
     * @param jmw the value for LOG.JMW
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setJmw(String jmw) {
        this.jmw = jmw;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.F1
     *
     * @return the value of LOG.F1
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.F1
     *
     * @param f1 the value for LOG.F1
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setF1(String f1) {
        this.f1 = f1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.F2
     *
     * @return the value of LOG.F2
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getF2() {
        return f2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.F2
     *
     * @param f2 the value for LOG.F2
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setF2(String f2) {
        this.f2 = f2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.F3
     *
     * @return the value of LOG.F3
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getF3() {
        return f3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.F3
     *
     * @param f3 the value for LOG.F3
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setF3(String f3) {
        this.f3 = f3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LOG.LOGTYPE
     *
     * @return the value of LOG.LOGTYPE
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LOG.LOGTYPE
     *
     * @param logtype the value for LOG.LOGTYPE
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype;
    }
}