package com.pd.swgl.model;

import java.util.Date;

public class ArcStorageOut {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CKID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String ckid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.XTDABH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String xtdabh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CKPCH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String ckpch;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.ZDAID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String zdaid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.DAZT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String dazt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CWBH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String cwbh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.DABH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String dabh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.YWLX
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String ywlx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.LSH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String lsh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.HPZL
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String hpzl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.HPHM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String hphm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CLSBDH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String clsbdh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.XH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String xh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.XZQH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String xzqh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SQRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String sqrid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SQRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String sqrxm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SQSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private Date sqsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SQSM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String sqsm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CZRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String czrid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CZRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String czrxm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SHRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String shrid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SHRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String shrxm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SHSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private Date shsj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SHSM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String shsm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CKRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String ckrid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CKRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String ckrxm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.CKSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private Date cksj;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_STORAGE_OUT.SFHD
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private String sfhd;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CKID
     *
     * @return the value of ARC_STORAGE_OUT.CKID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getCkid() {
        return ckid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CKID
     *
     * @param ckid the value for ARC_STORAGE_OUT.CKID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCkid(String ckid) {
        this.ckid = ckid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.XTDABH
     *
     * @return the value of ARC_STORAGE_OUT.XTDABH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getXtdabh() {
        return xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.XTDABH
     *
     * @param xtdabh the value for ARC_STORAGE_OUT.XTDABH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setXtdabh(String xtdabh) {
        this.xtdabh = xtdabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CKPCH
     *
     * @return the value of ARC_STORAGE_OUT.CKPCH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getCkpch() {
        return ckpch;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CKPCH
     *
     * @param ckpch the value for ARC_STORAGE_OUT.CKPCH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCkpch(String ckpch) {
        this.ckpch = ckpch;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.ZDAID
     *
     * @return the value of ARC_STORAGE_OUT.ZDAID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getZdaid() {
        return zdaid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.ZDAID
     *
     * @param zdaid the value for ARC_STORAGE_OUT.ZDAID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setZdaid(String zdaid) {
        this.zdaid = zdaid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.DAZT
     *
     * @return the value of ARC_STORAGE_OUT.DAZT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getDazt() {
        return dazt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.DAZT
     *
     * @param dazt the value for ARC_STORAGE_OUT.DAZT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setDazt(String dazt) {
        this.dazt = dazt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CWBH
     *
     * @return the value of ARC_STORAGE_OUT.CWBH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getCwbh() {
        return cwbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CWBH
     *
     * @param cwbh the value for ARC_STORAGE_OUT.CWBH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCwbh(String cwbh) {
        this.cwbh = cwbh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.DABH
     *
     * @return the value of ARC_STORAGE_OUT.DABH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.DABH
     *
     * @param dabh the value for ARC_STORAGE_OUT.DABH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setDabh(String dabh) {
        this.dabh = dabh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.YWLX
     *
     * @return the value of ARC_STORAGE_OUT.YWLX
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getYwlx() {
        return ywlx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.YWLX
     *
     * @param ywlx the value for ARC_STORAGE_OUT.YWLX
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setYwlx(String ywlx) {
        this.ywlx = ywlx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.LSH
     *
     * @return the value of ARC_STORAGE_OUT.LSH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getLsh() {
        return lsh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.LSH
     *
     * @param lsh the value for ARC_STORAGE_OUT.LSH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setLsh(String lsh) {
        this.lsh = lsh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.HPZL
     *
     * @return the value of ARC_STORAGE_OUT.HPZL
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getHpzl() {
        return hpzl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.HPZL
     *
     * @param hpzl the value for ARC_STORAGE_OUT.HPZL
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setHpzl(String hpzl) {
        this.hpzl = hpzl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.HPHM
     *
     * @return the value of ARC_STORAGE_OUT.HPHM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.HPHM
     *
     * @param hphm the value for ARC_STORAGE_OUT.HPHM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setHphm(String hphm) {
        this.hphm = hphm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CLSBDH
     *
     * @return the value of ARC_STORAGE_OUT.CLSBDH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getClsbdh() {
        return clsbdh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CLSBDH
     *
     * @param clsbdh the value for ARC_STORAGE_OUT.CLSBDH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setClsbdh(String clsbdh) {
        this.clsbdh = clsbdh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.XH
     *
     * @return the value of ARC_STORAGE_OUT.XH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.XH
     *
     * @param xh the value for ARC_STORAGE_OUT.XH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setXh(String xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.XZQH
     *
     * @return the value of ARC_STORAGE_OUT.XZQH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getXzqh() {
        return xzqh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.XZQH
     *
     * @param xzqh the value for ARC_STORAGE_OUT.XZQH
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setXzqh(String xzqh) {
        this.xzqh = xzqh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SQRID
     *
     * @return the value of ARC_STORAGE_OUT.SQRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getSqrid() {
        return sqrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SQRID
     *
     * @param sqrid the value for ARC_STORAGE_OUT.SQRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setSqrid(String sqrid) {
        this.sqrid = sqrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SQRXM
     *
     * @return the value of ARC_STORAGE_OUT.SQRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getSqrxm() {
        return sqrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SQRXM
     *
     * @param sqrxm the value for ARC_STORAGE_OUT.SQRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setSqrxm(String sqrxm) {
        this.sqrxm = sqrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SQSJ
     *
     * @return the value of ARC_STORAGE_OUT.SQSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public Date getSqsj() {
        return sqsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SQSJ
     *
     * @param sqsj the value for ARC_STORAGE_OUT.SQSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setSqsj(Date sqsj) {
        this.sqsj = sqsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SQSM
     *
     * @return the value of ARC_STORAGE_OUT.SQSM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getSqsm() {
        return sqsm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SQSM
     *
     * @param sqsm the value for ARC_STORAGE_OUT.SQSM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setSqsm(String sqsm) {
        this.sqsm = sqsm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CZRID
     *
     * @return the value of ARC_STORAGE_OUT.CZRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getCzrid() {
        return czrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CZRID
     *
     * @param czrid the value for ARC_STORAGE_OUT.CZRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCzrid(String czrid) {
        this.czrid = czrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CZRXM
     *
     * @return the value of ARC_STORAGE_OUT.CZRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getCzrxm() {
        return czrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CZRXM
     *
     * @param czrxm the value for ARC_STORAGE_OUT.CZRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCzrxm(String czrxm) {
        this.czrxm = czrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SHRID
     *
     * @return the value of ARC_STORAGE_OUT.SHRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getShrid() {
        return shrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SHRID
     *
     * @param shrid the value for ARC_STORAGE_OUT.SHRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setShrid(String shrid) {
        this.shrid = shrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SHRXM
     *
     * @return the value of ARC_STORAGE_OUT.SHRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getShrxm() {
        return shrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SHRXM
     *
     * @param shrxm the value for ARC_STORAGE_OUT.SHRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setShrxm(String shrxm) {
        this.shrxm = shrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SHSJ
     *
     * @return the value of ARC_STORAGE_OUT.SHSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public Date getShsj() {
        return shsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SHSJ
     *
     * @param shsj the value for ARC_STORAGE_OUT.SHSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setShsj(Date shsj) {
        this.shsj = shsj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SHSM
     *
     * @return the value of ARC_STORAGE_OUT.SHSM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getShsm() {
        return shsm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SHSM
     *
     * @param shsm the value for ARC_STORAGE_OUT.SHSM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setShsm(String shsm) {
        this.shsm = shsm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CKRID
     *
     * @return the value of ARC_STORAGE_OUT.CKRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getCkrid() {
        return ckrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CKRID
     *
     * @param ckrid the value for ARC_STORAGE_OUT.CKRID
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCkrid(String ckrid) {
        this.ckrid = ckrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CKRXM
     *
     * @return the value of ARC_STORAGE_OUT.CKRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getCkrxm() {
        return ckrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CKRXM
     *
     * @param ckrxm the value for ARC_STORAGE_OUT.CKRXM
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCkrxm(String ckrxm) {
        this.ckrxm = ckrxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.CKSJ
     *
     * @return the value of ARC_STORAGE_OUT.CKSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public Date getCksj() {
        return cksj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.CKSJ
     *
     * @param cksj the value for ARC_STORAGE_OUT.CKSJ
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setCksj(Date cksj) {
        this.cksj = cksj;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_STORAGE_OUT.SFHD
     *
     * @return the value of ARC_STORAGE_OUT.SFHD
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public String getSfhd() {
        return sfhd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_STORAGE_OUT.SFHD
     *
     * @param sfhd the value for ARC_STORAGE_OUT.SFHD
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void setSfhd(String sfhd) {
        this.sfhd = sfhd;
    }
}