package com.pd.base.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.base.model.Attr;
import com.pd.base.model.AttrExample;

public class AttrDAOImpl extends SqlMapClientDaoSupport implements AttrDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public AttrDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void insert(Attr record) {
        getSqlMapClientTemplate().insert("ATTR.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByPrimaryKey(Attr record) {
        int rows = getSqlMapClientTemplate().update("ATTR.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByPrimaryKeySelective(Attr record) {
        int rows = getSqlMapClientTemplate().update("ATTR.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public List selectByExample(AttrExample example) {
        List list = getSqlMapClientTemplate().queryForList("ATTR.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public Attr selectByPrimaryKey(String id) {
        Attr key = new Attr();
        key.setId(id);
        Attr record = (Attr) getSqlMapClientTemplate().queryForObject("ATTR.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int deleteByExample(AttrExample example) {
        int rows = getSqlMapClientTemplate().delete("ATTR.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        Attr key = new Attr();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("ATTR.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int countByExample(AttrExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ATTR.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByExampleSelective(Attr record, AttrExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ATTR.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByExample(Attr record, AttrExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ATTR.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ATTR
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private static class UpdateByExampleParms extends AttrExample {
        private Object record;

        public UpdateByExampleParms(Object record, AttrExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<Attr> selectByExampleToPage(AttrExample example) {
		List<Attr> list = getSqlMapClientTemplate().queryForList("ATTR.abatorgenerated_selectByExampleToPage", example);
	    return list;
	}
}