package com.pd.base.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.base.model.Codeset;
import com.pd.base.model.CodesetExample;

public class CodesetDAOImpl extends SqlMapClientDaoSupport implements CodesetDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public CodesetDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public void insert(Codeset record) {
		getSqlMapClientTemplate().insert("CODESET.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public int updateByPrimaryKey(Codeset record) {
		int rows = getSqlMapClientTemplate().update(
				"CODESET.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public int updateByPrimaryKeySelective(Codeset record) {
		int rows = getSqlMapClientTemplate().update(
				"CODESET.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public List selectByExample(CodesetExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"CODESET.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public Codeset selectByPrimaryKey(String id) {
		Codeset key = new Codeset();
		key.setId(id);
		Codeset record = (Codeset) getSqlMapClientTemplate().queryForObject(
				"CODESET.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public int deleteByExample(CodesetExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"CODESET.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public int deleteByPrimaryKey(String id) {
		Codeset key = new Codeset();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"CODESET.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public int countByExample(CodesetExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"CODESET.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public int updateByExampleSelective(Codeset record, CodesetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"CODESET.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	public int updateByExample(Codeset record, CodesetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"CODESET.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table CODESET
	 * @abatorgenerated  Wed Jun 26 15:31:53 CST 2013
	 */
	private static class UpdateByExampleParms extends CodesetExample {
		private Object record;

		public UpdateByExampleParms(Object record, CodesetExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Codeset> selectByExampleToPage(CodesetExample example) {
		List<Codeset> list = getSqlMapClientTemplate().queryForList("CODESET.abatorgenerated_selectByExampleToPage", example);
	    return list;
	}
}