package com.pd.base.dao.impl;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.base.model.Flow;
import com.pd.base.model.FlowExample;

public class FlowDAOImpl extends SqlMapClientDaoSupport implements FlowDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public FlowDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public void insert(Flow record) {
		getSqlMapClientTemplate().insert("FLOW.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public int updateByPrimaryKey(Flow record) {
		int rows = getSqlMapClientTemplate().update(
				"FLOW.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public int updateByPrimaryKeySelective(Flow record) {
		int rows = getSqlMapClientTemplate().update(
				"FLOW.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public List selectByExample(FlowExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"FLOW.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public Flow selectByPrimaryKey(String id) {
		Flow key = new Flow();
		key.setId(id);
		Flow record = (Flow) getSqlMapClientTemplate().queryForObject(
				"FLOW.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public int deleteByExample(FlowExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"FLOW.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public int deleteByPrimaryKey(String id) {
		Flow key = new Flow();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"FLOW.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public int countByExample(FlowExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"FLOW.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public int updateByExampleSelective(Flow record, FlowExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"FLOW.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	public int updateByExample(Flow record, FlowExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"FLOW.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table FLOW
	 * @abatorgenerated  Tue Jul 09 14:34:40 CST 2013
	 */
	private static class UpdateByExampleParms extends FlowExample {
		private Object record;

		public UpdateByExampleParms(Object record, FlowExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Flow> selectByExampleToPage(FlowExample example) {
		List<Flow> list = getSqlMapClientTemplate().queryForList("FLOW.abatorgenerated_selectByExampleToPage", example);
	    return list;
	}
}