package com.pd.base.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.base.model.Paper;
import com.pd.base.model.PaperExample;

public class PaperDAOImpl extends SqlMapClientDaoSupport implements PaperDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public PaperDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void insert(Paper record) {
        getSqlMapClientTemplate().insert("PAPER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByPrimaryKey(Paper record) {
        int rows = getSqlMapClientTemplate().update("PAPER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByPrimaryKeySelective(Paper record) {
        int rows = getSqlMapClientTemplate().update("PAPER.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public List selectByExample(PaperExample example) {
        List list = getSqlMapClientTemplate().queryForList("PAPER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public Paper selectByPrimaryKey(String id) {
        Paper key = new Paper();
        key.setId(id);
        Paper record = (Paper) getSqlMapClientTemplate().queryForObject("PAPER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int deleteByExample(PaperExample example) {
        int rows = getSqlMapClientTemplate().delete("PAPER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        Paper key = new Paper();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("PAPER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int countByExample(PaperExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("PAPER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByExampleSelective(Paper record, PaperExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PAPER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByExample(Paper record, PaperExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PAPER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table PAPER
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private static class UpdateByExampleParms extends PaperExample {
        private Object record;

        public UpdateByExampleParms(Object record, PaperExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<Paper> selectByExampleToPage(PaperExample example) {
		List<Paper> list = getSqlMapClientTemplate().queryForList("PAPER.abatorgenerated_selectByExampleToPage", example);
	    return list;
	}
}