package com.pd.base.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.base.model.Seclevel;
import com.pd.base.model.SeclevelExample;

public class SeclevelDAOImpl extends SqlMapClientDaoSupport implements SeclevelDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public SeclevelDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public void insert(Seclevel record) {
        getSqlMapClientTemplate().insert("SECLEVEL.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByPrimaryKey(Seclevel record) {
        int rows = getSqlMapClientTemplate().update("SECLEVEL.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByPrimaryKeySelective(Seclevel record) {
        int rows = getSqlMapClientTemplate().update("SECLEVEL.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public List selectByExample(SeclevelExample example) {
        List list = getSqlMapClientTemplate().queryForList("SECLEVEL.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public Seclevel selectByPrimaryKey(String id) {
        Seclevel key = new Seclevel();
        key.setId(id);
        Seclevel record = (Seclevel) getSqlMapClientTemplate().queryForObject("SECLEVEL.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int deleteByExample(SeclevelExample example) {
        int rows = getSqlMapClientTemplate().delete("SECLEVEL.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        Seclevel key = new Seclevel();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("SECLEVEL.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int countByExample(SeclevelExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SECLEVEL.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByExampleSelective(Seclevel record, SeclevelExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SECLEVEL.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    public int updateByExample(Seclevel record, SeclevelExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SECLEVEL.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table SECLEVEL
     *
     * @abatorgenerated Tue Jun 25 16:47:15 CST 2013
     */
    private static class UpdateByExampleParms extends SeclevelExample {
        private Object record;

        public UpdateByExampleParms(Object record, SeclevelExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<Seclevel> selectByExampleToPage(SeclevelExample example) {
		List<Seclevel> list = getSqlMapClientTemplate().queryForList("SECLEVEL.abatorgenerated_selectByExampleToPage", example);
	    return list;
	}
}