package com.pd.right.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.right.model.Log;
import com.pd.right.model.LogExample;

public class LogDAOImpl extends SqlMapClientDaoSupport implements LogDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public LogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void insert(Log record) {
        getSqlMapClientTemplate().insert("LOG.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByPrimaryKey(Log record) {
        int rows = getSqlMapClientTemplate().update("LOG.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByPrimaryKeySelective(Log record) {
        int rows = getSqlMapClientTemplate().update("LOG.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public List selectByExample(LogExample example) {
        List list = getSqlMapClientTemplate().queryForList("LOG.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public Log selectByPrimaryKey(String id) {
        Log key = new Log();
        key.setId(id);
        Log record = (Log) getSqlMapClientTemplate().queryForObject("LOG.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int deleteByExample(LogExample example) {
        int rows = getSqlMapClientTemplate().delete("LOG.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        Log key = new Log();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("LOG.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int countByExample(LogExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("LOG.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByExampleSelective(Log record, LogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("LOG.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByExample(Log record, LogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("LOG.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table LOG
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private static class UpdateByExampleParms extends LogExample {
        private Object record;

        public UpdateByExampleParms(Object record, LogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<Log> selectByExampleToPage(LogExample example) {
		 List<Log> list = getSqlMapClientTemplate().queryForList("LOG.abatorgenerated_selectByExampleToPage", example);
	     return list;
	}
}