package com.pd.right.dao.impl;

import com.pd.right.model.Resources;
import com.pd.right.model.ResourcesExample;
import java.util.List;

public interface ResourcesDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    void insert(Resources record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    int updateByPrimaryKey(Resources record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    int updateByPrimaryKeySelective(Resources record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    List selectByExample(ResourcesExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    Resources selectByPrimaryKey(String resid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    int deleteByExample(ResourcesExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    int deleteByPrimaryKey(String resid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    int countByExample(ResourcesExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    int updateByExampleSelective(Resources record, ResourcesExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    int updateByExample(Resources record, ResourcesExample example);

	List<Resources> selectByExampleToPage(ResourcesExample example);
	
	String getMaxRes(ResourcesExample example);
}