package com.pd.right.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.right.model.SuperUser;
import com.pd.right.model.Users;
import com.pd.right.model.UsersExample;

public class UsersDAOImpl extends SqlMapClientDaoSupport implements UsersDAO {

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public UsersDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public void insert(Users record) {
		getSqlMapClientTemplate()
				.insert("USERS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public int updateByPrimaryKey(Users record) {
		int rows = getSqlMapClientTemplate().update(
				"USERS.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public int updateByPrimaryKeySelective(Users record) {
		int rows = getSqlMapClientTemplate().update(
				"USERS.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public List selectByExample(UsersExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"USERS.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public Users selectByPrimaryKey(String userCode) {
		Users key = new Users();
		key.setUserCode(userCode);
		Users record = (Users) getSqlMapClientTemplate().queryForObject(
				"USERS.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public int deleteByExample(UsersExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"USERS.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public int deleteByPrimaryKey(String userCode) {
		Users key = new Users();
		key.setUserCode(userCode);
		int rows = getSqlMapClientTemplate().delete(
				"USERS.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public int countByExample(UsersExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"USERS.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public int updateByExampleSelective(Users record, UsersExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"USERS.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	public int updateByExample(Users record, UsersExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"USERS.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table USERS
	 * @abatorgenerated  Tue Dec 24 16:10:43 CST 2013
	 */
	private static class UpdateByExampleParms extends UsersExample {
		private Object record;

		public UpdateByExampleParms(Object record, UsersExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Users> selectByExampleToPage(UsersExample example) {
		 List<Users> list = getSqlMapClientTemplate().queryForList("USERS.abatorgenerated_selectByExampleToPage", example);
	     return list;
	}

	@Override
	public SuperUser getUser(String userCode,String password,String type) {
		Map map = new HashMap();
		map.put("userCode", userCode);
		map.put("password", password);
		if (null!=type&&!"".equals(type)) {
			map.put("userstat", type);//查询可用的用户
		}
		return (SuperUser) getSqlMapClientTemplate().queryForObject("USERS.getUser", map);
	}
}