package com.pd.cwgl.dao;

import com.pd.cwgl.model.StoSetting;
import com.pd.cwgl.model.StoSettingExample;
import com.pd.system.framework.PageToExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class StoSettingDAOImpl extends SqlMapClientDaoSupport implements
		StoSettingDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public StoSettingDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public void insert(StoSetting record) {
		getSqlMapClientTemplate().insert("STO_SETTING.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public int updateByPrimaryKey(StoSetting record) {
		int rows = getSqlMapClientTemplate().update(
				"STO_SETTING.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public int updateByPrimaryKeySelective(StoSetting record) {
		int rows = getSqlMapClientTemplate().update(
				"STO_SETTING.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public List selectByExample(StoSettingExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"STO_SETTING.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public StoSetting selectByPrimaryKey(String cid) {
		StoSetting key = new StoSetting();
		key.setCid(cid);
		StoSetting record = (StoSetting) getSqlMapClientTemplate()
				.queryForObject(
						"STO_SETTING.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public int deleteByExample(StoSettingExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"STO_SETTING.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public int deleteByPrimaryKey(String cid) {
		StoSetting key = new StoSetting();
		key.setCid(cid);
		int rows = getSqlMapClientTemplate().delete(
				"STO_SETTING.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public int countByExample(StoSettingExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"STO_SETTING.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public int updateByExampleSelective(StoSetting record,
			StoSettingExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"STO_SETTING.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	public int updateByExample(StoSetting record, StoSettingExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"STO_SETTING.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table STO_SETTING
	 * 
	 * @abatorgenerated Mon Aug 18 15:58:32 CST 2014
	 */
	private static class UpdateByExampleParms extends StoSettingExample {
		private Object record;

		public UpdateByExampleParms(Object record, StoSettingExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List selectByExampleToPage(PageToExample example) {
		return getSqlMapClientTemplate().queryForList(
				"STO_SETTING." + SELECT_EXAMPLE_TO_PAGE, example);
	}

	@Override
	public long selectNumByExample(StoSettingExample example, String sumFiled) {
		example.setTarget(sumFiled);
		Object obj = getSqlMapClientTemplate().queryForObject(
				"STO_SETTING.selectNumByExample", example);
		if (null == obj) {
			return 0;
		}
		return (Long) obj;
	}

	@Override
	public List<StoSetting> selectAutoUsableHe() {
		return getSqlMapClientTemplate().queryForList(
				"STO_SETTING.selectUsableHe");
	}
}