package com.pd.right.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.right.model.Resources;
import com.pd.right.model.ResourcesExample;

public class ResourcesDAOImpl extends SqlMapClientDaoSupport implements ResourcesDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public ResourcesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public void insert(Resources record) {
        getSqlMapClientTemplate().insert("RESOURCES.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByPrimaryKey(Resources record) {
        int rows = getSqlMapClientTemplate().update("RESOURCES.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByPrimaryKeySelective(Resources record) {
        int rows = getSqlMapClientTemplate().update("RESOURCES.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public List selectByExample(ResourcesExample example) {
        List list = getSqlMapClientTemplate().queryForList("RESOURCES.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public Resources selectByPrimaryKey(String resid) {
        Resources key = new Resources();
        key.setResid(resid);
        Resources record = (Resources) getSqlMapClientTemplate().queryForObject("RESOURCES.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int deleteByExample(ResourcesExample example) {
        int rows = getSqlMapClientTemplate().delete("RESOURCES.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int deleteByPrimaryKey(String resid) {
        Resources key = new Resources();
        key.setResid(resid);
        int rows = getSqlMapClientTemplate().delete("RESOURCES.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int countByExample(ResourcesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("RESOURCES.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByExampleSelective(Resources record, ResourcesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("RESOURCES.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    public int updateByExample(Resources record, ResourcesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("RESOURCES.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table RESOURCES
     *
     * @abatorgenerated Tue Jun 25 10:04:54 CST 2013
     */
    private static class UpdateByExampleParms extends ResourcesExample {
        private Object record;

        public UpdateByExampleParms(Object record, ResourcesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<Resources> selectByExampleToPage(ResourcesExample example) {
		 List<Resources> list = getSqlMapClientTemplate().queryForList("RESOURCES.abatorgenerated_selectByExampleToPage", example);
	     return list;
	}

	@Override
	public String getMaxRes(ResourcesExample example) {
		String maxRes = (String)  getSqlMapClientTemplate().queryForObject("RESOURCES.getMaxResByExample", example);
	     return maxRes;
	}
}