package com.pd.wjyw.dao.impl;

import com.pd.system.framework.PageToExample;
import com.pd.wjyw.model.YcInfo;
import com.pd.wjyw.model.YcInfoExample;
import com.pd.wjyw.model.YcInfoSuper;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class YcInfoDAOImpl extends SqlMapClientDaoSupport implements YcInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public YcInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public void insert(YcInfo record) {
		getSqlMapClientTemplate().insert("YC_INFO.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public int updateByPrimaryKey(YcInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public int updateByPrimaryKeySelective(YcInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public List selectByExample(YcInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"YC_INFO.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public YcInfo selectByPrimaryKey(String id) {
		YcInfo key = new YcInfo();
		key.setId(id);
		YcInfo record = (YcInfo) getSqlMapClientTemplate().queryForObject(
				"YC_INFO.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public int deleteByExample(YcInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"YC_INFO.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		YcInfo key = new YcInfo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"YC_INFO.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public int countByExample(YcInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"YC_INFO.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public int updateByExampleSelective(YcInfo record, YcInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public int updateByExample(YcInfo record, YcInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"YC_INFO.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	private static class UpdateByExampleParms extends YcInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, YcInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}


	/**
	 * 分页查询
	 */
	@Override
	public List selectByExampleToPage(PageToExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"YC_INFO.abatorgenerated_selectByExampleToPage", example);
		return list;
	}

	@Override
	public Map getXh(String code) {
		return (Map) getSqlMapClientTemplate().queryForObject("YC_INFO.getMaxXh", code);
	}

	@Override
	public List<YcInfoSuper> getYcInfoByDept(Map map) {
		List<YcInfoSuper> list = getSqlMapClientTemplate().queryForList(
				"YC_INFO.getYcInfoCount", map);
		return list;
	}

	@Override
	public int getYcInfoWeekCount(Map map) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"YC_INFO.getYcInfoWeekCount", map);
		return count.intValue();
	}
	
	@Override
	public String getXtdabhSeq() {
		String xtdabh = (String) getSqlMapClientTemplate().queryForObject(
				"YC_INFO.getXtdabhSeq", null);
		return xtdabh;
	}
	
	
}