package com.pd.wjyw.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import com.pd.system.framework.PageToExample;

public class YcInfoExample extends PageToExample{

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public YcInfoExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	protected YcInfoExample(YcInfoExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table YC_INFO
	 * @abatorgenerated  Tue Aug 05 11:38:16 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andXtdabhIsNull() {
			addCriterion("XTDABH is null");
			return this;
		}

		public Criteria andXtdabhIsNotNull() {
			addCriterion("XTDABH is not null");
			return this;
		}

		public Criteria andXtdabhEqualTo(String value) {
			addCriterion("XTDABH =", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhNotEqualTo(String value) {
			addCriterion("XTDABH <>", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhGreaterThan(String value) {
			addCriterion("XTDABH >", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhGreaterThanOrEqualTo(String value) {
			addCriterion("XTDABH >=", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhLessThan(String value) {
			addCriterion("XTDABH <", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhLessThanOrEqualTo(String value) {
			addCriterion("XTDABH <=", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhLike(String value) {
			addCriterion("XTDABH like", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhNotLike(String value) {
			addCriterion("XTDABH not like", value, "xtdabh");
			return this;
		}

		public Criteria andXtdabhIn(List values) {
			addCriterion("XTDABH in", values, "xtdabh");
			return this;
		}

		public Criteria andXtdabhNotIn(List values) {
			addCriterion("XTDABH not in", values, "xtdabh");
			return this;
		}

		public Criteria andXtdabhBetween(String value1, String value2) {
			addCriterion("XTDABH between", value1, value2, "xtdabh");
			return this;
		}

		public Criteria andXtdabhNotBetween(String value1, String value2) {
			addCriterion("XTDABH not between", value1, value2, "xtdabh");
			return this;
		}

		public Criteria andYwlxIsNull() {
			addCriterion("YWLX is null");
			return this;
		}

		public Criteria andYwlxIsNotNull() {
			addCriterion("YWLX is not null");
			return this;
		}

		public Criteria andYwlxEqualTo(String value) {
			addCriterion("YWLX =", value, "ywlx");
			return this;
		}

		public Criteria andYwlxNotEqualTo(String value) {
			addCriterion("YWLX <>", value, "ywlx");
			return this;
		}

		public Criteria andYwlxGreaterThan(String value) {
			addCriterion("YWLX >", value, "ywlx");
			return this;
		}

		public Criteria andYwlxGreaterThanOrEqualTo(String value) {
			addCriterion("YWLX >=", value, "ywlx");
			return this;
		}

		public Criteria andYwlxLessThan(String value) {
			addCriterion("YWLX <", value, "ywlx");
			return this;
		}

		public Criteria andYwlxLessThanOrEqualTo(String value) {
			addCriterion("YWLX <=", value, "ywlx");
			return this;
		}

		public Criteria andYwlxLike(String value) {
			addCriterion("YWLX like", value, "ywlx");
			return this;
		}

		public Criteria andYwlxNotLike(String value) {
			addCriterion("YWLX not like", value, "ywlx");
			return this;
		}

		public Criteria andYwlxIn(List values) {
			addCriterion("YWLX in", values, "ywlx");
			return this;
		}

		public Criteria andYwlxNotIn(List values) {
			addCriterion("YWLX not in", values, "ywlx");
			return this;
		}

		public Criteria andYwlxBetween(String value1, String value2) {
			addCriterion("YWLX between", value1, value2, "ywlx");
			return this;
		}

		public Criteria andYwlxNotBetween(String value1, String value2) {
			addCriterion("YWLX not between", value1, value2, "ywlx");
			return this;
		}

		public Criteria andHphmIsNull() {
			addCriterion("HPHM is null");
			return this;
		}

		public Criteria andHphmIsNotNull() {
			addCriterion("HPHM is not null");
			return this;
		}

		public Criteria andHphmEqualTo(String value) {
			addCriterion("HPHM =", value, "hphm");
			return this;
		}

		public Criteria andHphmNotEqualTo(String value) {
			addCriterion("HPHM <>", value, "hphm");
			return this;
		}

		public Criteria andHphmGreaterThan(String value) {
			addCriterion("HPHM >", value, "hphm");
			return this;
		}

		public Criteria andHphmGreaterThanOrEqualTo(String value) {
			addCriterion("HPHM >=", value, "hphm");
			return this;
		}

		public Criteria andHphmLessThan(String value) {
			addCriterion("HPHM <", value, "hphm");
			return this;
		}

		public Criteria andHphmLessThanOrEqualTo(String value) {
			addCriterion("HPHM <=", value, "hphm");
			return this;
		}

		public Criteria andHphmLike(String value) {
			addCriterion("HPHM like", value, "hphm");
			return this;
		}

		public Criteria andHphmNotLike(String value) {
			addCriterion("HPHM not like", value, "hphm");
			return this;
		}

		public Criteria andHphmIn(List values) {
			addCriterion("HPHM in", values, "hphm");
			return this;
		}

		public Criteria andHphmNotIn(List values) {
			addCriterion("HPHM not in", values, "hphm");
			return this;
		}

		public Criteria andHphmBetween(String value1, String value2) {
			addCriterion("HPHM between", value1, value2, "hphm");
			return this;
		}

		public Criteria andHphmNotBetween(String value1, String value2) {
			addCriterion("HPHM not between", value1, value2, "hphm");
			return this;
		}

		public Criteria andHpzlIsNull() {
			addCriterion("HPZL is null");
			return this;
		}

		public Criteria andHpzlIsNotNull() {
			addCriterion("HPZL is not null");
			return this;
		}

		public Criteria andHpzlEqualTo(String value) {
			addCriterion("HPZL =", value, "hpzl");
			return this;
		}

		public Criteria andHpzlNotEqualTo(String value) {
			addCriterion("HPZL <>", value, "hpzl");
			return this;
		}

		public Criteria andHpzlGreaterThan(String value) {
			addCriterion("HPZL >", value, "hpzl");
			return this;
		}

		public Criteria andHpzlGreaterThanOrEqualTo(String value) {
			addCriterion("HPZL >=", value, "hpzl");
			return this;
		}

		public Criteria andHpzlLessThan(String value) {
			addCriterion("HPZL <", value, "hpzl");
			return this;
		}

		public Criteria andHpzlLessThanOrEqualTo(String value) {
			addCriterion("HPZL <=", value, "hpzl");
			return this;
		}

		public Criteria andHpzlLike(String value) {
			addCriterion("HPZL like", value, "hpzl");
			return this;
		}

		public Criteria andHpzlNotLike(String value) {
			addCriterion("HPZL not like", value, "hpzl");
			return this;
		}

		public Criteria andHpzlIn(List values) {
			addCriterion("HPZL in", values, "hpzl");
			return this;
		}

		public Criteria andHpzlNotIn(List values) {
			addCriterion("HPZL not in", values, "hpzl");
			return this;
		}

		public Criteria andHpzlBetween(String value1, String value2) {
			addCriterion("HPZL between", value1, value2, "hpzl");
			return this;
		}

		public Criteria andHpzlNotBetween(String value1, String value2) {
			addCriterion("HPZL not between", value1, value2, "hpzl");
			return this;
		}

		public Criteria andCjrIsNull() {
			addCriterion("CJR is null");
			return this;
		}

		public Criteria andCjrIsNotNull() {
			addCriterion("CJR is not null");
			return this;
		}

		public Criteria andCjrEqualTo(String value) {
			addCriterion("CJR =", value, "cjr");
			return this;
		}

		public Criteria andCjrNotEqualTo(String value) {
			addCriterion("CJR <>", value, "cjr");
			return this;
		}

		public Criteria andCjrGreaterThan(String value) {
			addCriterion("CJR >", value, "cjr");
			return this;
		}

		public Criteria andCjrGreaterThanOrEqualTo(String value) {
			addCriterion("CJR >=", value, "cjr");
			return this;
		}

		public Criteria andCjrLessThan(String value) {
			addCriterion("CJR <", value, "cjr");
			return this;
		}

		public Criteria andCjrLessThanOrEqualTo(String value) {
			addCriterion("CJR <=", value, "cjr");
			return this;
		}

		public Criteria andCjrLike(String value) {
			addCriterion("CJR like", value, "cjr");
			return this;
		}

		public Criteria andCjrNotLike(String value) {
			addCriterion("CJR not like", value, "cjr");
			return this;
		}

		public Criteria andCjrIn(List values) {
			addCriterion("CJR in", values, "cjr");
			return this;
		}

		public Criteria andCjrNotIn(List values) {
			addCriterion("CJR not in", values, "cjr");
			return this;
		}

		public Criteria andCjrBetween(String value1, String value2) {
			addCriterion("CJR between", value1, value2, "cjr");
			return this;
		}

		public Criteria andCjrNotBetween(String value1, String value2) {
			addCriterion("CJR not between", value1, value2, "cjr");
			return this;
		}

		public Criteria andCjrmcIsNull() {
			addCriterion("CJRMC is null");
			return this;
		}

		public Criteria andCjrmcIsNotNull() {
			addCriterion("CJRMC is not null");
			return this;
		}

		public Criteria andCjrmcEqualTo(String value) {
			addCriterion("CJRMC =", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcNotEqualTo(String value) {
			addCriterion("CJRMC <>", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcGreaterThan(String value) {
			addCriterion("CJRMC >", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcGreaterThanOrEqualTo(String value) {
			addCriterion("CJRMC >=", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcLessThan(String value) {
			addCriterion("CJRMC <", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcLessThanOrEqualTo(String value) {
			addCriterion("CJRMC <=", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcLike(String value) {
			addCriterion("CJRMC like", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcNotLike(String value) {
			addCriterion("CJRMC not like", value, "cjrmc");
			return this;
		}

		public Criteria andCjrmcIn(List values) {
			addCriterion("CJRMC in", values, "cjrmc");
			return this;
		}

		public Criteria andCjrmcNotIn(List values) {
			addCriterion("CJRMC not in", values, "cjrmc");
			return this;
		}

		public Criteria andCjrmcBetween(String value1, String value2) {
			addCriterion("CJRMC between", value1, value2, "cjrmc");
			return this;
		}

		public Criteria andCjrmcNotBetween(String value1, String value2) {
			addCriterion("CJRMC not between", value1, value2, "cjrmc");
			return this;
		}

		public Criteria andCjsjIsNull() {
			addCriterion("CJSJ is null");
			return this;
		}

		public Criteria andCjsjIsNotNull() {
			addCriterion("CJSJ is not null");
			return this;
		}

		public Criteria andCjsjEqualTo(Date value) {
			addCriterionForJDBCDate("CJSJ =", value, "cjsj");
			return this;
		}

		public Criteria andCjsjNotEqualTo(Date value) {
			addCriterionForJDBCDate("CJSJ <>", value, "cjsj");
			return this;
		}

		public Criteria andCjsjGreaterThan(Date value) {
			addCriterionForJDBCDate("CJSJ >", value, "cjsj");
			return this;
		}

		public Criteria andCjsjGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CJSJ >=", value, "cjsj");
			return this;
		}

		public Criteria andCjsjLessThan(Date value) {
			addCriterionForJDBCDate("CJSJ <", value, "cjsj");
			return this;
		}

		public Criteria andCjsjLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CJSJ <=", value, "cjsj");
			return this;
		}

		public Criteria andCjsjIn(List values) {
			addCriterionForJDBCDate("CJSJ in", values, "cjsj");
			return this;
		}

		public Criteria andCjsjNotIn(List values) {
			addCriterionForJDBCDate("CJSJ not in", values, "cjsj");
			return this;
		}

		public Criteria andCjsjBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CJSJ between", value1, value2, "cjsj");
			return this;
		}

		public Criteria andCjsjNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CJSJ not between", value1, value2, "cjsj");
			return this;
		}

		public Criteria andXzqhIsNull() {
			addCriterion("XZQH is null");
			return this;
		}

		public Criteria andXzqhIsNotNull() {
			addCriterion("XZQH is not null");
			return this;
		}

		public Criteria andXzqhEqualTo(String value) {
			addCriterion("XZQH =", value, "xzqh");
			return this;
		}

		public Criteria andXzqhNotEqualTo(String value) {
			addCriterion("XZQH <>", value, "xzqh");
			return this;
		}

		public Criteria andXzqhGreaterThan(String value) {
			addCriterion("XZQH >", value, "xzqh");
			return this;
		}

		public Criteria andXzqhGreaterThanOrEqualTo(String value) {
			addCriterion("XZQH >=", value, "xzqh");
			return this;
		}

		public Criteria andXzqhLessThan(String value) {
			addCriterion("XZQH <", value, "xzqh");
			return this;
		}

		public Criteria andXzqhLessThanOrEqualTo(String value) {
			addCriterion("XZQH <=", value, "xzqh");
			return this;
		}

		public Criteria andXzqhLike(String value) {
			addCriterion("XZQH like", value, "xzqh");
			return this;
		}

		public Criteria andXzqhNotLike(String value) {
			addCriterion("XZQH not like", value, "xzqh");
			return this;
		}

		public Criteria andXzqhIn(List values) {
			addCriterion("XZQH in", values, "xzqh");
			return this;
		}

		public Criteria andXzqhNotIn(List values) {
			addCriterion("XZQH not in", values, "xzqh");
			return this;
		}

		public Criteria andXzqhBetween(String value1, String value2) {
			addCriterion("XZQH between", value1, value2, "xzqh");
			return this;
		}

		public Criteria andXzqhNotBetween(String value1, String value2) {
			addCriterion("XZQH not between", value1, value2, "xzqh");
			return this;
		}

		public Criteria andBzIsNull() {
			addCriterion("BZ is null");
			return this;
		}

		public Criteria andBzIsNotNull() {
			addCriterion("BZ is not null");
			return this;
		}

		public Criteria andBzEqualTo(String value) {
			addCriterion("BZ =", value, "bz");
			return this;
		}

		public Criteria andBzNotEqualTo(String value) {
			addCriterion("BZ <>", value, "bz");
			return this;
		}

		public Criteria andBzGreaterThan(String value) {
			addCriterion("BZ >", value, "bz");
			return this;
		}

		public Criteria andBzGreaterThanOrEqualTo(String value) {
			addCriterion("BZ >=", value, "bz");
			return this;
		}

		public Criteria andBzLessThan(String value) {
			addCriterion("BZ <", value, "bz");
			return this;
		}

		public Criteria andBzLessThanOrEqualTo(String value) {
			addCriterion("BZ <=", value, "bz");
			return this;
		}

		public Criteria andBzLike(String value) {
			addCriterion("BZ like", value, "bz");
			return this;
		}

		public Criteria andBzNotLike(String value) {
			addCriterion("BZ not like", value, "bz");
			return this;
		}

		public Criteria andBzIn(List values) {
			addCriterion("BZ in", values, "bz");
			return this;
		}

		public Criteria andBzNotIn(List values) {
			addCriterion("BZ not in", values, "bz");
			return this;
		}

		public Criteria andBzBetween(String value1, String value2) {
			addCriterion("BZ between", value1, value2, "bz");
			return this;
		}

		public Criteria andBzNotBetween(String value1, String value2) {
			addCriterion("BZ not between", value1, value2, "bz");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}

		public Criteria andShrIsNull() {
			addCriterion("SHR is null");
			return this;
		}

		public Criteria andShrIsNotNull() {
			addCriterion("SHR is not null");
			return this;
		}

		public Criteria andShrEqualTo(String value) {
			addCriterion("SHR =", value, "shr");
			return this;
		}

		public Criteria andShrNotEqualTo(String value) {
			addCriterion("SHR <>", value, "shr");
			return this;
		}

		public Criteria andShrGreaterThan(String value) {
			addCriterion("SHR >", value, "shr");
			return this;
		}

		public Criteria andShrGreaterThanOrEqualTo(String value) {
			addCriterion("SHR >=", value, "shr");
			return this;
		}

		public Criteria andShrLessThan(String value) {
			addCriterion("SHR <", value, "shr");
			return this;
		}

		public Criteria andShrLessThanOrEqualTo(String value) {
			addCriterion("SHR <=", value, "shr");
			return this;
		}

		public Criteria andShrLike(String value) {
			addCriterion("SHR like", value, "shr");
			return this;
		}

		public Criteria andShrNotLike(String value) {
			addCriterion("SHR not like", value, "shr");
			return this;
		}

		public Criteria andShrIn(List values) {
			addCriterion("SHR in", values, "shr");
			return this;
		}

		public Criteria andShrNotIn(List values) {
			addCriterion("SHR not in", values, "shr");
			return this;
		}

		public Criteria andShrBetween(String value1, String value2) {
			addCriterion("SHR between", value1, value2, "shr");
			return this;
		}

		public Criteria andShrNotBetween(String value1, String value2) {
			addCriterion("SHR not between", value1, value2, "shr");
			return this;
		}

		public Criteria andShrmcIsNull() {
			addCriterion("SHRMC is null");
			return this;
		}

		public Criteria andShrmcIsNotNull() {
			addCriterion("SHRMC is not null");
			return this;
		}

		public Criteria andShrmcEqualTo(String value) {
			addCriterion("SHRMC =", value, "shrmc");
			return this;
		}

		public Criteria andShrmcNotEqualTo(String value) {
			addCriterion("SHRMC <>", value, "shrmc");
			return this;
		}

		public Criteria andShrmcGreaterThan(String value) {
			addCriterion("SHRMC >", value, "shrmc");
			return this;
		}

		public Criteria andShrmcGreaterThanOrEqualTo(String value) {
			addCriterion("SHRMC >=", value, "shrmc");
			return this;
		}

		public Criteria andShrmcLessThan(String value) {
			addCriterion("SHRMC <", value, "shrmc");
			return this;
		}

		public Criteria andShrmcLessThanOrEqualTo(String value) {
			addCriterion("SHRMC <=", value, "shrmc");
			return this;
		}

		public Criteria andShrmcLike(String value) {
			addCriterion("SHRMC like", value, "shrmc");
			return this;
		}

		public Criteria andShrmcNotLike(String value) {
			addCriterion("SHRMC not like", value, "shrmc");
			return this;
		}

		public Criteria andShrmcIn(List values) {
			addCriterion("SHRMC in", values, "shrmc");
			return this;
		}

		public Criteria andShrmcNotIn(List values) {
			addCriterion("SHRMC not in", values, "shrmc");
			return this;
		}

		public Criteria andShrmcBetween(String value1, String value2) {
			addCriterion("SHRMC between", value1, value2, "shrmc");
			return this;
		}

		public Criteria andShrmcNotBetween(String value1, String value2) {
			addCriterion("SHRMC not between", value1, value2, "shrmc");
			return this;
		}

		public Criteria andShsjIsNull() {
			addCriterion("SHSJ is null");
			return this;
		}

		public Criteria andShsjIsNotNull() {
			addCriterion("SHSJ is not null");
			return this;
		}

		public Criteria andShsjEqualTo(Date value) {
			addCriterionForJDBCDate("SHSJ =", value, "shsj");
			return this;
		}

		public Criteria andShsjNotEqualTo(Date value) {
			addCriterionForJDBCDate("SHSJ <>", value, "shsj");
			return this;
		}

		public Criteria andShsjGreaterThan(Date value) {
			addCriterionForJDBCDate("SHSJ >", value, "shsj");
			return this;
		}

		public Criteria andShsjGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("SHSJ >=", value, "shsj");
			return this;
		}

		public Criteria andShsjLessThan(Date value) {
			addCriterionForJDBCDate("SHSJ <", value, "shsj");
			return this;
		}

		public Criteria andShsjLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("SHSJ <=", value, "shsj");
			return this;
		}

		public Criteria andShsjIn(List values) {
			addCriterionForJDBCDate("SHSJ in", values, "shsj");
			return this;
		}

		public Criteria andShsjNotIn(List values) {
			addCriterionForJDBCDate("SHSJ not in", values, "shsj");
			return this;
		}

		public Criteria andShsjBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("SHSJ between", value1, value2, "shsj");
			return this;
		}

		public Criteria andShsjNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("SHSJ not between", value1, value2, "shsj");
			return this;
		}

		public Criteria andShjgIsNull() {
			addCriterion("SHJG is null");
			return this;
		}

		public Criteria andShjgIsNotNull() {
			addCriterion("SHJG is not null");
			return this;
		}

		public Criteria andShjgEqualTo(String value) {
			addCriterion("SHJG =", value, "shjg");
			return this;
		}

		public Criteria andShjgNotEqualTo(String value) {
			addCriterion("SHJG <>", value, "shjg");
			return this;
		}

		public Criteria andShjgGreaterThan(String value) {
			addCriterion("SHJG >", value, "shjg");
			return this;
		}

		public Criteria andShjgGreaterThanOrEqualTo(String value) {
			addCriterion("SHJG >=", value, "shjg");
			return this;
		}

		public Criteria andShjgLessThan(String value) {
			addCriterion("SHJG <", value, "shjg");
			return this;
		}

		public Criteria andShjgLessThanOrEqualTo(String value) {
			addCriterion("SHJG <=", value, "shjg");
			return this;
		}

		public Criteria andShjgLike(String value) {
			addCriterion("SHJG like", value, "shjg");
			return this;
		}

		public Criteria andShjgNotLike(String value) {
			addCriterion("SHJG not like", value, "shjg");
			return this;
		}

		public Criteria andShjgIn(List values) {
			addCriterion("SHJG in", values, "shjg");
			return this;
		}

		public Criteria andShjgNotIn(List values) {
			addCriterion("SHJG not in", values, "shjg");
			return this;
		}

		public Criteria andShjgBetween(String value1, String value2) {
			addCriterion("SHJG between", value1, value2, "shjg");
			return this;
		}

		public Criteria andShjgNotBetween(String value1, String value2) {
			addCriterion("SHJG not between", value1, value2, "shjg");
			return this;
		}

		public Criteria andLshIsNull() {
			addCriterion("LSH is null");
			return this;
		}

		public Criteria andLshIsNotNull() {
			addCriterion("LSH is not null");
			return this;
		}

		public Criteria andLshEqualTo(String value) {
			addCriterion("LSH =", value, "lsh");
			return this;
		}

		public Criteria andLshNotEqualTo(String value) {
			addCriterion("LSH <>", value, "lsh");
			return this;
		}

		public Criteria andLshGreaterThan(String value) {
			addCriterion("LSH >", value, "lsh");
			return this;
		}

		public Criteria andLshGreaterThanOrEqualTo(String value) {
			addCriterion("LSH >=", value, "lsh");
			return this;
		}

		public Criteria andLshLessThan(String value) {
			addCriterion("LSH <", value, "lsh");
			return this;
		}

		public Criteria andLshLessThanOrEqualTo(String value) {
			addCriterion("LSH <=", value, "lsh");
			return this;
		}

		public Criteria andLshLike(String value) {
			addCriterion("LSH like", value, "lsh");
			return this;
		}

		public Criteria andLshNotLike(String value) {
			addCriterion("LSH not like", value, "lsh");
			return this;
		}

		public Criteria andLshIn(List values) {
			addCriterion("LSH in", values, "lsh");
			return this;
		}

		public Criteria andLshNotIn(List values) {
			addCriterion("LSH not in", values, "lsh");
			return this;
		}

		public Criteria andLshBetween(String value1, String value2) {
			addCriterion("LSH between", value1, value2, "lsh");
			return this;
		}

		public Criteria andLshNotBetween(String value1, String value2) {
			addCriterion("LSH not between", value1, value2, "lsh");
			return this;
		}

		public Criteria andSfwjIsNull() {
			addCriterion("SFWJ is null");
			return this;
		}

		public Criteria andSfwjIsNotNull() {
			addCriterion("SFWJ is not null");
			return this;
		}

		public Criteria andSfwjEqualTo(String value) {
			addCriterion("SFWJ =", value, "sfwj");
			return this;
		}

		public Criteria andSfwjNotEqualTo(String value) {
			addCriterion("SFWJ <>", value, "sfwj");
			return this;
		}

		public Criteria andSfwjGreaterThan(String value) {
			addCriterion("SFWJ >", value, "sfwj");
			return this;
		}

		public Criteria andSfwjGreaterThanOrEqualTo(String value) {
			addCriterion("SFWJ >=", value, "sfwj");
			return this;
		}

		public Criteria andSfwjLessThan(String value) {
			addCriterion("SFWJ <", value, "sfwj");
			return this;
		}

		public Criteria andSfwjLessThanOrEqualTo(String value) {
			addCriterion("SFWJ <=", value, "sfwj");
			return this;
		}

		public Criteria andSfwjLike(String value) {
			addCriterion("SFWJ like", value, "sfwj");
			return this;
		}

		public Criteria andSfwjNotLike(String value) {
			addCriterion("SFWJ not like", value, "sfwj");
			return this;
		}

		public Criteria andSfwjIn(List values) {
			addCriterion("SFWJ in", values, "sfwj");
			return this;
		}

		public Criteria andSfwjNotIn(List values) {
			addCriterion("SFWJ not in", values, "sfwj");
			return this;
		}

		public Criteria andSfwjBetween(String value1, String value2) {
			addCriterion("SFWJ between", value1, value2, "sfwj");
			return this;
		}

		public Criteria andSfwjNotBetween(String value1, String value2) {
			addCriterion("SFWJ not between", value1, value2, "sfwj");
			return this;
		}

		public Criteria andDeptcodeIsNull() {
			addCriterion("DEPTCODE is null");
			return this;
		}

		public Criteria andDeptcodeIsNotNull() {
			addCriterion("DEPTCODE is not null");
			return this;
		}

		public Criteria andDeptcodeEqualTo(String value) {
			addCriterion("DEPTCODE =", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeNotEqualTo(String value) {
			addCriterion("DEPTCODE <>", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeGreaterThan(String value) {
			addCriterion("DEPTCODE >", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeGreaterThanOrEqualTo(String value) {
			addCriterion("DEPTCODE >=", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeLessThan(String value) {
			addCriterion("DEPTCODE <", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeLessThanOrEqualTo(String value) {
			addCriterion("DEPTCODE <=", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeLike(String value) {
			addCriterion("DEPTCODE like", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeNotLike(String value) {
			addCriterion("DEPTCODE not like", value, "deptcode");
			return this;
		}

		public Criteria andDeptcodeIn(List values) {
			addCriterion("DEPTCODE in", values, "deptcode");
			return this;
		}

		public Criteria andDeptcodeNotIn(List values) {
			addCriterion("DEPTCODE not in", values, "deptcode");
			return this;
		}

		public Criteria andDeptcodeBetween(String value1, String value2) {
			addCriterion("DEPTCODE between", value1, value2, "deptcode");
			return this;
		}

		public Criteria andDeptcodeNotBetween(String value1, String value2) {
			addCriterion("DEPTCODE not between", value1, value2, "deptcode");
			return this;
		}
		public Criteria andCjsjGreaterThanOrEqualTo(String sdate) {
			addCriterion("to_char(CJSJ,'yyyy-mm-dd')>=", sdate, "cjsj");
            return this;
			
		}

		public Criteria andCCjsjLessThanOrEqualTo(String edate) {
			addCriterion("to_char(CJSJ,'yyyy-mm-dd'<=", edate, "cjsj");
            return this;
		}
	}
}