package com.pd.base.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.pd.system.framework.PageToExample;

public class TypesetExample  extends PageToExample{

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public TypesetExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	protected TypesetExample(TypesetExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andTypeIdIsNull() {
			addCriterion("TYPE_ID is null");
			return this;
		}

		public Criteria andTypeIdIsNotNull() {
			addCriterion("TYPE_ID is not null");
			return this;
		}

		public Criteria andTypeIdEqualTo(String value) {
			addCriterion("TYPE_ID =", value, "typeId");
			return this;
		}

		public Criteria andTypeIdNotEqualTo(String value) {
			addCriterion("TYPE_ID <>", value, "typeId");
			return this;
		}

		public Criteria andTypeIdGreaterThan(String value) {
			addCriterion("TYPE_ID >", value, "typeId");
			return this;
		}

		public Criteria andTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE_ID >=", value, "typeId");
			return this;
		}

		public Criteria andTypeIdLessThan(String value) {
			addCriterion("TYPE_ID <", value, "typeId");
			return this;
		}

		public Criteria andTypeIdLessThanOrEqualTo(String value) {
			addCriterion("TYPE_ID <=", value, "typeId");
			return this;
		}

		public Criteria andTypeIdLike(String value) {
			addCriterion("TYPE_ID like", value, "typeId");
			return this;
		}

		public Criteria andTypeIdNotLike(String value) {
			addCriterion("TYPE_ID not like", value, "typeId");
			return this;
		}

		public Criteria andTypeIdIn(List values) {
			addCriterion("TYPE_ID in", values, "typeId");
			return this;
		}

		public Criteria andTypeIdNotIn(List values) {
			addCriterion("TYPE_ID not in", values, "typeId");
			return this;
		}

		public Criteria andTypeIdBetween(String value1, String value2) {
			addCriterion("TYPE_ID between", value1, value2, "typeId");
			return this;
		}

		public Criteria andTypeIdNotBetween(String value1, String value2) {
			addCriterion("TYPE_ID not between", value1, value2, "typeId");
			return this;
		}

		public Criteria andPaperIdIsNull() {
			addCriterion("PAPER_ID is null");
			return this;
		}

		public Criteria andPaperIdIsNotNull() {
			addCriterion("PAPER_ID is not null");
			return this;
		}

		public Criteria andPaperIdEqualTo(String value) {
			addCriterion("PAPER_ID =", value, "paperId");
			return this;
		}

		public Criteria andPaperIdNotEqualTo(String value) {
			addCriterion("PAPER_ID <>", value, "paperId");
			return this;
		}

		public Criteria andPaperIdGreaterThan(String value) {
			addCriterion("PAPER_ID >", value, "paperId");
			return this;
		}

		public Criteria andPaperIdGreaterThanOrEqualTo(String value) {
			addCriterion("PAPER_ID >=", value, "paperId");
			return this;
		}

		public Criteria andPaperIdLessThan(String value) {
			addCriterion("PAPER_ID <", value, "paperId");
			return this;
		}

		public Criteria andPaperIdLessThanOrEqualTo(String value) {
			addCriterion("PAPER_ID <=", value, "paperId");
			return this;
		}

		public Criteria andPaperIdLike(String value) {
			addCriterion("PAPER_ID like", value, "paperId");
			return this;
		}

		public Criteria andPaperIdNotLike(String value) {
			addCriterion("PAPER_ID not like", value, "paperId");
			return this;
		}

		public Criteria andPaperIdIn(List values) {
			addCriterion("PAPER_ID in", values, "paperId");
			return this;
		}

		public Criteria andPaperIdNotIn(List values) {
			addCriterion("PAPER_ID not in", values, "paperId");
			return this;
		}

		public Criteria andPaperIdBetween(String value1, String value2) {
			addCriterion("PAPER_ID between", value1, value2, "paperId");
			return this;
		}

		public Criteria andPaperIdNotBetween(String value1, String value2) {
			addCriterion("PAPER_ID not between", value1, value2, "paperId");
			return this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("ROLE_ID is null");
			return this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("ROLE_ID is not null");
			return this;
		}

		public Criteria andRoleIdEqualTo(Long value) {
			addCriterion("ROLE_ID =", value, "roleId");
			return this;
		}

		public Criteria andRoleIdNotEqualTo(Long value) {
			addCriterion("ROLE_ID <>", value, "roleId");
			return this;
		}

		public Criteria andRoleIdGreaterThan(Long value) {
			addCriterion("ROLE_ID >", value, "roleId");
			return this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ROLE_ID >=", value, "roleId");
			return this;
		}

		public Criteria andRoleIdLessThan(Long value) {
			addCriterion("ROLE_ID <", value, "roleId");
			return this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("ROLE_ID <=", value, "roleId");
			return this;
		}

		public Criteria andRoleIdIn(List values) {
			addCriterion("ROLE_ID in", values, "roleId");
			return this;
		}

		public Criteria andRoleIdNotIn(List values) {
			addCriterion("ROLE_ID not in", values, "roleId");
			return this;
		}

		public Criteria andRoleIdBetween(Long value1, Long value2) {
			addCriterion("ROLE_ID between", value1, value2, "roleId");
			return this;
		}

		public Criteria andRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("ROLE_ID not between", value1, value2, "roleId");
			return this;
		}

		public Criteria andSetdescIsNull() {
			addCriterion("SETDESC is null");
			return this;
		}

		public Criteria andSetdescIsNotNull() {
			addCriterion("SETDESC is not null");
			return this;
		}

		public Criteria andSetdescEqualTo(String value) {
			addCriterion("SETDESC =", value, "setdesc");
			return this;
		}

		public Criteria andSetdescNotEqualTo(String value) {
			addCriterion("SETDESC <>", value, "setdesc");
			return this;
		}

		public Criteria andSetdescGreaterThan(String value) {
			addCriterion("SETDESC >", value, "setdesc");
			return this;
		}

		public Criteria andSetdescGreaterThanOrEqualTo(String value) {
			addCriterion("SETDESC >=", value, "setdesc");
			return this;
		}

		public Criteria andSetdescLessThan(String value) {
			addCriterion("SETDESC <", value, "setdesc");
			return this;
		}

		public Criteria andSetdescLessThanOrEqualTo(String value) {
			addCriterion("SETDESC <=", value, "setdesc");
			return this;
		}

		public Criteria andSetdescLike(String value) {
			addCriterion("SETDESC like", value, "setdesc");
			return this;
		}

		public Criteria andSetdescNotLike(String value) {
			addCriterion("SETDESC not like", value, "setdesc");
			return this;
		}

		public Criteria andSetdescIn(List values) {
			addCriterion("SETDESC in", values, "setdesc");
			return this;
		}

		public Criteria andSetdescNotIn(List values) {
			addCriterion("SETDESC not in", values, "setdesc");
			return this;
		}

		public Criteria andSetdescBetween(String value1, String value2) {
			addCriterion("SETDESC between", value1, value2, "setdesc");
			return this;
		}

		public Criteria andSetdescNotBetween(String value1, String value2) {
			addCriterion("SETDESC not between", value1, value2, "setdesc");
			return this;
		}

		public Criteria andF1IsNull() {
			addCriterion("F1 is null");
			return this;
		}

		public Criteria andF1IsNotNull() {
			addCriterion("F1 is not null");
			return this;
		}

		public Criteria andF1EqualTo(String value) {
			addCriterion("F1 =", value, "f1");
			return this;
		}

		public Criteria andF1NotEqualTo(String value) {
			addCriterion("F1 <>", value, "f1");
			return this;
		}

		public Criteria andF1GreaterThan(String value) {
			addCriterion("F1 >", value, "f1");
			return this;
		}

		public Criteria andF1GreaterThanOrEqualTo(String value) {
			addCriterion("F1 >=", value, "f1");
			return this;
		}

		public Criteria andF1LessThan(String value) {
			addCriterion("F1 <", value, "f1");
			return this;
		}

		public Criteria andF1LessThanOrEqualTo(String value) {
			addCriterion("F1 <=", value, "f1");
			return this;
		}

		public Criteria andF1Like(String value) {
			addCriterion("F1 like", value, "f1");
			return this;
		}

		public Criteria andF1NotLike(String value) {
			addCriterion("F1 not like", value, "f1");
			return this;
		}

		public Criteria andF1In(List values) {
			addCriterion("F1 in", values, "f1");
			return this;
		}

		public Criteria andF1NotIn(List values) {
			addCriterion("F1 not in", values, "f1");
			return this;
		}

		public Criteria andF1Between(String value1, String value2) {
			addCriterion("F1 between", value1, value2, "f1");
			return this;
		}

		public Criteria andF1NotBetween(String value1, String value2) {
			addCriterion("F1 not between", value1, value2, "f1");
			return this;
		}

		public Criteria andF2IsNull() {
			addCriterion("F2 is null");
			return this;
		}

		public Criteria andF2IsNotNull() {
			addCriterion("F2 is not null");
			return this;
		}

		public Criteria andF2EqualTo(String value) {
			addCriterion("F2 =", value, "f2");
			return this;
		}

		public Criteria andF2NotEqualTo(String value) {
			addCriterion("F2 <>", value, "f2");
			return this;
		}

		public Criteria andF2GreaterThan(String value) {
			addCriterion("F2 >", value, "f2");
			return this;
		}

		public Criteria andF2GreaterThanOrEqualTo(String value) {
			addCriterion("F2 >=", value, "f2");
			return this;
		}

		public Criteria andF2LessThan(String value) {
			addCriterion("F2 <", value, "f2");
			return this;
		}

		public Criteria andF2LessThanOrEqualTo(String value) {
			addCriterion("F2 <=", value, "f2");
			return this;
		}

		public Criteria andF2Like(String value) {
			addCriterion("F2 like", value, "f2");
			return this;
		}

		public Criteria andF2NotLike(String value) {
			addCriterion("F2 not like", value, "f2");
			return this;
		}

		public Criteria andF2In(List values) {
			addCriterion("F2 in", values, "f2");
			return this;
		}

		public Criteria andF2NotIn(List values) {
			addCriterion("F2 not in", values, "f2");
			return this;
		}

		public Criteria andF2Between(String value1, String value2) {
			addCriterion("F2 between", value1, value2, "f2");
			return this;
		}

		public Criteria andF2NotBetween(String value1, String value2) {
			addCriterion("F2 not between", value1, value2, "f2");
			return this;
		}

		public Criteria andF3IsNull() {
			addCriterion("F3 is null");
			return this;
		}

		public Criteria andF3IsNotNull() {
			addCriterion("F3 is not null");
			return this;
		}

		public Criteria andF3EqualTo(String value) {
			addCriterion("F3 =", value, "f3");
			return this;
		}

		public Criteria andF3NotEqualTo(String value) {
			addCriterion("F3 <>", value, "f3");
			return this;
		}

		public Criteria andF3GreaterThan(String value) {
			addCriterion("F3 >", value, "f3");
			return this;
		}

		public Criteria andF3GreaterThanOrEqualTo(String value) {
			addCriterion("F3 >=", value, "f3");
			return this;
		}

		public Criteria andF3LessThan(String value) {
			addCriterion("F3 <", value, "f3");
			return this;
		}

		public Criteria andF3LessThanOrEqualTo(String value) {
			addCriterion("F3 <=", value, "f3");
			return this;
		}

		public Criteria andF3Like(String value) {
			addCriterion("F3 like", value, "f3");
			return this;
		}

		public Criteria andF3NotLike(String value) {
			addCriterion("F3 not like", value, "f3");
			return this;
		}

		public Criteria andF3In(List values) {
			addCriterion("F3 in", values, "f3");
			return this;
		}

		public Criteria andF3NotIn(List values) {
			addCriterion("F3 not in", values, "f3");
			return this;
		}

		public Criteria andF3Between(String value1, String value2) {
			addCriterion("F3 between", value1, value2, "f3");
			return this;
		}

		public Criteria andF3NotBetween(String value1, String value2) {
			addCriterion("F3 not between", value1, value2, "f3");
			return this;
		}

		public Criteria andF4IsNull() {
			addCriterion("F4 is null");
			return this;
		}

		public Criteria andF4IsNotNull() {
			addCriterion("F4 is not null");
			return this;
		}

		public Criteria andF4EqualTo(String value) {
			addCriterion("F4 =", value, "f4");
			return this;
		}

		public Criteria andF4NotEqualTo(String value) {
			addCriterion("F4 <>", value, "f4");
			return this;
		}

		public Criteria andF4GreaterThan(String value) {
			addCriterion("F4 >", value, "f4");
			return this;
		}

		public Criteria andF4GreaterThanOrEqualTo(String value) {
			addCriterion("F4 >=", value, "f4");
			return this;
		}

		public Criteria andF4LessThan(String value) {
			addCriterion("F4 <", value, "f4");
			return this;
		}

		public Criteria andF4LessThanOrEqualTo(String value) {
			addCriterion("F4 <=", value, "f4");
			return this;
		}

		public Criteria andF4Like(String value) {
			addCriterion("F4 like", value, "f4");
			return this;
		}

		public Criteria andF4NotLike(String value) {
			addCriterion("F4 not like", value, "f4");
			return this;
		}

		public Criteria andF4In(List values) {
			addCriterion("F4 in", values, "f4");
			return this;
		}

		public Criteria andF4NotIn(List values) {
			addCriterion("F4 not in", values, "f4");
			return this;
		}

		public Criteria andF4Between(String value1, String value2) {
			addCriterion("F4 between", value1, value2, "f4");
			return this;
		}

		public Criteria andF4NotBetween(String value1, String value2) {
			addCriterion("F4 not between", value1, value2, "f4");
			return this;
		}

		public Criteria andF5IsNull() {
			addCriterion("F5 is null");
			return this;
		}

		public Criteria andF5IsNotNull() {
			addCriterion("F5 is not null");
			return this;
		}

		public Criteria andF5EqualTo(String value) {
			addCriterion("F5 =", value, "f5");
			return this;
		}

		public Criteria andF5NotEqualTo(String value) {
			addCriterion("F5 <>", value, "f5");
			return this;
		}

		public Criteria andF5GreaterThan(String value) {
			addCriterion("F5 >", value, "f5");
			return this;
		}

		public Criteria andF5GreaterThanOrEqualTo(String value) {
			addCriterion("F5 >=", value, "f5");
			return this;
		}

		public Criteria andF5LessThan(String value) {
			addCriterion("F5 <", value, "f5");
			return this;
		}

		public Criteria andF5LessThanOrEqualTo(String value) {
			addCriterion("F5 <=", value, "f5");
			return this;
		}

		public Criteria andF5Like(String value) {
			addCriterion("F5 like", value, "f5");
			return this;
		}

		public Criteria andF5NotLike(String value) {
			addCriterion("F5 not like", value, "f5");
			return this;
		}

		public Criteria andF5In(List values) {
			addCriterion("F5 in", values, "f5");
			return this;
		}

		public Criteria andF5NotIn(List values) {
			addCriterion("F5 not in", values, "f5");
			return this;
		}

		public Criteria andF5Between(String value1, String value2) {
			addCriterion("F5 between", value1, value2, "f5");
			return this;
		}

		public Criteria andF5NotBetween(String value1, String value2) {
			addCriterion("F5 not between", value1, value2, "f5");
			return this;
		}
	}
}