package com.pd.cwgl.model;

import java.util.Date;

public class StoSetting {

	public StoSetting() {
	}

	/**
	 * 创建新储位
	 * 
	 * @param cid
	 *            储位编号
	 * @param sid
	 *            储位简单编号
	 * @param pid
	 *            上级储位编号
	 * @param cwlx
	 *            储位类型
	 * @param xsjg
	 *            显示结构
	 * @param zrl
	 *            容量
	 * @param cjrid
	 *            创建人
	 * @param cjrxm
	 *            创建人姓名
	 * @param cjsj
	 *            创建时间
	 * @param cwsm
	 *            说明
	 * */
	public StoSetting(String cid, String sid, String pid, String cwlx,
			String xsjg, String zrl,String syl ,String cjrid, String cjrxm, Date cjsj,
			String cwsm) {
		super();
		this.cid = cid;
		this.sid = sid;
		this.pid = pid;
		this.cwlx = cwlx;
		this.xsjg = xsjg;
		this.zrl = zrl;
		this.syl = syl;
		this.cjrid = cjrid;
		this.cjrxm = cjrxm;
		this.cjsj = cjsj;
		this.sfky = "1";
		this.cwsm = cwsm;
	}
	
	/**
	 * 创建新储位
	 * 
	 * @param cid
	 *            储位编号
	 * @param sid
	 *            储位简单编号
	 * @param pid
	 *            上级储位编号
	 * @param cwlx
	 *            储位类型
	 * @param xsjg
	 *            显示结构
	 * @param zrl
	 *            容量
	 * @param cjrid
	 *            创建人
	 * @param cjrxm
	 *            创建人姓名
	 * @param cjsj
	 *            创建时间
	 * @param cwsm
	 *            说明
	 * */
	public StoSetting(String cid, String sid, String pid, String cwlx,
			String xsjg, String zrl,String syl ,String cjrid, String cjrxm, Date cjsj,String cflx,
			String cwsm) {
		super();
		this.cid = cid;
		this.sid = sid;
		this.pid = pid;
		this.cwlx = cwlx;
		this.xsjg = xsjg;
		this.zrl = zrl;
		this.syl = syl;
		this.cjrid = cjrid;
		this.cjrxm = cjrxm;
		this.cjsj = cjsj;
		this.sfky = "1";
		this.cflx=cflx;
		this.cwsm = cwsm;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String cid;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.SID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String sid;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.PID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String pid;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CWLX
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String cwlx;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.XSJG
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String xsjg;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.ZRL
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String zrl;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.SYL
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String syl;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CFGZ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String cfgz;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CFLX
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String cflx;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CJRID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String cjrid;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CJRXM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String cjrxm;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CJSJ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private Date cjsj;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.XGRID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String xgrid;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.XGRXM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String xgrxm;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.XGSJ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private Date xgsj;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.SFKY
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String sfky;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column STO_SETTING.CWSM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	private String cwsm;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CID
	 * 
	 * @return the value of STO_SETTING.CID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getCid() {
		return cid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CID
	 * 
	 * @param cid
	 *            the value for STO_SETTING.CID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCid(String cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.SID
	 * 
	 * @return the value of STO_SETTING.SID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getSid() {
		return sid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.SID
	 * 
	 * @param sid
	 *            the value for STO_SETTING.SID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setSid(String sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.PID
	 * 
	 * @return the value of STO_SETTING.PID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.PID
	 * 
	 * @param pid
	 *            the value for STO_SETTING.PID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CWLX
	 * 
	 * @return the value of STO_SETTING.CWLX
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getCwlx() {
		return cwlx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CWLX
	 * 
	 * @param cwlx
	 *            the value for STO_SETTING.CWLX
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCwlx(String cwlx) {
		this.cwlx = cwlx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.XSJG
	 * 
	 * @return the value of STO_SETTING.XSJG
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getXsjg() {
		return xsjg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.XSJG
	 * 
	 * @param xsjg
	 *            the value for STO_SETTING.XSJG
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setXsjg(String xsjg) {
		this.xsjg = xsjg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.ZRL
	 * 
	 * @return the value of STO_SETTING.ZRL
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getZrl() {
		return zrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.ZRL
	 * 
	 * @param zrl
	 *            the value for STO_SETTING.ZRL
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setZrl(String zrl) {
		this.zrl = zrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.SYL
	 * 
	 * @return the value of STO_SETTING.SYL
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getSyl() {
		return syl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.SYL
	 * 
	 * @param syl
	 *            the value for STO_SETTING.SYL
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setSyl(String syl) {
		this.syl = syl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CFGZ
	 * 
	 * @return the value of STO_SETTING.CFGZ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getCfgz() {
		return cfgz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CFGZ
	 * 
	 * @param cfgz
	 *            the value for STO_SETTING.CFGZ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCfgz(String cfgz) {
		this.cfgz = cfgz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CFLX
	 * 
	 * @return the value of STO_SETTING.CFLX
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getCflx() {
		return cflx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CFLX
	 * 
	 * @param cflx
	 *            the value for STO_SETTING.CFLX
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCflx(String cflx) {
		this.cflx = cflx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CJRID
	 * 
	 * @return the value of STO_SETTING.CJRID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getCjrid() {
		return cjrid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CJRID
	 * 
	 * @param cjrid
	 *            the value for STO_SETTING.CJRID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCjrid(String cjrid) {
		this.cjrid = cjrid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CJRXM
	 * 
	 * @return the value of STO_SETTING.CJRXM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getCjrxm() {
		return cjrxm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CJRXM
	 * 
	 * @param cjrxm
	 *            the value for STO_SETTING.CJRXM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCjrxm(String cjrxm) {
		this.cjrxm = cjrxm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CJSJ
	 * 
	 * @return the value of STO_SETTING.CJSJ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public Date getCjsj() {
		return cjsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CJSJ
	 * 
	 * @param cjsj
	 *            the value for STO_SETTING.CJSJ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.XGRID
	 * 
	 * @return the value of STO_SETTING.XGRID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getXgrid() {
		return xgrid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.XGRID
	 * 
	 * @param xgrid
	 *            the value for STO_SETTING.XGRID
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setXgrid(String xgrid) {
		this.xgrid = xgrid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.XGRXM
	 * 
	 * @return the value of STO_SETTING.XGRXM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getXgrxm() {
		return xgrxm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.XGRXM
	 * 
	 * @param xgrxm
	 *            the value for STO_SETTING.XGRXM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setXgrxm(String xgrxm) {
		this.xgrxm = xgrxm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.XGSJ
	 * 
	 * @return the value of STO_SETTING.XGSJ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public Date getXgsj() {
		return xgsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.XGSJ
	 * 
	 * @param xgsj
	 *            the value for STO_SETTING.XGSJ
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setXgsj(Date xgsj) {
		this.xgsj = xgsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.SFKY
	 * 
	 * @return the value of STO_SETTING.SFKY
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getSfky() {
		return sfky;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.SFKY
	 * 
	 * @param sfky
	 *            the value for STO_SETTING.SFKY
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setSfky(String sfky) {
		this.sfky = sfky;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column STO_SETTING.CWSM
	 * 
	 * @return the value of STO_SETTING.CWSM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public String getCwsm() {
		return cwsm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column STO_SETTING.CWSM
	 * 
	 * @param cwsm
	 *            the value for STO_SETTING.CWSM
	 * 
	 * @abatorgenerated Tue Aug 19 15:01:35 CST 2014
	 */
	public void setCwsm(String cwsm) {
		this.cwsm = cwsm;
	}

}