package com.pd.wjyw.dao.impl;

import com.pd.system.framework.PageToExample;
import com.pd.wjyw.model.YcTypePaper;
import com.pd.wjyw.model.YcTypePaperExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class YcTypePaperDAOImpl extends SqlMapClientDaoSupport implements YcTypePaperDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public YcTypePaperDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public void insert(YcTypePaper record) {
		getSqlMapClientTemplate().insert(
				"YC_TYPE_PAPER.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public int updateByPrimaryKey(YcTypePaper record) {
		int rows = getSqlMapClientTemplate().update(
				"YC_TYPE_PAPER.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public int updateByPrimaryKeySelective(YcTypePaper record) {
		int rows = getSqlMapClientTemplate().update(
				"YC_TYPE_PAPER.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public List selectByExample(YcTypePaperExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"YC_TYPE_PAPER.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public YcTypePaper selectByPrimaryKey(String id) {
		YcTypePaper key = new YcTypePaper();
		key.setId(id);
		YcTypePaper record = (YcTypePaper) getSqlMapClientTemplate()
				.queryForObject(
						"YC_TYPE_PAPER.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public int deleteByExample(YcTypePaperExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"YC_TYPE_PAPER.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public int deleteByPrimaryKey(String id) {
		YcTypePaper key = new YcTypePaper();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"YC_TYPE_PAPER.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public int countByExample(YcTypePaperExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"YC_TYPE_PAPER.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public int updateByExampleSelective(YcTypePaper record,
			YcTypePaperExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"YC_TYPE_PAPER.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	public int updateByExample(YcTypePaper record, YcTypePaperExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"YC_TYPE_PAPER.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table YC_TYPE_PAPER
	 * @abatorgenerated  Tue Aug 05 10:19:49 CST 2014
	 */
	private static class UpdateByExampleParms extends YcTypePaperExample {
		private Object record;

		public UpdateByExampleParms(Object record, YcTypePaperExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List selectByExampleToPage(PageToExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"YC_TYPE_PAPER.abatorgenerated_selectByExampleToPage", example);
		return list;
	}
}