package com.pd.arc.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ArcCallExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public ArcCallExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    protected ArcCallExample(ArcCallExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_CALL
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCallnumIsNull() {
            addCriterion("CALLNUM is null");
            return this;
        }

        public Criteria andCallnumIsNotNull() {
            addCriterion("CALLNUM is not null");
            return this;
        }

        public Criteria andCallnumEqualTo(String value) {
            addCriterion("CALLNUM =", value, "callnum");
            return this;
        }

        public Criteria andCallnumNotEqualTo(String value) {
            addCriterion("CALLNUM <>", value, "callnum");
            return this;
        }

        public Criteria andCallnumGreaterThan(String value) {
            addCriterion("CALLNUM >", value, "callnum");
            return this;
        }

        public Criteria andCallnumGreaterThanOrEqualTo(String value) {
            addCriterion("CALLNUM >=", value, "callnum");
            return this;
        }

        public Criteria andCallnumLessThan(String value) {
            addCriterion("CALLNUM <", value, "callnum");
            return this;
        }

        public Criteria andCallnumLessThanOrEqualTo(String value) {
            addCriterion("CALLNUM <=", value, "callnum");
            return this;
        }

        public Criteria andCallnumLike(String value) {
            addCriterion("CALLNUM like", value, "callnum");
            return this;
        }

        public Criteria andCallnumNotLike(String value) {
            addCriterion("CALLNUM not like", value, "callnum");
            return this;
        }

        public Criteria andCallnumIn(List values) {
            addCriterion("CALLNUM in", values, "callnum");
            return this;
        }

        public Criteria andCallnumNotIn(List values) {
            addCriterion("CALLNUM not in", values, "callnum");
            return this;
        }

        public Criteria andCallnumBetween(String value1, String value2) {
            addCriterion("CALLNUM between", value1, value2, "callnum");
            return this;
        }

        public Criteria andCallnumNotBetween(String value1, String value2) {
            addCriterion("CALLNUM not between", value1, value2, "callnum");
            return this;
        }
    }
}