package com.pd.swgl.dao;

import com.pd.swgl.model.ArcStorageOut;
import com.pd.swgl.model.ArcStorageOutExample;
import com.pd.system.framework.BaseDAO;

import java.util.List;

public interface ArcStorageOutDAO extends BaseDAO{
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    void insert(ArcStorageOut record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    int updateByPrimaryKey(ArcStorageOut record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    int updateByPrimaryKeySelective(ArcStorageOut record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    List selectByExample(ArcStorageOutExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    ArcStorageOut selectByPrimaryKey(String ckid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    int deleteByExample(ArcStorageOutExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    int deleteByPrimaryKey(String ckid);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    int countByExample(ArcStorageOutExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    int updateByExampleSelective(ArcStorageOut record, ArcStorageOutExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    int updateByExample(ArcStorageOut record, ArcStorageOutExample example);
    
	/**
     * 出库id序列
     * */
    String getCKSeq();
    
    /**
     * 出库批次序列
     * */
    String getCKPCSeq();
}