package com.pd.arc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import com.pd.system.framework.PageToExample;

public class ArcPicInfoExample extends PageToExample{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public ArcPicInfoExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    protected ArcPicInfoExample(ArcPicInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_PIC_INFO2
     *
     * @abatorgenerated Sat Aug 02 13:49:31 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andXtdabhIsNull() {
            addCriterion("XTDABH is null");
            return this;
        }

        public Criteria andXtdabhIsNotNull() {
            addCriterion("XTDABH is not null");
            return this;
        }

        public Criteria andXtdabhEqualTo(String value) {
            addCriterion("XTDABH =", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotEqualTo(String value) {
            addCriterion("XTDABH <>", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhGreaterThan(String value) {
            addCriterion("XTDABH >", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhGreaterThanOrEqualTo(String value) {
            addCriterion("XTDABH >=", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLessThan(String value) {
            addCriterion("XTDABH <", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLessThanOrEqualTo(String value) {
            addCriterion("XTDABH <=", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhLike(String value) {
            addCriterion("XTDABH like", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotLike(String value) {
            addCriterion("XTDABH not like", value, "xtdabh");
            return this;
        }

        public Criteria andXtdabhIn(List values) {
            addCriterion("XTDABH in", values, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotIn(List values) {
            addCriterion("XTDABH not in", values, "xtdabh");
            return this;
        }

        public Criteria andXtdabhBetween(String value1, String value2) {
            addCriterion("XTDABH between", value1, value2, "xtdabh");
            return this;
        }

        public Criteria andXtdabhNotBetween(String value1, String value2) {
            addCriterion("XTDABH not between", value1, value2, "xtdabh");
            return this;
        }

        public Criteria andPicFilenameIsNull() {
            addCriterion("PIC_FILENAME is null");
            return this;
        }

        public Criteria andPicFilenameIsNotNull() {
            addCriterion("PIC_FILENAME is not null");
            return this;
        }

        public Criteria andPicFilenameEqualTo(String value) {
            addCriterion("PIC_FILENAME =", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameNotEqualTo(String value) {
            addCriterion("PIC_FILENAME <>", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameGreaterThan(String value) {
            addCriterion("PIC_FILENAME >", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("PIC_FILENAME >=", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameLessThan(String value) {
            addCriterion("PIC_FILENAME <", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameLessThanOrEqualTo(String value) {
            addCriterion("PIC_FILENAME <=", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameLike(String value) {
            addCriterion("PIC_FILENAME like", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameNotLike(String value) {
            addCriterion("PIC_FILENAME not like", value, "picFilename");
            return this;
        }

        public Criteria andPicFilenameIn(List values) {
            addCriterion("PIC_FILENAME in", values, "picFilename");
            return this;
        }

        public Criteria andPicFilenameNotIn(List values) {
            addCriterion("PIC_FILENAME not in", values, "picFilename");
            return this;
        }

        public Criteria andPicFilenameBetween(String value1, String value2) {
            addCriterion("PIC_FILENAME between", value1, value2, "picFilename");
            return this;
        }

        public Criteria andPicFilenameNotBetween(String value1, String value2) {
            addCriterion("PIC_FILENAME not between", value1, value2, "picFilename");
            return this;
        }

        public Criteria andYwlxIsNull() {
            addCriterion("YWLX is null");
            return this;
        }

        public Criteria andYwlxIsNotNull() {
            addCriterion("YWLX is not null");
            return this;
        }

        public Criteria andYwlxEqualTo(String value) {
            addCriterion("YWLX =", value, "ywlx");
            return this;
        }

        public Criteria andYwlxNotEqualTo(String value) {
            addCriterion("YWLX <>", value, "ywlx");
            return this;
        }

        public Criteria andYwlxGreaterThan(String value) {
            addCriterion("YWLX >", value, "ywlx");
            return this;
        }

        public Criteria andYwlxGreaterThanOrEqualTo(String value) {
            addCriterion("YWLX >=", value, "ywlx");
            return this;
        }

        public Criteria andYwlxLessThan(String value) {
            addCriterion("YWLX <", value, "ywlx");
            return this;
        }

        public Criteria andYwlxLessThanOrEqualTo(String value) {
            addCriterion("YWLX <=", value, "ywlx");
            return this;
        }

        public Criteria andYwlxLike(String value) {
            addCriterion("YWLX like", value, "ywlx");
            return this;
        }

        public Criteria andYwlxNotLike(String value) {
            addCriterion("YWLX not like", value, "ywlx");
            return this;
        }

        public Criteria andYwlxIn(List values) {
            addCriterion("YWLX in", values, "ywlx");
            return this;
        }

        public Criteria andYwlxNotIn(List values) {
            addCriterion("YWLX not in", values, "ywlx");
            return this;
        }

        public Criteria andYwlxBetween(String value1, String value2) {
            addCriterion("YWLX between", value1, value2, "ywlx");
            return this;
        }

        public Criteria andYwlxNotBetween(String value1, String value2) {
            addCriterion("YWLX not between", value1, value2, "ywlx");
            return this;
        }

        public Criteria andSntmcIsNull() {
            addCriterion("SNTMC is null");
            return this;
        }

        public Criteria andSntmcIsNotNull() {
            addCriterion("SNTMC is not null");
            return this;
        }

        public Criteria andSntmcEqualTo(String value) {
            addCriterion("SNTMC =", value, "sntmc");
            return this;
        }

        public Criteria andSntmcNotEqualTo(String value) {
            addCriterion("SNTMC <>", value, "sntmc");
            return this;
        }

        public Criteria andSntmcGreaterThan(String value) {
            addCriterion("SNTMC >", value, "sntmc");
            return this;
        }

        public Criteria andSntmcGreaterThanOrEqualTo(String value) {
            addCriterion("SNTMC >=", value, "sntmc");
            return this;
        }

        public Criteria andSntmcLessThan(String value) {
            addCriterion("SNTMC <", value, "sntmc");
            return this;
        }

        public Criteria andSntmcLessThanOrEqualTo(String value) {
            addCriterion("SNTMC <=", value, "sntmc");
            return this;
        }

        public Criteria andSntmcLike(String value) {
            addCriterion("SNTMC like", value, "sntmc");
            return this;
        }

        public Criteria andSntmcNotLike(String value) {
            addCriterion("SNTMC not like", value, "sntmc");
            return this;
        }

        public Criteria andSntmcIn(List values) {
            addCriterion("SNTMC in", values, "sntmc");
            return this;
        }

        public Criteria andSntmcNotIn(List values) {
            addCriterion("SNTMC not in", values, "sntmc");
            return this;
        }

        public Criteria andSntmcBetween(String value1, String value2) {
            addCriterion("SNTMC between", value1, value2, "sntmc");
            return this;
        }

        public Criteria andSntmcNotBetween(String value1, String value2) {
            addCriterion("SNTMC not between", value1, value2, "sntmc");
            return this;
        }

        public Criteria andPaperIdIsNull() {
            addCriterion("PAPER_ID is null");
            return this;
        }

        public Criteria andPaperIdIsNotNull() {
            addCriterion("PAPER_ID is not null");
            return this;
        }

        public Criteria andPaperIdEqualTo(String value) {
            addCriterion("PAPER_ID =", value, "paperId");
            return this;
        }

        public Criteria andPaperIdNotEqualTo(String value) {
            addCriterion("PAPER_ID <>", value, "paperId");
            return this;
        }

        public Criteria andPaperIdGreaterThan(String value) {
            addCriterion("PAPER_ID >", value, "paperId");
            return this;
        }

        public Criteria andPaperIdGreaterThanOrEqualTo(String value) {
            addCriterion("PAPER_ID >=", value, "paperId");
            return this;
        }

        public Criteria andPaperIdLessThan(String value) {
            addCriterion("PAPER_ID <", value, "paperId");
            return this;
        }

        public Criteria andPaperIdLessThanOrEqualTo(String value) {
            addCriterion("PAPER_ID <=", value, "paperId");
            return this;
        }

        public Criteria andPaperIdLike(String value) {
            addCriterion("PAPER_ID like", value, "paperId");
            return this;
        }

        public Criteria andPaperIdNotLike(String value) {
            addCriterion("PAPER_ID not like", value, "paperId");
            return this;
        }

        public Criteria andPaperIdIn(List values) {
            addCriterion("PAPER_ID in", values, "paperId");
            return this;
        }

        public Criteria andPaperIdNotIn(List values) {
            addCriterion("PAPER_ID not in", values, "paperId");
            return this;
        }

        public Criteria andPaperIdBetween(String value1, String value2) {
            addCriterion("PAPER_ID between", value1, value2, "paperId");
            return this;
        }

        public Criteria andPaperIdNotBetween(String value1, String value2) {
            addCriterion("PAPER_ID not between", value1, value2, "paperId");
            return this;
        }

        public Criteria andSmrmcIsNull() {
            addCriterion("SMRMC is null");
            return this;
        }

        public Criteria andSmrmcIsNotNull() {
            addCriterion("SMRMC is not null");
            return this;
        }

        public Criteria andSmrmcEqualTo(String value) {
            addCriterion("SMRMC =", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcNotEqualTo(String value) {
            addCriterion("SMRMC <>", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcGreaterThan(String value) {
            addCriterion("SMRMC >", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcGreaterThanOrEqualTo(String value) {
            addCriterion("SMRMC >=", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcLessThan(String value) {
            addCriterion("SMRMC <", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcLessThanOrEqualTo(String value) {
            addCriterion("SMRMC <=", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcLike(String value) {
            addCriterion("SMRMC like", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcNotLike(String value) {
            addCriterion("SMRMC not like", value, "smrmc");
            return this;
        }

        public Criteria andSmrmcIn(List values) {
            addCriterion("SMRMC in", values, "smrmc");
            return this;
        }

        public Criteria andSmrmcNotIn(List values) {
            addCriterion("SMRMC not in", values, "smrmc");
            return this;
        }

        public Criteria andSmrmcBetween(String value1, String value2) {
            addCriterion("SMRMC between", value1, value2, "smrmc");
            return this;
        }

        public Criteria andSmrmcNotBetween(String value1, String value2) {
            addCriterion("SMRMC not between", value1, value2, "smrmc");
            return this;
        }

        public Criteria andSmrIsNull() {
            addCriterion("SMR is null");
            return this;
        }

        public Criteria andSmrIsNotNull() {
            addCriterion("SMR is not null");
            return this;
        }

        public Criteria andSmrEqualTo(String value) {
            addCriterion("SMR =", value, "smr");
            return this;
        }

        public Criteria andSmrNotEqualTo(String value) {
            addCriterion("SMR <>", value, "smr");
            return this;
        }

        public Criteria andSmrGreaterThan(String value) {
            addCriterion("SMR >", value, "smr");
            return this;
        }

        public Criteria andSmrGreaterThanOrEqualTo(String value) {
            addCriterion("SMR >=", value, "smr");
            return this;
        }

        public Criteria andSmrLessThan(String value) {
            addCriterion("SMR <", value, "smr");
            return this;
        }

        public Criteria andSmrLessThanOrEqualTo(String value) {
            addCriterion("SMR <=", value, "smr");
            return this;
        }

        public Criteria andSmrLike(String value) {
            addCriterion("SMR like", value, "smr");
            return this;
        }

        public Criteria andSmrNotLike(String value) {
            addCriterion("SMR not like", value, "smr");
            return this;
        }

        public Criteria andSmrIn(List values) {
            addCriterion("SMR in", values, "smr");
            return this;
        }

        public Criteria andSmrNotIn(List values) {
            addCriterion("SMR not in", values, "smr");
            return this;
        }

        public Criteria andSmrBetween(String value1, String value2) {
            addCriterion("SMR between", value1, value2, "smr");
            return this;
        }

        public Criteria andSmrNotBetween(String value1, String value2) {
            addCriterion("SMR not between", value1, value2, "smr");
            return this;
        }

        public Criteria andSmsjIsNull() {
            addCriterion("SMSJ is null");
            return this;
        }

        public Criteria andSmsjIsNotNull() {
            addCriterion("SMSJ is not null");
            return this;
        }

        public Criteria andSmsjEqualTo(Date value) {
            addCriterionForJDBCDate("SMSJ =", value, "smsj");
            return this;
        }

        public Criteria andSmsjNotEqualTo(Date value) {
            addCriterionForJDBCDate("SMSJ <>", value, "smsj");
            return this;
        }

        public Criteria andSmsjGreaterThan(Date value) {
            addCriterionForJDBCDate("SMSJ >", value, "smsj");
            return this;
        }

        public Criteria andSmsjGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SMSJ >=", value, "smsj");
            return this;
        }

        public Criteria andSmsjLessThan(Date value) {
            addCriterionForJDBCDate("SMSJ <", value, "smsj");
            return this;
        }

        public Criteria andSmsjLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SMSJ <=", value, "smsj");
            return this;
        }

        public Criteria andSmsjIn(List values) {
            addCriterionForJDBCDate("SMSJ in", values, "smsj");
            return this;
        }

        public Criteria andSmsjNotIn(List values) {
            addCriterionForJDBCDate("SMSJ not in", values, "smsj");
            return this;
        }

        public Criteria andSmsjBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SMSJ between", value1, value2, "smsj");
            return this;
        }

        public Criteria andSmsjNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SMSJ not between", value1, value2, "smsj");
            return this;
        }

        public Criteria andSmcsIsNull() {
            addCriterion("SMCS is null");
            return this;
        }

        public Criteria andSmcsIsNotNull() {
            addCriterion("SMCS is not null");
            return this;
        }

        public Criteria andSmcsEqualTo(String value) {
            addCriterion("SMCS =", value, "smcs");
            return this;
        }

        public Criteria andSmcsNotEqualTo(String value) {
            addCriterion("SMCS <>", value, "smcs");
            return this;
        }

        public Criteria andSmcsGreaterThan(String value) {
            addCriterion("SMCS >", value, "smcs");
            return this;
        }

        public Criteria andSmcsGreaterThanOrEqualTo(String value) {
            addCriterion("SMCS >=", value, "smcs");
            return this;
        }

        public Criteria andSmcsLessThan(String value) {
            addCriterion("SMCS <", value, "smcs");
            return this;
        }

        public Criteria andSmcsLessThanOrEqualTo(String value) {
            addCriterion("SMCS <=", value, "smcs");
            return this;
        }

        public Criteria andSmcsLike(String value) {
            addCriterion("SMCS like", value, "smcs");
            return this;
        }

        public Criteria andSmcsNotLike(String value) {
            addCriterion("SMCS not like", value, "smcs");
            return this;
        }

        public Criteria andSmcsIn(List values) {
            addCriterion("SMCS in", values, "smcs");
            return this;
        }

        public Criteria andSmcsNotIn(List values) {
            addCriterion("SMCS not in", values, "smcs");
            return this;
        }

        public Criteria andSmcsBetween(String value1, String value2) {
            addCriterion("SMCS between", value1, value2, "smcs");
            return this;
        }

        public Criteria andSmcsNotBetween(String value1, String value2) {
            addCriterion("SMCS not between", value1, value2, "smcs");
            return this;
        }

        public Criteria andTpljIsNull() {
            addCriterion("TPLJ is null");
            return this;
        }

        public Criteria andTpljIsNotNull() {
            addCriterion("TPLJ is not null");
            return this;
        }

        public Criteria andTpljEqualTo(String value) {
            addCriterion("TPLJ =", value, "tplj");
            return this;
        }

        public Criteria andTpljNotEqualTo(String value) {
            addCriterion("TPLJ <>", value, "tplj");
            return this;
        }

        public Criteria andTpljGreaterThan(String value) {
            addCriterion("TPLJ >", value, "tplj");
            return this;
        }

        public Criteria andTpljGreaterThanOrEqualTo(String value) {
            addCriterion("TPLJ >=", value, "tplj");
            return this;
        }

        public Criteria andTpljLessThan(String value) {
            addCriterion("TPLJ <", value, "tplj");
            return this;
        }

        public Criteria andTpljLessThanOrEqualTo(String value) {
            addCriterion("TPLJ <=", value, "tplj");
            return this;
        }

        public Criteria andTpljLike(String value) {
            addCriterion("TPLJ like", value, "tplj");
            return this;
        }

        public Criteria andTpljNotLike(String value) {
            addCriterion("TPLJ not like", value, "tplj");
            return this;
        }

        public Criteria andTpljIn(List values) {
            addCriterion("TPLJ in", values, "tplj");
            return this;
        }

        public Criteria andTpljNotIn(List values) {
            addCriterion("TPLJ not in", values, "tplj");
            return this;
        }

        public Criteria andTpljBetween(String value1, String value2) {
            addCriterion("TPLJ between", value1, value2, "tplj");
            return this;
        }

        public Criteria andTpljNotBetween(String value1, String value2) {
            addCriterion("TPLJ not between", value1, value2, "tplj");
            return this;
        }

        public Criteria andSntljIsNull() {
            addCriterion("SNTLJ is null");
            return this;
        }

        public Criteria andSntljIsNotNull() {
            addCriterion("SNTLJ is not null");
            return this;
        }

        public Criteria andSntljEqualTo(String value) {
            addCriterion("SNTLJ =", value, "sntlj");
            return this;
        }

        public Criteria andSntljNotEqualTo(String value) {
            addCriterion("SNTLJ <>", value, "sntlj");
            return this;
        }

        public Criteria andSntljGreaterThan(String value) {
            addCriterion("SNTLJ >", value, "sntlj");
            return this;
        }

        public Criteria andSntljGreaterThanOrEqualTo(String value) {
            addCriterion("SNTLJ >=", value, "sntlj");
            return this;
        }

        public Criteria andSntljLessThan(String value) {
            addCriterion("SNTLJ <", value, "sntlj");
            return this;
        }

        public Criteria andSntljLessThanOrEqualTo(String value) {
            addCriterion("SNTLJ <=", value, "sntlj");
            return this;
        }

        public Criteria andSntljLike(String value) {
            addCriterion("SNTLJ like", value, "sntlj");
            return this;
        }

        public Criteria andSntljNotLike(String value) {
            addCriterion("SNTLJ not like", value, "sntlj");
            return this;
        }

        public Criteria andSntljIn(List values) {
            addCriterion("SNTLJ in", values, "sntlj");
            return this;
        }

        public Criteria andSntljNotIn(List values) {
            addCriterion("SNTLJ not in", values, "sntlj");
            return this;
        }

        public Criteria andSntljBetween(String value1, String value2) {
            addCriterion("SNTLJ between", value1, value2, "sntlj");
            return this;
        }

        public Criteria andSntljNotBetween(String value1, String value2) {
            addCriterion("SNTLJ not between", value1, value2, "sntlj");
            return this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return this;
        }

        public Criteria andBzIn(List values) {
            addCriterion("BZ in", values, "bz");
            return this;
        }

        public Criteria andBzNotIn(List values) {
            addCriterion("BZ not in", values, "bz");
            return this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return this;
        }

        public Criteria andYtpIsNull() {
            addCriterion("YTP is null");
            return this;
        }

        public Criteria andYtpIsNotNull() {
            addCriterion("YTP is not null");
            return this;
        }

        public Criteria andYtpEqualTo(String value) {
            addCriterion("YTP =", value, "ytp");
            return this;
        }

        public Criteria andYtpNotEqualTo(String value) {
            addCriterion("YTP <>", value, "ytp");
            return this;
        }

        public Criteria andYtpGreaterThan(String value) {
            addCriterion("YTP >", value, "ytp");
            return this;
        }

        public Criteria andYtpGreaterThanOrEqualTo(String value) {
            addCriterion("YTP >=", value, "ytp");
            return this;
        }

        public Criteria andYtpLessThan(String value) {
            addCriterion("YTP <", value, "ytp");
            return this;
        }

        public Criteria andYtpLessThanOrEqualTo(String value) {
            addCriterion("YTP <=", value, "ytp");
            return this;
        }

        public Criteria andYtpLike(String value) {
            addCriterion("YTP like", value, "ytp");
            return this;
        }

        public Criteria andYtpNotLike(String value) {
            addCriterion("YTP not like", value, "ytp");
            return this;
        }

        public Criteria andYtpIn(List values) {
            addCriterion("YTP in", values, "ytp");
            return this;
        }

        public Criteria andYtpNotIn(List values) {
            addCriterion("YTP not in", values, "ytp");
            return this;
        }

        public Criteria andYtpBetween(String value1, String value2) {
            addCriterion("YTP between", value1, value2, "ytp");
            return this;
        }

        public Criteria andYtpNotBetween(String value1, String value2) {
            addCriterion("YTP not between", value1, value2, "ytp");
            return this;
        }

        public Criteria andTplxIsNull() {
            addCriterion("TPLX is null");
            return this;
        }

        public Criteria andTplxIsNotNull() {
            addCriterion("TPLX is not null");
            return this;
        }

        public Criteria andTplxEqualTo(String value) {
            addCriterion("TPLX =", value, "tplx");
            return this;
        }

        public Criteria andTplxNotEqualTo(String value) {
            addCriterion("TPLX <>", value, "tplx");
            return this;
        }

        public Criteria andTplxGreaterThan(String value) {
            addCriterion("TPLX >", value, "tplx");
            return this;
        }

        public Criteria andTplxGreaterThanOrEqualTo(String value) {
            addCriterion("TPLX >=", value, "tplx");
            return this;
        }

        public Criteria andTplxLessThan(String value) {
            addCriterion("TPLX <", value, "tplx");
            return this;
        }

        public Criteria andTplxLessThanOrEqualTo(String value) {
            addCriterion("TPLX <=", value, "tplx");
            return this;
        }

        public Criteria andTplxLike(String value) {
            addCriterion("TPLX like", value, "tplx");
            return this;
        }

        public Criteria andTplxNotLike(String value) {
            addCriterion("TPLX not like", value, "tplx");
            return this;
        }

        public Criteria andTplxIn(List values) {
            addCriterion("TPLX in", values, "tplx");
            return this;
        }

        public Criteria andTplxNotIn(List values) {
            addCriterion("TPLX not in", values, "tplx");
            return this;
        }

        public Criteria andTplxBetween(String value1, String value2) {
            addCriterion("TPLX between", value1, value2, "tplx");
            return this;
        }

        public Criteria andTplxNotBetween(String value1, String value2) {
            addCriterion("TPLX not between", value1, value2, "tplx");
            return this;
        }

        public Criteria andSfcsIsNull() {
            addCriterion("SFCS is null");
            return this;
        }

        public Criteria andSfcsIsNotNull() {
            addCriterion("SFCS is not null");
            return this;
        }

        public Criteria andSfcsEqualTo(String value) {
            addCriterion("SFCS =", value, "sfcs");
            return this;
        }

        public Criteria andSfcsNotEqualTo(String value) {
            addCriterion("SFCS <>", value, "sfcs");
            return this;
        }

        public Criteria andSfcsGreaterThan(String value) {
            addCriterion("SFCS >", value, "sfcs");
            return this;
        }

        public Criteria andSfcsGreaterThanOrEqualTo(String value) {
            addCriterion("SFCS >=", value, "sfcs");
            return this;
        }

        public Criteria andSfcsLessThan(String value) {
            addCriterion("SFCS <", value, "sfcs");
            return this;
        }

        public Criteria andSfcsLessThanOrEqualTo(String value) {
            addCriterion("SFCS <=", value, "sfcs");
            return this;
        }

        public Criteria andSfcsLike(String value) {
            addCriterion("SFCS like", value, "sfcs");
            return this;
        }

        public Criteria andSfcsNotLike(String value) {
            addCriterion("SFCS not like", value, "sfcs");
            return this;
        }

        public Criteria andSfcsIn(List values) {
            addCriterion("SFCS in", values, "sfcs");
            return this;
        }

        public Criteria andSfcsNotIn(List values) {
            addCriterion("SFCS not in", values, "sfcs");
            return this;
        }

        public Criteria andSfcsBetween(String value1, String value2) {
            addCriterion("SFCS between", value1, value2, "sfcs");
            return this;
        }

        public Criteria andSfcsNotBetween(String value1, String value2) {
            addCriterion("SFCS not between", value1, value2, "sfcs");
            return this;
        }
    }
}