package com.pd.swgl.dao;

import com.pd.swgl.model.ArcStorageOut;
import com.pd.swgl.model.ArcStorageOutExample;
import com.pd.system.framework.PageToExample;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArcStorageOutDAOImpl extends SqlMapClientDaoSupport implements ArcStorageOutDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public ArcStorageOutDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public void insert(ArcStorageOut record) {
        getSqlMapClientTemplate().insert("ARC_STORAGE_OUT.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public int updateByPrimaryKey(ArcStorageOut record) {
        int rows = getSqlMapClientTemplate().update("ARC_STORAGE_OUT.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public int updateByPrimaryKeySelective(ArcStorageOut record) {
        int rows = getSqlMapClientTemplate().update("ARC_STORAGE_OUT.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public List selectByExample(ArcStorageOutExample example) {
        List list = getSqlMapClientTemplate().queryForList("ARC_STORAGE_OUT.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public ArcStorageOut selectByPrimaryKey(String ckid) {
        ArcStorageOut key = new ArcStorageOut();
        key.setCkid(ckid);
        ArcStorageOut record = (ArcStorageOut) getSqlMapClientTemplate().queryForObject("ARC_STORAGE_OUT.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public int deleteByExample(ArcStorageOutExample example) {
        int rows = getSqlMapClientTemplate().delete("ARC_STORAGE_OUT.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public int deleteByPrimaryKey(String ckid) {
        ArcStorageOut key = new ArcStorageOut();
        key.setCkid(ckid);
        int rows = getSqlMapClientTemplate().delete("ARC_STORAGE_OUT.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public int countByExample(ArcStorageOutExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ARC_STORAGE_OUT.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public int updateByExampleSelective(ArcStorageOut record, ArcStorageOutExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_STORAGE_OUT.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    public int updateByExample(ArcStorageOut record, ArcStorageOutExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ARC_STORAGE_OUT.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table ARC_STORAGE_OUT
     *
     * @abatorgenerated Thu Aug 07 15:36:09 CST 2014
     */
    private static class UpdateByExampleParms extends ArcStorageOutExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArcStorageOutExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public String getCKSeq() {
		return getSqlMapClientTemplate().queryForObject("ARC_STORAGE_OUT.getCKSeq").toString();
	}

	@Override
	public String getCKPCSeq() {
		return getSqlMapClientTemplate().queryForObject("ARC_STORAGE_OUT.getCKPCSeq").toString();
	}

	@Override
	public List selectByExampleToPage(PageToExample example) {
		return getSqlMapClientTemplate().queryForList("ARC_STORAGE_OUT."+SELECT_EXAMPLE_TO_PAGE,example);
	}
}