package com.pd.arc.model;

import java.util.Date;

import com.pd.right.model.SuperUser;

public class ArcCombInfo {

	public ArcCombInfo() {
	}

	public ArcCombInfo(ArcBaseInfo info, ArcBaseInfo main, SuperUser user,
			Date date) {
		super();
		this.id = info.getId();
		this.dazt = info.getDazt();
		this.xh = info.getXh();
		this.ywlx = info.getYwlx();
		this.lsh = info.getLsh();
		this.hpzl = info.getHpzl();
		this.hphm = info.getHphm();
		this.clsbdh = info.getClsbdh();
		this.fprq = info.getFprq();
		this.syr = info.getSyr();
		this.sfzmhm = info.getSfzmhm();
		this.zsxxdz = info.getZsxxdz();
		this.clpp1 = info.getClpp1();
		this.clxh = info.getClxh();
		this.cllx = info.getCllx();
		this.csys = info.getCsys();
		this.zzg = info.getZzg();
		this.fdjh = info.getFdjh();
		this.bz = info.getBz();
		this.dalx = info.getDalx();
		this.gdr = info.getGdr();
		this.gdsj = info.getGdsj();
		this.dabh = info.getDabh();
		this.cwbh = info.getCwbh();
		this.xzqh = info.getXzqh();
		this.deptcode = info.getDeptcode();
		this.hdbj = info.getHdbj();
		this.xtdabh = info.getXtdabh();
		this.zxtdabh = main.getXtdabh();
		this.clpp2 = info.getClpp2();
		this.gdrmc = info.getGdrmc();
		this.zzcmc = info.getZzcmc();
		this.sfzmmc = info.getSfzmmc();
		this.fzjg = info.getFzjg();
		this.djrq = info.getDjrq();
		this.sqrq = info.getSqrq();
		this.cjr = info.getCjr();
		this.cjrmc = info.getCjrmc();
		this.cjsj = info.getCjsj();
		this.shr = info.getShr();
		this.shrmc = info.getShrmc();
		this.shsj = info.getShsj();
		this.kfbj = info.getKfbj();
		this.bjrq = info.getBjrq();
		this.pc = info.getPc();
		this.sfbh = info.getSfbh();
		this.cwsj = info.getCwsj();
		this.cwyx = "0";
		this.hdr = user.getUserCode();
		this.hdrxm = user.getUserName();
		this.hdsj = date;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.ID
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.DAZT
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String dazt;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.XH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String xh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.YWLX
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String ywlx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.LSH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String lsh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.HPZL
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String hpzl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.HPHM
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String hphm;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CLSBDH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String clsbdh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.FPRQ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date fprq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SYR
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String syr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SFZMHM
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String sfzmhm;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.ZSXXDZ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String zsxxdz;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CLPP1
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String clpp1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CLXH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String clxh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CLLX
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String cllx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CSYS
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String csys;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.ZZG
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String zzg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.FDJH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String fdjh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.BZ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String bz;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.DALX
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String dalx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.GDR
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String gdr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.GDSJ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date gdsj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.DABH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String dabh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CWBH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String cwbh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.XZQH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String xzqh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.DEPTCODE
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String deptcode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.HDBJ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String hdbj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.XTDABH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String xtdabh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.ZXTDABH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String zxtdabh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CLPP2
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String clpp2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.GDRMC
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String gdrmc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.ZZCMC
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String zzcmc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SFZMMC
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String sfzmmc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.FZJG
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String fzjg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.DJRQ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date djrq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SQRQ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date sqrq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CJR
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String cjr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CJRMC
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String cjrmc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CJSJ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date cjsj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SHR
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String shr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SHRMC
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String shrmc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SHSJ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date shsj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.KFBJ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String kfbj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.BJRQ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date bjrq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.PC
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String pc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.SFBH
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String sfbh;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CWSJ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String cwsj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.CWYX
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String cwyx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.HDR
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String hdr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.HDRXM
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private String hdrxm;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column ARC_COMB_INFO.HDSJ
	 * 
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	private Date hdsj;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.ID
	 * 
	 * @return the value of ARC_COMB_INFO.ID
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.ID
	 * 
	 * @param id
	 *            the value for ARC_COMB_INFO.ID
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.DAZT
	 * 
	 * @return the value of ARC_COMB_INFO.DAZT
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getDazt() {
		return dazt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.DAZT
	 * 
	 * @param dazt
	 *            the value for ARC_COMB_INFO.DAZT
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setDazt(String dazt) {
		this.dazt = dazt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.XH
	 * 
	 * @return the value of ARC_COMB_INFO.XH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getXh() {
		return xh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.XH
	 * 
	 * @param xh
	 *            the value for ARC_COMB_INFO.XH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setXh(String xh) {
		this.xh = xh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.YWLX
	 * 
	 * @return the value of ARC_COMB_INFO.YWLX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getYwlx() {
		return ywlx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.YWLX
	 * 
	 * @param ywlx
	 *            the value for ARC_COMB_INFO.YWLX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setYwlx(String ywlx) {
		this.ywlx = ywlx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.LSH
	 * 
	 * @return the value of ARC_COMB_INFO.LSH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getLsh() {
		return lsh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.LSH
	 * 
	 * @param lsh
	 *            the value for ARC_COMB_INFO.LSH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setLsh(String lsh) {
		this.lsh = lsh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.HPZL
	 * 
	 * @return the value of ARC_COMB_INFO.HPZL
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getHpzl() {
		return hpzl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.HPZL
	 * 
	 * @param hpzl
	 *            the value for ARC_COMB_INFO.HPZL
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setHpzl(String hpzl) {
		this.hpzl = hpzl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.HPHM
	 * 
	 * @return the value of ARC_COMB_INFO.HPHM
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getHphm() {
		return hphm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.HPHM
	 * 
	 * @param hphm
	 *            the value for ARC_COMB_INFO.HPHM
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setHphm(String hphm) {
		this.hphm = hphm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CLSBDH
	 * 
	 * @return the value of ARC_COMB_INFO.CLSBDH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getClsbdh() {
		return clsbdh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CLSBDH
	 * 
	 * @param clsbdh
	 *            the value for ARC_COMB_INFO.CLSBDH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setClsbdh(String clsbdh) {
		this.clsbdh = clsbdh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.FPRQ
	 * 
	 * @return the value of ARC_COMB_INFO.FPRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getFprq() {
		return fprq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.FPRQ
	 * 
	 * @param fprq
	 *            the value for ARC_COMB_INFO.FPRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setFprq(Date fprq) {
		this.fprq = fprq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SYR
	 * 
	 * @return the value of ARC_COMB_INFO.SYR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getSyr() {
		return syr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SYR
	 * 
	 * @param syr
	 *            the value for ARC_COMB_INFO.SYR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setSyr(String syr) {
		this.syr = syr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SFZMHM
	 * 
	 * @return the value of ARC_COMB_INFO.SFZMHM
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getSfzmhm() {
		return sfzmhm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SFZMHM
	 * 
	 * @param sfzmhm
	 *            the value for ARC_COMB_INFO.SFZMHM
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setSfzmhm(String sfzmhm) {
		this.sfzmhm = sfzmhm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.ZSXXDZ
	 * 
	 * @return the value of ARC_COMB_INFO.ZSXXDZ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getZsxxdz() {
		return zsxxdz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.ZSXXDZ
	 * 
	 * @param zsxxdz
	 *            the value for ARC_COMB_INFO.ZSXXDZ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setZsxxdz(String zsxxdz) {
		this.zsxxdz = zsxxdz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CLPP1
	 * 
	 * @return the value of ARC_COMB_INFO.CLPP1
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getClpp1() {
		return clpp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CLPP1
	 * 
	 * @param clpp1
	 *            the value for ARC_COMB_INFO.CLPP1
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setClpp1(String clpp1) {
		this.clpp1 = clpp1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CLXH
	 * 
	 * @return the value of ARC_COMB_INFO.CLXH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getClxh() {
		return clxh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CLXH
	 * 
	 * @param clxh
	 *            the value for ARC_COMB_INFO.CLXH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setClxh(String clxh) {
		this.clxh = clxh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CLLX
	 * 
	 * @return the value of ARC_COMB_INFO.CLLX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getCllx() {
		return cllx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CLLX
	 * 
	 * @param cllx
	 *            the value for ARC_COMB_INFO.CLLX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCllx(String cllx) {
		this.cllx = cllx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CSYS
	 * 
	 * @return the value of ARC_COMB_INFO.CSYS
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getCsys() {
		return csys;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CSYS
	 * 
	 * @param csys
	 *            the value for ARC_COMB_INFO.CSYS
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCsys(String csys) {
		this.csys = csys;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.ZZG
	 * 
	 * @return the value of ARC_COMB_INFO.ZZG
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getZzg() {
		return zzg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.ZZG
	 * 
	 * @param zzg
	 *            the value for ARC_COMB_INFO.ZZG
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setZzg(String zzg) {
		this.zzg = zzg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.FDJH
	 * 
	 * @return the value of ARC_COMB_INFO.FDJH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getFdjh() {
		return fdjh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.FDJH
	 * 
	 * @param fdjh
	 *            the value for ARC_COMB_INFO.FDJH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setFdjh(String fdjh) {
		this.fdjh = fdjh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.BZ
	 * 
	 * @return the value of ARC_COMB_INFO.BZ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getBz() {
		return bz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.BZ
	 * 
	 * @param bz
	 *            the value for ARC_COMB_INFO.BZ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setBz(String bz) {
		this.bz = bz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.DALX
	 * 
	 * @return the value of ARC_COMB_INFO.DALX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getDalx() {
		return dalx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.DALX
	 * 
	 * @param dalx
	 *            the value for ARC_COMB_INFO.DALX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setDalx(String dalx) {
		this.dalx = dalx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.GDR
	 * 
	 * @return the value of ARC_COMB_INFO.GDR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getGdr() {
		return gdr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.GDR
	 * 
	 * @param gdr
	 *            the value for ARC_COMB_INFO.GDR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setGdr(String gdr) {
		this.gdr = gdr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.GDSJ
	 * 
	 * @return the value of ARC_COMB_INFO.GDSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getGdsj() {
		return gdsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.GDSJ
	 * 
	 * @param gdsj
	 *            the value for ARC_COMB_INFO.GDSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setGdsj(Date gdsj) {
		this.gdsj = gdsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.DABH
	 * 
	 * @return the value of ARC_COMB_INFO.DABH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getDabh() {
		return dabh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.DABH
	 * 
	 * @param dabh
	 *            the value for ARC_COMB_INFO.DABH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setDabh(String dabh) {
		this.dabh = dabh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CWBH
	 * 
	 * @return the value of ARC_COMB_INFO.CWBH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getCwbh() {
		return cwbh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CWBH
	 * 
	 * @param cwbh
	 *            the value for ARC_COMB_INFO.CWBH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCwbh(String cwbh) {
		this.cwbh = cwbh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.XZQH
	 * 
	 * @return the value of ARC_COMB_INFO.XZQH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getXzqh() {
		return xzqh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.XZQH
	 * 
	 * @param xzqh
	 *            the value for ARC_COMB_INFO.XZQH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setXzqh(String xzqh) {
		this.xzqh = xzqh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.DEPTCODE
	 * 
	 * @return the value of ARC_COMB_INFO.DEPTCODE
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getDeptcode() {
		return deptcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.DEPTCODE
	 * 
	 * @param deptcode
	 *            the value for ARC_COMB_INFO.DEPTCODE
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.HDBJ
	 * 
	 * @return the value of ARC_COMB_INFO.HDBJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getHdbj() {
		return hdbj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.HDBJ
	 * 
	 * @param hdbj
	 *            the value for ARC_COMB_INFO.HDBJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setHdbj(String hdbj) {
		this.hdbj = hdbj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.XTDABH
	 * 
	 * @return the value of ARC_COMB_INFO.XTDABH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getXtdabh() {
		return xtdabh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.XTDABH
	 * 
	 * @param xtdabh
	 *            the value for ARC_COMB_INFO.XTDABH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setXtdabh(String xtdabh) {
		this.xtdabh = xtdabh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.ZXTDABH
	 * 
	 * @return the value of ARC_COMB_INFO.ZXTDABH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getZxtdabh() {
		return zxtdabh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.ZXTDABH
	 * 
	 * @param zxtdabh
	 *            the value for ARC_COMB_INFO.ZXTDABH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setZxtdabh(String zxtdabh) {
		this.zxtdabh = zxtdabh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CLPP2
	 * 
	 * @return the value of ARC_COMB_INFO.CLPP2
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getClpp2() {
		return clpp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CLPP2
	 * 
	 * @param clpp2
	 *            the value for ARC_COMB_INFO.CLPP2
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setClpp2(String clpp2) {
		this.clpp2 = clpp2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.GDRMC
	 * 
	 * @return the value of ARC_COMB_INFO.GDRMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getGdrmc() {
		return gdrmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.GDRMC
	 * 
	 * @param gdrmc
	 *            the value for ARC_COMB_INFO.GDRMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setGdrmc(String gdrmc) {
		this.gdrmc = gdrmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.ZZCMC
	 * 
	 * @return the value of ARC_COMB_INFO.ZZCMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getZzcmc() {
		return zzcmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.ZZCMC
	 * 
	 * @param zzcmc
	 *            the value for ARC_COMB_INFO.ZZCMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setZzcmc(String zzcmc) {
		this.zzcmc = zzcmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SFZMMC
	 * 
	 * @return the value of ARC_COMB_INFO.SFZMMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getSfzmmc() {
		return sfzmmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SFZMMC
	 * 
	 * @param sfzmmc
	 *            the value for ARC_COMB_INFO.SFZMMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setSfzmmc(String sfzmmc) {
		this.sfzmmc = sfzmmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.FZJG
	 * 
	 * @return the value of ARC_COMB_INFO.FZJG
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getFzjg() {
		return fzjg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.FZJG
	 * 
	 * @param fzjg
	 *            the value for ARC_COMB_INFO.FZJG
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setFzjg(String fzjg) {
		this.fzjg = fzjg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.DJRQ
	 * 
	 * @return the value of ARC_COMB_INFO.DJRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getDjrq() {
		return djrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.DJRQ
	 * 
	 * @param djrq
	 *            the value for ARC_COMB_INFO.DJRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setDjrq(Date djrq) {
		this.djrq = djrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SQRQ
	 * 
	 * @return the value of ARC_COMB_INFO.SQRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getSqrq() {
		return sqrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SQRQ
	 * 
	 * @param sqrq
	 *            the value for ARC_COMB_INFO.SQRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setSqrq(Date sqrq) {
		this.sqrq = sqrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CJR
	 * 
	 * @return the value of ARC_COMB_INFO.CJR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getCjr() {
		return cjr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CJR
	 * 
	 * @param cjr
	 *            the value for ARC_COMB_INFO.CJR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCjr(String cjr) {
		this.cjr = cjr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CJRMC
	 * 
	 * @return the value of ARC_COMB_INFO.CJRMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getCjrmc() {
		return cjrmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CJRMC
	 * 
	 * @param cjrmc
	 *            the value for ARC_COMB_INFO.CJRMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCjrmc(String cjrmc) {
		this.cjrmc = cjrmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CJSJ
	 * 
	 * @return the value of ARC_COMB_INFO.CJSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getCjsj() {
		return cjsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CJSJ
	 * 
	 * @param cjsj
	 *            the value for ARC_COMB_INFO.CJSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SHR
	 * 
	 * @return the value of ARC_COMB_INFO.SHR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getShr() {
		return shr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SHR
	 * 
	 * @param shr
	 *            the value for ARC_COMB_INFO.SHR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setShr(String shr) {
		this.shr = shr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SHRMC
	 * 
	 * @return the value of ARC_COMB_INFO.SHRMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getShrmc() {
		return shrmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SHRMC
	 * 
	 * @param shrmc
	 *            the value for ARC_COMB_INFO.SHRMC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setShrmc(String shrmc) {
		this.shrmc = shrmc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SHSJ
	 * 
	 * @return the value of ARC_COMB_INFO.SHSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getShsj() {
		return shsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SHSJ
	 * 
	 * @param shsj
	 *            the value for ARC_COMB_INFO.SHSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setShsj(Date shsj) {
		this.shsj = shsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.KFBJ
	 * 
	 * @return the value of ARC_COMB_INFO.KFBJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getKfbj() {
		return kfbj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.KFBJ
	 * 
	 * @param kfbj
	 *            the value for ARC_COMB_INFO.KFBJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setKfbj(String kfbj) {
		this.kfbj = kfbj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.BJRQ
	 * 
	 * @return the value of ARC_COMB_INFO.BJRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getBjrq() {
		return bjrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.BJRQ
	 * 
	 * @param bjrq
	 *            the value for ARC_COMB_INFO.BJRQ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setBjrq(Date bjrq) {
		this.bjrq = bjrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.PC
	 * 
	 * @return the value of ARC_COMB_INFO.PC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getPc() {
		return pc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.PC
	 * 
	 * @param pc
	 *            the value for ARC_COMB_INFO.PC
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setPc(String pc) {
		this.pc = pc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.SFBH
	 * 
	 * @return the value of ARC_COMB_INFO.SFBH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getSfbh() {
		return sfbh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.SFBH
	 * 
	 * @param sfbh
	 *            the value for ARC_COMB_INFO.SFBH
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setSfbh(String sfbh) {
		this.sfbh = sfbh;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CWSJ
	 * 
	 * @return the value of ARC_COMB_INFO.CWSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getCwsj() {
		return cwsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CWSJ
	 * 
	 * @param cwsj
	 *            the value for ARC_COMB_INFO.CWSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCwsj(String cwsj) {
		this.cwsj = cwsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.CWYX
	 * 
	 * @return the value of ARC_COMB_INFO.CWYX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getCwyx() {
		return cwyx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.CWYX
	 * 
	 * @param cwyx
	 *            the value for ARC_COMB_INFO.CWYX
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setCwyx(String cwyx) {
		this.cwyx = cwyx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.HDR
	 * 
	 * @return the value of ARC_COMB_INFO.HDR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getHdr() {
		return hdr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.HDR
	 * 
	 * @param hdr
	 *            the value for ARC_COMB_INFO.HDR
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setHdr(String hdr) {
		this.hdr = hdr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.HDRXM
	 * 
	 * @return the value of ARC_COMB_INFO.HDRXM
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public String getHdrxm() {
		return hdrxm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.HDRXM
	 * 
	 * @param hdrxm
	 *            the value for ARC_COMB_INFO.HDRXM
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setHdrxm(String hdrxm) {
		this.hdrxm = hdrxm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column ARC_COMB_INFO.HDSJ
	 * 
	 * @return the value of ARC_COMB_INFO.HDSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public Date getHdsj() {
		return hdsj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column ARC_COMB_INFO.HDSJ
	 * 
	 * @param hdsj
	 *            the value for ARC_COMB_INFO.HDSJ
	 * @abatorgenerated Mon Aug 18 14:49:14 CST 2014
	 */
	public void setHdsj(Date hdsj) {
		this.hdsj = hdsj;
	}
}