package com.pd.base.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.pd.base.model.Typeset;
import com.pd.base.model.TypesetExample;

public class TypesetDAOImpl extends SqlMapClientDaoSupport implements TypesetDAO {

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public TypesetDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public void insert(Typeset record) {
		getSqlMapClientTemplate().insert("TYPESET.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public int updateByPrimaryKey(Typeset record) {
		int rows = getSqlMapClientTemplate().update(
				"TYPESET.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public int updateByPrimaryKeySelective(Typeset record) {
		int rows = getSqlMapClientTemplate().update(
				"TYPESET.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public List selectByExample(TypesetExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TYPESET.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public Typeset selectByPrimaryKey(String id) {
		Typeset key = new Typeset();
		key.setId(id);
		Typeset record = (Typeset) getSqlMapClientTemplate().queryForObject(
				"TYPESET.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public int deleteByExample(TypesetExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TYPESET.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public int deleteByPrimaryKey(String id) {
		Typeset key = new Typeset();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TYPESET.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public int countByExample(TypesetExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TYPESET.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public int updateByExampleSelective(Typeset record, TypesetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TYPESET.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	public int updateByExample(Typeset record, TypesetExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TYPESET.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TYPESET
	 * @abatorgenerated  Thu Jul 04 14:07:35 CST 2013
	 */
	private static class UpdateByExampleParms extends TypesetExample {
		private Object record;

		public UpdateByExampleParms(Object record, TypesetExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Typeset> selectByExampleToPage(TypesetExample example) {
		List<Typeset> list = getSqlMapClientTemplate().queryForList("TYPESET.abatorgenerated_selectByExampleToPage", example);
	    return list;
	}
}