package com.pd.arc.model;

public class ArcCall {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ARC_CALL.CALLNUM
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    private String callnum;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ARC_CALL.CALLNUM
     *
     * @return the value of ARC_CALL.CALLNUM
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public String getCallnum() {
        return callnum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ARC_CALL.CALLNUM
     *
     * @param callnum the value for ARC_CALL.CALLNUM
     *
     * @abatorgenerated Tue Aug 19 16:13:47 CST 2014
     */
    public void setCallnum(String callnum) {
        this.callnum = callnum;
    }
}